gradle.properties, src/main/resources/META-INF/plugin.xml, src/test/java/com/redhat/devtools/intellij/quarkus/MavenImportingTestCase.java
=> Revert minimum requirement to 2018.3 and update plugin.xml accordingly

src/main/java/com/redhat/devtools/intellij/quarkus/QuarkusConstants.java, src/main/java/com/redhat/devtools/intellij/quarkus/module/QuarkusCodeEndpointChooserStep.java, src/main/java/com/redhat/devtools/intellij/quarkus/module/QuarkusModelRegistry.java, src/main/java/com/redhat/devtools/intellij/quarkus/module/QuarkusModuleBuilder.java, src/main/java/com/redhat/devtools/intellij/quarkus/module/QuarkusModuleInfoStep.java, src/test/java/com/redhat/devtools/intellij/quarkus/module/QuarkusModelRegistryTest.java
=> Add headers to requests sent to code.quarkus.io

.github/workflows/gradle.yml
=> Add GitHub action

src/main/resources/META-INF/plugin.xml
=> Update plugin description as required by JetBrains

src/main/java/com/redhat/devtools/intellij/quarkus/module/QuarkusModuleBuilder.java
=> Wizard uses path as version

src/main/java/com/redhat/devtools/intellij/quarkus/lsp/QuarkusLSPInitializer.java
=> Update server path

gradle.properties
=> Bump to 0.0.2

README.md, build.gradle, src/main/resources/META-INF/plugin.xml
=> Rename to Quarkus Tools

src/main/java/com/redhat/devtools/intellij/quarkus/module/QuarkusExtension.java, src/main/java/com/redhat/devtools/intellij/quarkus/module/QuarkusExtensionsStep.java, src/test/java/com/redhat/devtools/intellij/quarkus/module/QuarkusExtensionsTest.java, src/test/resources/single-preview-extension.json, src/test/resources/single-stable-extension.json
=> Add Preview label for preview extensions

src/main/java/com/redhat/devtools/intellij/quarkus/PluginHelper.java, src/main/java/com/redhat/devtools/intellij/quarkus/QuarkusPreloadActivity.java, src/main/java/com/redhat/devtools/intellij/quarkus/gradle/GradleToolDelegate.java, src/main/java/com/redhat/devtools/intellij/quarkus/lsp/QuarkusLanguageServerDefinition.java
=> Fix LSP messages by hacking lsp streams

build.gradle, src/main/resources/META-INF/plugin.xml
=> Prepare for 0.0.2

.travis.yml, README.md, build.gradle
=> Add codecov

gradle.properties, src/main/java/com/redhat/devtools/intellij/quarkus/QuarkusPostStartupActivity.java, src/main/java/com/redhat/devtools/intellij/quarkus/maven/MavenToolDelegate.java, src/main/java/com/redhat/devtools/intellij/quarkus/maven/QuarkusMavenLibraryImporter.java, src/main/java/com/redhat/devtools/intellij/quarkus/maven/QuarkusMavenProjectsProcessTask.java, src/main/resources/META-INF/plugin-maven.xml, src/main/resources/META-INF/plugin.xml
=> Fix proper initialization for Maven projects

src/main/resources/META-INF/plugin.xml
=> Prepare for 0.0.3

src/main/java/com/redhat/devtools/intellij/quarkus/maven/MavenToolDelegate.java, src/main/java/com/redhat/devtools/intellij/quarkus/tool/ToolDelegate.java
=> Fix ClassNotFoundError while running a JUnit test

gradle.properties
=> Bump to 0.0.4

src/main/java/com/redhat/devtools/intellij/quarkus/module/QuarkusExtension.java, src/test/java/com/redhat/devtools/intellij/quarkus/module/QuarkusExtensionsTest.java, src/test/resources/single-experimental-extension.json
=> Extensions with status other than preview should get status displayed

src/main/java/com/redhat/devtools/intellij/quarkus/module/QuarkusModelRegistry.java, src/main/java/com/redhat/devtools/intellij/quarkus/module/QuarkusModuleBuilder.java
=> User agent sent to code.quarkus.io is non Google Analytics compliant

.github/workflows/ci.yml, README.md
=> Add GitHub Actions CI

src/main/resources/META-INF/plugin.xml
Signed-off-by: Koen Aers <koen.aers@gmail.com>
=> #68: Lost color completion in application.properties

src/main/java/com/redhat/devtools/intellij/quarkus/facet/QuarkusLibraryType.java, src/main/java/com/redhat/devtools/intellij/quarkus/lang/ApplicationPropertiesFileType.java, src/main/java/com/redhat/devtools/intellij/quarkus/lang/ApplicationPropertiesLanguage.java
Also added a missing icon (just a suggestion).
=> Added highlighting to application properties

gradle/wrapper/gradle-wrapper.properties
Fixes #76
Signed-off-by: Koen Aers <koen.aers@gmail.com>
=> Update Gradle version to 6.3

src/main/java/com/redhat/devtools/intellij/quarkus/QuarkusConstants.java, src/test/java/com/redhat/devtools/intellij/quarkus/module/QuarkusModelRegistryTest.java
=> Use https://stage.code.quarkus.io while running tests

.github/workflows/IJ.yml
=> Add IJ check workflow

build.gradle
=> Fix Gradle build to support various IJ versions vs Java plugin

.github/workflows/IJ.yml, README.md
=> Execute IJ check versions worflow on PRs as well

src/main/java/com/redhat/devtools/intellij/quarkus/gradle/GradleToolDelegate.java
- Use reflection to create the Gradle import provider/builder as they removed the deprecated ones
Fixes #83
=> Fix compilation issue for 2019.2+

build.gradle
=> Ensure compilation is done for Java8

src/main/java/com/redhat/devtools/intellij/quarkus/module/QuarkusExtension.java, src/main/java/com/redhat/devtools/intellij/quarkus/module/QuarkusExtensionsStep.java, src/main/java/com/redhat/devtools/intellij/quarkus/module/QuarkusModuleBuilder.java, src/test/java/com/redhat/devtools/intellij/quarkus/module/QuarkusExtensionsTest.java, src/test/resources/single-extension-with-default.json, src/test/resources/single-extension-without-default.json
=> Pre-select default extensions

src/main/java/com/redhat/devtools/intellij/quarkus/lsp4ij/operations/completion/LSIncompleteCompletionProposal.java, src/main/java/com/redhat/devtools/intellij/quarkus/lsp4ij/operations/diagnostics/LSPDiagnosticsToMarkers.java
=> Fix LSP position / index issues

src/main/java/com/redhat/devtools/intellij/quarkus/module/QuarkusExtensionsStep.java
=> The right column with the extensions list is not scrollable

src/main/java/com/redhat/devtools/intellij/quarkus/lsp4ij/operations/completion/LSIncompleteCompletionProposal.java
=> Fix code assist offset management

src/main/java/com/redhat/devtools/intellij/quarkus/lang/QuarkusPropertiesSyntaxHighlighterFactory.java, src/main/resources/META-INF/plugin.xml
=> Add runtime dependency to Properties support

src/main/java/com/redhat/devtools/intellij/quarkus/QuarkusConstants.java, src/main/java/com/redhat/devtools/intellij/quarkus/module/QuarkusExtension.java, src/main/java/com/redhat/devtools/intellij/quarkus/module/QuarkusModelRegistry.java, src/main/java/com/redhat/devtools/intellij/quarkus/module/QuarkusModuleBuilder.java, src/test/java/com/redhat/devtools/intellij/quarkus/module/QuarkusExtensionsTest.java, src/test/java/com/redhat/devtools/intellij/quarkus/module/QuarkusModelRegistryTest.java, src/test/resources/single-extension.json
=> Use extension shortId when calling zip

src/main/java/com/redhat/devtools/intellij/quarkus/module/QuarkusExtensionsStep.java
=> Pre select first category

src/main/java/com/redhat/devtools/intellij/quarkus/lsp4ij/LSPIJUtils.java
=> Fix exception while inserting mutiple lines completions (qds)

src/main/java/com/redhat/devtools/intellij/quarkus/module/QuarkusModuleBuilder.java
=> Update Quarkus wizard tooltip

src/main/java/com/redhat/devtools/intellij/quarkus/lang/QuarkusIconProvider.java, src/main/java/com/redhat/devtools/intellij/quarkus/lang/QuarkusImplicitPropertyUsageProvider.java, src/main/resources/META-INF/plugin.xml
=> Remove warnings about not used property in application.properties

src/main/java/com/redhat/devtools/intellij/quarkus/search/ProjectLabelManager.java, src/main/java/com/redhat/devtools/intellij/quarkus/search/core/PropertiesManagerForJava.java
=> Fix read access in the project label manager

src/main/java/com/redhat/devtools/intellij/quarkus/module/QuarkusExtensionsStep.java
=> Add selected extensions in a separate column in wizard

src/main/java/com/redhat/devtools/intellij/quarkus/lsp4ij/operations/hover/LSPTextHover.java
=> Java documentation not available when Quarkus Tools is installed

gradle.properties, src/main/resources/META-INF/plugin.xml
=> Prepare for 1.0.1

src/main/java/com/redhat/devtools/intellij/quarkus/QuarkusModuleUtil.java
=> Fix NPE while loading some projects

src/main/java/com/redhat/devtools/intellij/quarkus/module/QuarkusExtension.java, src/main/java/com/redhat/devtools/intellij/quarkus/module/QuarkusExtensionsStep.java
=> Add extension description and guide in wizard

src/main/java/com/redhat/devtools/intellij/quarkus/lsp4ij/LSPIJUtils.java
=> Handle file with space

src/main/java/com/redhat/devtools/intellij/quarkus/lsp/QuarkusLanguageClient.java
=> Ensure LSP4J callback methods don't run on the LSP4J reader thread

src/main/java/com/redhat/devtools/intellij/quarkus/lsp4ij/operations/completion/LSIncompleteCompletionProposal.java
=> No completion proposition after %profile.

gradle.properties, src/main/resources/META-INF/plugin.xml
=> Prepare for 1.0.2

src/main/java/com/redhat/devtools/intellij/quarkus/lsp4ij/LoggingStreamConnectionProviderProxy.java
=> quarkus-tools trying to write log to root directory

src/main/java/com/redhat/devtools/intellij/quarkus/lsp4ij/LSPIJUtils.java, src/main/java/com/redhat/devtools/intellij/quarkus/lsp4ij/operations/hover/LSPTextHover.java
=> java.lang.NullPointerException while computing documentation

projects/gradle/config-properties/gradle.properties, projects/gradle/config-properties/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-context-propagation/gradle.properties, projects/gradle/microprofile-context-propagation/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-lra/gradle.properties, projects/gradle/microprofile-lra/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-openapi/gradle.properties, projects/gradle/microprofile-openapi/src/main/resources/META-INF/resources/index.html, projects/gradle/using-vertx/gradle.properties, projects/gradle/using-vertx/src/main/resources/META-INF/resources/index.html, src/main/resources/quarkus.xml
Fixes #168 
Tested on localhost, runtime is downloaded without any issue when new project is created.
=> Update the plugin runtime to version 1.6.0.Final

src/main/resources/META-INF/plugin.xml
=> Update contact mail

intellij-community/plugins/gradle/tooling-extension-impl/testSources/org/jetbrains/plugins/gradle/tooling/builder/AbstractModelBuilderTest.java, src/main/java/com/redhat/devtools/intellij/quarkus/javadoc/JavaDoc2HTMLTextReader.java, src/main/java/com/redhat/devtools/intellij/quarkus/search/PropertiesManager.java
Signed-off-by: PASER4SE <aarahman@ncsu.edu>
As mentioned in https://github.com/redhat-developer/intellij-quarkus/pull/183 added sign-off header ... will replace the existing two pull requests
=> Add missing default cases in switch statements

src/main/java/com/redhat/devtools/intellij/quarkus/lsp4ij/operations/completion/LSContentAssistProcessor.java
=> Fix deadlock while computing the completions

src/main/java/com/redhat/devtools/intellij/quarkus/QuarkusModuleUtil.java
=> NPE while loading projects

gradle.properties, src/main/resources/META-INF/plugin.xml
=> Prepare for 1.0.3

.github/workflows/IJ.yml, build.gradle
=> Add IntelliJ 2020.2

src/main/java/com/redhat/devtools/intellij/quarkus/lsp4ij/operations/completion/LSContentAssistProcessor.java
=> Fix deadlock while computing the completions (2)

gradle.properties, src/main/resources/META-INF/plugin.xml
=> Prepare for 1.0.4

src/main/java/com/redhat/devtools/intellij/quarkus/QuarkusModuleUtil.java
=> Fix NPE when loading project

src/main/java/com/redhat/devtools/intellij/quarkus/QuarkusModuleUtil.java, src/main/java/com/redhat/devtools/intellij/quarkus/lang/QuarkusIconProvider.java, src/main/java/com/redhat/devtools/intellij/quarkus/lang/QuarkusImplicitPropertyUsageProvider.java, src/main/java/com/redhat/devtools/intellij/quarkus/lang/QuarkusPropertyClassNameCompletionRemover.java, src/main/resources/META-INF/lsp.xml, src/main/resources/META-INF/plugin.xml
=> Remove class scanning in content assist after the = sign

src/main/java/com/redhat/devtools/intellij/quarkus/module/QuarkusExtensionsStep.java
=> Selected extensions column is now scrollable

src/main/java/com/redhat/devtools/intellij/quarkus/gradle/GradleToolDelegate.java
=> Fix Gradle init exception on Java11

src/main/java/com/redhat/devtools/intellij/quarkus/lsp/QuarkusLanguageClient.java
=> java.lang.Throwable: Must be executed under progress indicator:

projects/gradle/config-properties/gradle.properties, projects/gradle/config-properties/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-context-propagation/gradle.properties, projects/gradle/microprofile-context-propagation/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-lra/gradle.properties, projects/gradle/microprofile-lra/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-openapi/gradle.properties, projects/gradle/microprofile-openapi/src/main/resources/META-INF/resources/index.html, projects/gradle/using-vertx/gradle.properties, projects/gradle/using-vertx/src/main/resources/META-INF/resources/index.html, src/main/resources/quarkus.xml
Fixes #232
Tested on localhost, new version of runtime is available and downloaded without any issue.
=> Update the plugin runtime to version 1.8.1.Final

src/main/resources/META-INF/lsp.xml
=> Update server to match LSP4MP Java namespac

projects/gradle/config-properties/gradle.properties, projects/gradle/config-properties/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-context-propagation/gradle.properties, projects/gradle/microprofile-context-propagation/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-graphql/gradle.properties, projects/gradle/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-health/gradle.properties, projects/gradle/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-jwt/gradle.properties, projects/gradle/microprofile-jwt/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-lra/gradle.properties, projects/gradle/microprofile-lra/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-openapi/gradle.properties, projects/gradle/microprofile-openapi/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-reactive-messaging/gradle.properties, projects/gradle/microprofile-reactive-messaging/src/main/resources/META-INF/resources/index.html, projects/gradle/using-vertx/gradle.properties, projects/gradle/using-vertx/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-graphql/pom.xml, projects/maven/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-health/pom.xml, projects/maven/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-jwt/pom.xml, projects/maven/microprofile-jwt/src/main/resources/META-INF/resources/index.html, src/main/resources/quarkus.xml
Fixes #256
Tested on localhost, new version of runtime is available and downloaded without any issue.
=> Update the plugin runtime to version 1.8.2.Final

projects/gradle/config-properties/gradle.properties, projects/gradle/config-properties/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-context-propagation/gradle.properties, projects/gradle/microprofile-context-propagation/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-graphql/gradle.properties, projects/gradle/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-health/gradle.properties, projects/gradle/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-jwt/gradle.properties, projects/gradle/microprofile-jwt/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-lra/gradle.properties, projects/gradle/microprofile-lra/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-openapi/gradle.properties, projects/gradle/microprofile-openapi/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-reactive-messaging/gradle.properties, projects/gradle/microprofile-reactive-messaging/src/main/resources/META-INF/resources/index.html, projects/gradle/using-vertx/gradle.properties, projects/gradle/using-vertx/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-graphql/pom.xml, projects/maven/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-health/pom.xml, projects/maven/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-jwt/pom.xml, projects/maven/microprofile-jwt/src/main/resources/META-INF/resources/index.html, src/main/resources/quarkus.xml
Fixes #259
Tested on localhost, new version of runtime is available and downloaded without any issue.
=> Update the plugin runtime to version 1.8.3.Final

gradle.properties, src/main/resources/META-INF/plugin.xml
=> Prepare for 1.2.0

Jenkinsfile
=> Handle spaces in rsync

src/main/resources/META-INF/plugin.xml, src/test/java/com/redhat/devtools/intellij/quarkus/completion/MavenApplicationYamlCompletionTest.java
=> Update minimal IJ version in plugin.xml

src/main/java/com/redhat/devtools/intellij/quarkus/module/QuarkusModelRegistry.java, src/test/java/com/redhat/devtools/intellij/quarkus/module/QuarkusModelRegistryTest.java
=> Cleanup url before calling code.quarkus.io or equivalent

src/main/java/com/redhat/devtools/intellij/quarkus/module/QuarkusModelRegistry.java
=> Prevent IOException to be logged

.github/workflows/update.yml
=> Add new workflow for updating Quarkus version in plugin

projects/gradle/config-properties/gradle.properties, projects/gradle/config-properties/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-context-propagation/gradle.properties, projects/gradle/microprofile-context-propagation/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-graphql/gradle.properties, projects/gradle/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-health/gradle.properties, projects/gradle/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-jwt/gradle.properties, projects/gradle/microprofile-jwt/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-lra/gradle.properties, projects/gradle/microprofile-lra/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-openapi/gradle.properties, projects/gradle/microprofile-openapi/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-reactive-messaging/gradle.properties, projects/gradle/microprofile-reactive-messaging/src/main/resources/META-INF/resources/index.html, projects/gradle/using-vertx/gradle.properties, projects/gradle/using-vertx/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-graphql/pom.xml, projects/maven/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-health/pom.xml, projects/maven/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-jwt/pom.xml, projects/maven/microprofile-jwt/src/main/resources/META-INF/resources/index.html, src/main/resources/quarkus.xml, src/test/java/com/redhat/devtools/intellij/quarkus/gradle/GradleMicroProfileReactiveMessagingTest.java
Fixes #267
Tested on localhost, new version of runtime is available and downloaded without any issue.
=> Update the plugin runtime to version 1.9.0.Final

.github/workflows/update.yml
=> Add signoff to update workflow

projects/gradle/config-properties/gradle.properties, projects/gradle/config-properties/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-context-propagation/gradle.properties, projects/gradle/microprofile-context-propagation/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-graphql/gradle.properties, projects/gradle/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-health/gradle.properties, projects/gradle/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-jwt/gradle.properties, projects/gradle/microprofile-jwt/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-lra/gradle.properties, projects/gradle/microprofile-lra/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-openapi/gradle.properties, projects/gradle/microprofile-openapi/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-reactive-messaging/gradle.properties, projects/gradle/microprofile-reactive-messaging/src/main/resources/META-INF/resources/index.html, projects/gradle/using-vertx/gradle.properties, projects/gradle/using-vertx/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-graphql/pom.xml, projects/maven/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-health/pom.xml, projects/maven/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-jwt/pom.xml, projects/maven/microprofile-jwt/src/main/resources/META-INF/resources/index.html, src/main/resources/quarkus.xml
=> Switch Quarkus runtime to 1.9.1.Final

projects/gradle/config-properties/gradle.properties, projects/gradle/config-properties/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-context-propagation/gradle.properties, projects/gradle/microprofile-context-propagation/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-graphql/gradle.properties, projects/gradle/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-health/gradle.properties, projects/gradle/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-jwt/gradle.properties, projects/gradle/microprofile-jwt/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-lra/gradle.properties, projects/gradle/microprofile-lra/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-openapi/gradle.properties, projects/gradle/microprofile-openapi/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-reactive-messaging/gradle.properties, projects/gradle/microprofile-reactive-messaging/src/main/resources/META-INF/resources/index.html, projects/gradle/using-vertx/gradle.properties, projects/gradle/using-vertx/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-graphql/pom.xml, projects/maven/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-health/pom.xml, projects/maven/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-jwt/pom.xml, projects/maven/microprofile-jwt/src/main/resources/META-INF/resources/index.html, src/main/resources/quarkus.xml
=> Switch Quarkus runtime to 1.9.2.Final

src/main/java/com/redhat/devtools/intellij/quarkus/lang/QuarkusIconProvider.java
=> Fix NPE in QuarkusIconProvider

src/it/java/org/jboss/tools/intellij/quarkus/BasicTests.java, src/it/java/org/jboss/tools/intellij/quarkus/utils/GlobalUtils.java
Fixes #272
Tested on localhost (this PR makes sure the workspace in IntelliJ and the project folder on the disk is empty at the beginning of the testing and it also clears it after each test).
Please review @jeffmaury @jrichter1
=> Fix the 'File Already Exists' issues during UI tests

README.md
Fixes 287
@jeffmaury Please review
=> Add steps to run UI tests to the README.md

src/test/java/com/redhat/devtools/intellij/quarkus/completion/MavenApplicationYamlCompletionTest.java
=> Fix unstable YAML test

projects/gradle/config-properties/gradle.properties, projects/gradle/config-properties/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-context-propagation/gradle.properties, projects/gradle/microprofile-context-propagation/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-graphql/gradle.properties, projects/gradle/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-health/gradle.properties, projects/gradle/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-jwt/gradle.properties, projects/gradle/microprofile-jwt/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-lra/gradle.properties, projects/gradle/microprofile-lra/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-openapi/gradle.properties, projects/gradle/microprofile-openapi/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-reactive-messaging/gradle.properties, projects/gradle/microprofile-reactive-messaging/src/main/resources/META-INF/resources/index.html, projects/gradle/using-vertx/gradle.properties, projects/gradle/using-vertx/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-graphql/pom.xml, projects/maven/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-health/pom.xml, projects/maven/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-jwt/pom.xml, projects/maven/microprofile-jwt/src/main/resources/META-INF/resources/index.html, src/main/resources/quarkus.xml
=> Switch Quarkus runtime to 1.10.2.Final

projects/gradle/config-properties/gradle.properties, projects/gradle/config-properties/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-context-propagation/gradle.properties, projects/gradle/microprofile-context-propagation/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-graphql/gradle.properties, projects/gradle/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-health/gradle.properties, projects/gradle/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-jwt/gradle.properties, projects/gradle/microprofile-jwt/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-lra/gradle.properties, projects/gradle/microprofile-lra/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-openapi/gradle.properties, projects/gradle/microprofile-openapi/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-reactive-messaging/gradle.properties, projects/gradle/microprofile-reactive-messaging/src/main/resources/META-INF/resources/index.html, projects/gradle/using-vertx/gradle.properties, projects/gradle/using-vertx/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-graphql/pom.xml, projects/maven/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-health/pom.xml, projects/maven/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-jwt/pom.xml, projects/maven/microprofile-jwt/src/main/resources/META-INF/resources/index.html, src/main/resources/quarkus.xml
=> Switch Quarkus runtime to 1.10.3.Final

src/test/java/com/redhat/devtools/intellij/quarkus/completion/MavenApplicationPropertiesCompletionTest.java
=> Fix properties test

.github/workflows/update.yml
Fixes #313
@jeffmaury please review and we can discuss together with @vkuznyetsov
=> Rename of the titles and branch names of automatically generated PRs for updating the Quarkus runtime version.

.github/workflows/IJ.yml
=> Add IntelliJ 2020.3

src/it/java/org/jboss/tools/intellij/quarkus/utils/GlobalUtils.java
=> Update UI tests for situation when ~/IdeaProjects is missing

projects/gradle/config-properties/gradle.properties, projects/gradle/config-properties/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-context-propagation/gradle.properties, projects/gradle/microprofile-context-propagation/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-graphql/gradle.properties, projects/gradle/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-health/gradle.properties, projects/gradle/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-jwt/gradle.properties, projects/gradle/microprofile-jwt/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-lra/gradle.properties, projects/gradle/microprofile-lra/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-openapi/gradle.properties, projects/gradle/microprofile-openapi/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-reactive-messaging/gradle.properties, projects/gradle/microprofile-reactive-messaging/src/main/resources/META-INF/resources/index.html, projects/gradle/using-vertx/gradle.properties, projects/gradle/using-vertx/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-graphql/pom.xml, projects/maven/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-health/pom.xml, projects/maven/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-jwt/pom.xml, projects/maven/microprofile-jwt/src/main/resources/META-INF/resources/index.html, src/main/resources/quarkus.xml
=> Update the Quarkus runtime used by the plugin to version 1.10.4.Final

src/it/java/org/jboss/tools/intellij/quarkus/fixtures/mainIdeWindow/CustomHeaderMenuBarFixture.java, src/it/java/org/jboss/tools/intellij/quarkus/fixtures/mainIdeWindow/LinuxIdeMenuBarFixture.java, src/it/java/org/jboss/tools/intellij/quarkus/utils/GlobalUtils.java
- tested on localhost - OS X, Windows, Linux
Fixes #320
Please review @jrichter1 @jeffmaury
=> Update the "closeTheProject()" method for Linux and Windows.

src/main/java/com/redhat/devtools/intellij/quarkus/lsp/QuarkusLanguageClient.java
=> Protect NPE

.github/workflows/update.yml
=> Use platform instead of core for reference

src/main/java/com/redhat/devtools/intellij/quarkus/lsp/QuarkusLanguageClient.java
=> Synchronize on dumb mode when processing LSP4MP events

.github/workflows/ci.yml
=> Archive tests results per platform

.sonarcloud.properties
=> Update Sonarcloud configuration

src/main/java/com/redhat/devtools/intellij/quarkus/QuarkusConstants.java, src/main/java/com/redhat/devtools/intellij/quarkus/module/QuarkusModuleBuilder.java, src/main/java/com/redhat/devtools/intellij/quarkus/module/QuarkusModuleInfoStep.java, src/test/java/com/redhat/devtools/intellij/quarkus/module/QuarkusModelRegistryTest.java
=> Support codestart option in project wizard

src/main/java/com/redhat/devtools/intellij/quarkus/lsp/QuarkusLanguageClient.java
=> Call background tasks directly while modal dialog is on

build.gradle
Fixes #347
Please review @jrichter1 @jeffmaury
=> Update the Remote-Robot framework to version 0.10.3

gradle.properties, src/main/resources/META-INF/plugin.xml
=> Prepare for 1.3.0

src/it/java/org/jboss/tools/intellij/quarkus/fixtures/popups/SearchEverywherePopupFixture.java, src/it/java/org/jboss/tools/intellij/quarkus/utils/GlobalUtils.java
- tested on localhost on OS X, linux, Windows
Fixes #332
=> Extend the UI tests to support invoking a command using the 'Search Everywhere' popup

projects/gradle/config-properties/gradle.properties, projects/gradle/config-properties/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-context-propagation/gradle.properties, projects/gradle/microprofile-context-propagation/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-graphql/gradle.properties, projects/gradle/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-health/gradle.properties, projects/gradle/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-jwt/gradle.properties, projects/gradle/microprofile-jwt/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-lra/gradle.properties, projects/gradle/microprofile-lra/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-openapi/gradle.properties, projects/gradle/microprofile-openapi/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-reactive-messaging/gradle.properties, projects/gradle/microprofile-reactive-messaging/src/main/resources/META-INF/resources/index.html, projects/gradle/using-vertx/gradle.properties, projects/gradle/using-vertx/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-graphql/pom.xml, projects/maven/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-health/pom.xml, projects/maven/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-jwt/pom.xml, projects/maven/microprofile-jwt/src/main/resources/META-INF/resources/index.html, src/main/resources/quarkus.xml
=> Update the Quarkus runtime used by the plugin to version 1.11.0.Final

src/main/java/com/redhat/devtools/intellij/quarkus/module/QuarkusCodeEndpointChooserStep.java
=> Remove use of AllIcons.Actions.ShowViewer

projects/gradle/config-properties/gradle.properties, projects/gradle/config-properties/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-context-propagation/gradle.properties, projects/gradle/microprofile-context-propagation/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-graphql/gradle.properties, projects/gradle/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-health/gradle.properties, projects/gradle/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-jwt/gradle.properties, projects/gradle/microprofile-jwt/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-lra/gradle.properties, projects/gradle/microprofile-lra/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-openapi/gradle.properties, projects/gradle/microprofile-openapi/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-reactive-messaging/gradle.properties, projects/gradle/microprofile-reactive-messaging/src/main/resources/META-INF/resources/index.html, projects/gradle/using-vertx/gradle.properties, projects/gradle/using-vertx/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-graphql/pom.xml, projects/maven/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-health/pom.xml, projects/maven/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-jwt/pom.xml, projects/maven/microprofile-jwt/src/main/resources/META-INF/resources/index.html, src/main/resources/quarkus.xml
=> Update the Quarkus runtime used by the plugin to version 1.11.1.Final

.github/workflows/accepted, .github/workflows/ci.yml, .github/workflows/prefs.xml, src/it/java/org/jboss/tools/intellij/quarkus/BasicTests.java, src/it/java/org/jboss/tools/intellij/quarkus/fixtures/dialogs/NewProjectDialogFixture.java, src/it/java/org/jboss/tools/intellij/quarkus/fixtures/mainIdeWindow/ProjectToolWindowFixture.java, src/it/java/org/jboss/tools/intellij/quarkus/fixtures/quarkus/DownloadingOptionsDialogFixture.java, src/it/java/org/jboss/tools/intellij/quarkus/utils/GlobalUtils.java, src/it/java/org/jboss/tools/intellij/quarkus/utils/HelperUtils.java, src/it/java/org/jboss/tools/intellij/quarkus/utils/ProjectToolWindowUtils.java, src/it/java/org/jboss/tools/intellij/quarkus/utils/QuarkusUtils.java
=> Automate UI test that creates new Quarkus project and tests whether the runtime has been downloaded

.github/workflows/ci.yml, README.md, src/it/java/org/jboss/tools/intellij/quarkus/BasicTests.java, src/it/java/org/jboss/tools/intellij/quarkus/fixtures/dialogs/NewProjectDialogFixture.java, src/it/java/org/jboss/tools/intellij/quarkus/fixtures/dialogs/WelcomeFrameDialogFixture.java, src/it/java/org/jboss/tools/intellij/quarkus/fixtures/mainIdeWindow/IdeStatusBarFixture.java, src/it/java/org/jboss/tools/intellij/quarkus/utils/BuildUtils.java, src/it/java/org/jboss/tools/intellij/quarkus/utils/GlobalUtils.java
Add new automated test and updates for changes in UI:
- Fixes #217
- Fixes #305
Please review @jrichter1 @jeffmaury
=> Automate basic UI test that creates new Quarkus project and builds it using gradle (+ update for UI changes in 2020.2 IntelliJ)

src/main/java/com/redhat/devtools/intellij/quarkus/QuarkusProjectService.java
=> Compute schema when indexing is not running

src/main/java/com/redhat/devtools/intellij/quarkus/lsp4ij/operations/navigation/LSPGotoDeclarationHandler.java
=> fix: add timeout for definition request (goto, references)

projects/gradle/config-properties/gradle.properties, projects/gradle/config-properties/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-context-propagation/gradle.properties, projects/gradle/microprofile-context-propagation/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-graphql/gradle.properties, projects/gradle/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-health/gradle.properties, projects/gradle/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-jwt/gradle.properties, projects/gradle/microprofile-jwt/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-lra/gradle.properties, projects/gradle/microprofile-lra/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-openapi/gradle.properties, projects/gradle/microprofile-openapi/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-reactive-messaging/gradle.properties, projects/gradle/microprofile-reactive-messaging/src/main/resources/META-INF/resources/index.html, projects/gradle/using-vertx/gradle.properties, projects/gradle/using-vertx/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-graphql/pom.xml, projects/maven/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-health/pom.xml, projects/maven/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-jwt/pom.xml, projects/maven/microprofile-jwt/src/main/resources/META-INF/resources/index.html, src/main/resources/quarkus.xml
=> Update the Quarkus runtime used by the plugin to version 1.11.2.Final

src/it/java/org/jboss/tools/intellij/quarkus/BasicTests.java, src/it/java/org/jboss/tools/intellij/quarkus/fixtures/dialogs/WelcomeFrameDialogFixture.java, src/it/java/org/jboss/tools/intellij/quarkus/utils/BuildUtils.java, src/it/java/org/jboss/tools/intellij/quarkus/utils/GlobalUtils.java, src/it/java/org/jboss/tools/intellij/quarkus/utils/QuarkusUtils.java
=> Add UI tests - create new Quarkus project with custom endpoint URL

src/main/java/com/redhat/devtools/intellij/quarkus/module/QuarkusExtensionsStep.java
=> fix: exception when selecting a category in the new project wizard

projects/gradle/config-properties/gradle.properties, projects/gradle/config-properties/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-context-propagation/gradle.properties, projects/gradle/microprofile-context-propagation/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-graphql/gradle.properties, projects/gradle/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-health/gradle.properties, projects/gradle/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-jwt/gradle.properties, projects/gradle/microprofile-jwt/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-lra/gradle.properties, projects/gradle/microprofile-lra/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-openapi/gradle.properties, projects/gradle/microprofile-openapi/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-reactive-messaging/gradle.properties, projects/gradle/microprofile-reactive-messaging/src/main/resources/META-INF/resources/index.html, projects/gradle/using-vertx/gradle.properties, projects/gradle/using-vertx/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-graphql/pom.xml, projects/maven/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-health/pom.xml, projects/maven/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-jwt/pom.xml, projects/maven/microprofile-jwt/src/main/resources/META-INF/resources/index.html, src/main/resources/quarkus.xml
=> Update the Quarkus runtime used by the plugin to version 1.11.3.Final

gradle.properties, src/main/resources/META-INF/plugin.xml
=> Prepare for 1.4.0

src/main/java/com/redhat/devtools/intellij/quarkus/module/QuarkusExtensionsStep.java
=> fix: allow only one category

projects/gradle/config-properties/gradle.properties, projects/gradle/config-properties/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-context-propagation/gradle.properties, projects/gradle/microprofile-context-propagation/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-graphql/gradle.properties, projects/gradle/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-health/gradle.properties, projects/gradle/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-jwt/gradle.properties, projects/gradle/microprofile-jwt/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-lra/gradle.properties, projects/gradle/microprofile-lra/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-openapi/gradle.properties, projects/gradle/microprofile-openapi/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-reactive-messaging/gradle.properties, projects/gradle/microprofile-reactive-messaging/src/main/resources/META-INF/resources/index.html, projects/gradle/using-vertx/gradle.properties, projects/gradle/using-vertx/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-graphql/pom.xml, projects/maven/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-health/pom.xml, projects/maven/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-jwt/pom.xml, projects/maven/microprofile-jwt/src/main/resources/META-INF/resources/index.html, src/main/resources/quarkus.xml
=> Update the Quarkus runtime used by the plugin to version 1.12.0.Final

src/main/java/com/redhat/devtools/intellij/quarkus/QuarkusConstants.java, src/main/java/com/redhat/devtools/intellij/quarkus/module/QuarkusModelRegistry.java
=> refactor: use POST request in wizard

.github/workflows/conventionalCheck.yml, .github/workflows/release.yml
=> chore: add conventional commits check and release workflows

projects/gradle/config-properties/gradle.properties, projects/gradle/config-properties/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-context-propagation/gradle.properties, projects/gradle/microprofile-context-propagation/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-graphql/gradle.properties, projects/gradle/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-health/gradle.properties, projects/gradle/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-jwt/gradle.properties, projects/gradle/microprofile-jwt/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-lra/gradle.properties, projects/gradle/microprofile-lra/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-openapi/gradle.properties, projects/gradle/microprofile-openapi/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-reactive-messaging/gradle.properties, projects/gradle/microprofile-reactive-messaging/src/main/resources/META-INF/resources/index.html, projects/gradle/using-vertx/gradle.properties, projects/gradle/using-vertx/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-graphql/pom.xml, projects/maven/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-health/pom.xml, projects/maven/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-jwt/pom.xml, projects/maven/microprofile-jwt/src/main/resources/META-INF/resources/index.html, src/main/resources/quarkus.xml
=> Update the Quarkus runtime used by the plugin to version 1.12.1.Final

.github/workflows/update.yml
=> chore: update workflow to use conventional commits

projects/gradle/config-properties/gradle.properties, projects/gradle/config-properties/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-context-propagation/gradle.properties, projects/gradle/microprofile-context-propagation/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-graphql/gradle.properties, projects/gradle/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-health/gradle.properties, projects/gradle/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-jwt/gradle.properties, projects/gradle/microprofile-jwt/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-lra/gradle.properties, projects/gradle/microprofile-lra/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-openapi/gradle.properties, projects/gradle/microprofile-openapi/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-reactive-messaging/gradle.properties, projects/gradle/microprofile-reactive-messaging/src/main/resources/META-INF/resources/index.html, projects/gradle/using-vertx/gradle.properties, projects/gradle/using-vertx/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-graphql/pom.xml, projects/maven/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-health/pom.xml, projects/maven/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-jwt/pom.xml, projects/maven/microprofile-jwt/src/main/resources/META-INF/resources/index.html, src/main/resources/quarkus.xml
=> fix: Update the Quarkus runtime used by the plugin to version 1.13.0.Final

.github/workflows/IJ.yml, .github/workflows/ci.yml, src/main/java/com/redhat/devtools/intellij/quarkus/QuarkusPostStartupActivity.java, src/main/java/com/redhat/devtools/intellij/quarkus/maven/QuarkusMavenProjectsProcessTask.java
=> chore: Switch to main branch

.github/workflows/IJ.yml, build.gradle, gradle.properties, intellij-community/java/compiler/tests/com/intellij/compiler/artifacts/ArtifactsTestUtil.java, intellij-community/platform/external-system-impl/testSrc/com/intellij/openapi/externalSystem/test/ExternalSystemImportingTestCase.java, intellij-community/platform/external-system-impl/testSrc/com/intellij/openapi/externalSystem/test/ExternalSystemTestCase.java, intellij-community/platform/testFramework/extensions/src/com/intellij/testFramework/assertions/Assertions.java, intellij-community/platform/testFramework/extensions/src/com/intellij/testFramework/assertions/JdomAssert.kt, intellij-community/platform/testFramework/extensions/src/com/intellij/testFramework/assertions/PathAssertEx.kt, intellij-community/platform/testFramework/extensions/src/com/intellij/testFramework/assertions/StringAssertEx.kt, intellij-community/platform/testFramework/extensions/src/com/intellij/testFramework/assertions/snapshot.kt, intellij-community/plugins/gradle/testSources/org/jetbrains/plugins/gradle/importing/GradleImportingTestCase.java, intellij-community/plugins/gradle/tooling-extension-impl/testSources/org/jetbrains/plugins/gradle/tooling/builder/AbstractModelBuilderTest.java, pulltest.sh, src/main/java/com/redhat/devtools/intellij/quarkus/QuarkusModuleUtil.java, src/main/java/com/redhat/devtools/intellij/quarkus/TelemetryService.java, src/main/java/com/redhat/devtools/intellij/quarkus/gradle/GradleToolDelegate.java, src/main/java/com/redhat/devtools/intellij/quarkus/lsp/QuarkusServer.java, src/main/java/com/redhat/devtools/intellij/quarkus/module/QuarkusModuleBuilder.java, src/main/resources/META-INF/plugin.xml, src/test/java/com/redhat/devtools/intellij/quarkus/gradle/GradleTestCase.java, src/test/java/com/redhat/devtools/intellij/quarkus/maven/MavenTestCase.java
=> feat: Add telemetry

projects/gradle/config-properties/gradle.properties, projects/gradle/config-properties/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-context-propagation/gradle.properties, projects/gradle/microprofile-context-propagation/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-graphql/gradle.properties, projects/gradle/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-health/gradle.properties, projects/gradle/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-jwt/gradle.properties, projects/gradle/microprofile-jwt/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-lra/gradle.properties, projects/gradle/microprofile-lra/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-openapi/gradle.properties, projects/gradle/microprofile-openapi/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-reactive-messaging/gradle.properties, projects/gradle/microprofile-reactive-messaging/src/main/resources/META-INF/resources/index.html, projects/gradle/using-vertx/gradle.properties, projects/gradle/using-vertx/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-graphql/pom.xml, projects/maven/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-health/pom.xml, projects/maven/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-jwt/pom.xml, projects/maven/microprofile-jwt/src/main/resources/META-INF/resources/index.html, src/main/resources/quarkus.xml
=> fix: Update the Quarkus runtime used by the plugin to version 1.13.2.Final

build.gradle, src/main/java/com/redhat/devtools/intellij/quarkus/lsp/QuarkusServer.java
=> chore: Use LSP4MP 0.2.1 and quarkus-ls 0.10.0

README.md, USAGE_DATA.md, gradle.properties, src/main/resources/META-INF/plugin.xml
=> chore: Prepare 1.5.0

projects/gradle/config-properties/gradle.properties, projects/gradle/config-properties/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-context-propagation/gradle.properties, projects/gradle/microprofile-context-propagation/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-graphql/gradle.properties, projects/gradle/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-health/gradle.properties, projects/gradle/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-jwt/gradle.properties, projects/gradle/microprofile-jwt/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-lra/gradle.properties, projects/gradle/microprofile-lra/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-openapi/gradle.properties, projects/gradle/microprofile-openapi/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-reactive-messaging/gradle.properties, projects/gradle/microprofile-reactive-messaging/src/main/resources/META-INF/resources/index.html, projects/gradle/using-vertx/gradle.properties, projects/gradle/using-vertx/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-graphql/pom.xml, projects/maven/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-health/pom.xml, projects/maven/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-jwt/pom.xml, projects/maven/microprofile-jwt/src/main/resources/META-INF/resources/index.html, src/main/resources/quarkus.xml
=> fix: Update the Quarkus runtime used by the plugin to version 1.13.3.Final

README.md
=> fix: Update the cmd to run UI tests in the README.md file

build.gradle
=> chore: Update the Remote-Robot version to 0.11.2

projects/gradle/config-properties/gradle.properties, projects/gradle/config-properties/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-context-propagation/gradle.properties, projects/gradle/microprofile-context-propagation/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-graphql/gradle.properties, projects/gradle/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-health/gradle.properties, projects/gradle/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-jwt/gradle.properties, projects/gradle/microprofile-jwt/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-lra/gradle.properties, projects/gradle/microprofile-lra/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-openapi/gradle.properties, projects/gradle/microprofile-openapi/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-reactive-messaging/gradle.properties, projects/gradle/microprofile-reactive-messaging/src/main/resources/META-INF/resources/index.html, projects/gradle/using-vertx/gradle.properties, projects/gradle/using-vertx/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-graphql/pom.xml, projects/maven/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-health/pom.xml, projects/maven/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-jwt/pom.xml, projects/maven/microprofile-jwt/src/main/resources/META-INF/resources/index.html, src/main/resources/quarkus.xml
=> fix: Update the Quarkus runtime used by the plugin to version 1.13.4.Final

projects/gradle/config-properties/gradle.properties, projects/gradle/config-properties/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-context-propagation/gradle.properties, projects/gradle/microprofile-context-propagation/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-graphql/gradle.properties, projects/gradle/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-health/gradle.properties, projects/gradle/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-jwt/gradle.properties, projects/gradle/microprofile-jwt/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-lra/gradle.properties, projects/gradle/microprofile-lra/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-openapi/gradle.properties, projects/gradle/microprofile-openapi/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-reactive-messaging/gradle.properties, projects/gradle/microprofile-reactive-messaging/src/main/resources/META-INF/resources/index.html, projects/gradle/using-vertx/gradle.properties, projects/gradle/using-vertx/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-graphql/pom.xml, projects/maven/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-health/pom.xml, projects/maven/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-jwt/pom.xml, projects/maven/microprofile-jwt/src/main/resources/META-INF/resources/index.html, src/main/resources/quarkus.xml
=> fix: Update the Quarkus runtime used by the plugin to version 1.13.5.Final

.github/workflows/ci.yml, projects/gradle/config-properties/gradle.properties, projects/gradle/config-properties/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-context-propagation/gradle.properties, projects/gradle/microprofile-context-propagation/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-graphql/gradle.properties, projects/gradle/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-health/gradle.properties, projects/gradle/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-jwt/gradle.properties, projects/gradle/microprofile-jwt/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-lra/gradle.properties, projects/gradle/microprofile-lra/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-openapi/gradle.properties, projects/gradle/microprofile-openapi/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-reactive-messaging/gradle.properties, projects/gradle/microprofile-reactive-messaging/src/main/resources/META-INF/resources/index.html, projects/gradle/using-vertx/gradle.properties, projects/gradle/using-vertx/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-graphql/pom.xml, projects/maven/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-health/pom.xml, projects/maven/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-jwt/pom.xml, projects/maven/microprofile-jwt/src/main/resources/META-INF/resources/index.html, src/main/resources/quarkus.xml, src/test/java/com/redhat/devtools/intellij/quarkus/gradle/GradleMicroProfileJWTTest.java, src/test/java/com/redhat/devtools/intellij/quarkus/maven/MavenMicroProfileJWTTest.java
=> fix: Update the Quarkus runtime used by the plugin to version 2.0.1.Final

projects/gradle/config-properties/gradle.properties, projects/gradle/config-properties/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-context-propagation/gradle.properties, projects/gradle/microprofile-context-propagation/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-graphql/gradle.properties, projects/gradle/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-health/gradle.properties, projects/gradle/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-jwt/gradle.properties, projects/gradle/microprofile-jwt/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-lra/gradle.properties, projects/gradle/microprofile-lra/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-openapi/gradle.properties, projects/gradle/microprofile-openapi/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-reactive-messaging/gradle.properties, projects/gradle/microprofile-reactive-messaging/src/main/resources/META-INF/resources/index.html, projects/gradle/using-vertx/gradle.properties, projects/gradle/using-vertx/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-graphql/pom.xml, projects/maven/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-health/pom.xml, projects/maven/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-jwt/pom.xml, projects/maven/microprofile-jwt/src/main/resources/META-INF/resources/index.html, src/main/resources/quarkus.xml
=> fix: Update the Quarkus runtime used by the plugin to version 2.0.2.Final

projects/gradle/config-properties/gradle.properties, projects/gradle/config-properties/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-context-propagation/gradle.properties, projects/gradle/microprofile-context-propagation/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-graphql/gradle.properties, projects/gradle/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-health/gradle.properties, projects/gradle/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-jwt/gradle.properties, projects/gradle/microprofile-jwt/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-lra/gradle.properties, projects/gradle/microprofile-lra/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-openapi/gradle.properties, projects/gradle/microprofile-openapi/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-reactive-messaging/gradle.properties, projects/gradle/microprofile-reactive-messaging/src/main/resources/META-INF/resources/index.html, projects/gradle/using-vertx/gradle.properties, projects/gradle/using-vertx/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-graphql/pom.xml, projects/maven/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-health/pom.xml, projects/maven/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-jwt/pom.xml, projects/maven/microprofile-jwt/src/main/resources/META-INF/resources/index.html, src/main/resources/quarkus.xml
=> fix: Update the Quarkus runtime used by the plugin to version 2.1.0.Final

gradle.properties, src/main/resources/META-INF/plugin.xml
=> chore: Prepare 1.6.0

projects/gradle/config-properties/gradle.properties, projects/gradle/config-properties/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-context-propagation/gradle.properties, projects/gradle/microprofile-context-propagation/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-graphql/gradle.properties, projects/gradle/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-health/gradle.properties, projects/gradle/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-jwt/gradle.properties, projects/gradle/microprofile-jwt/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-lra/gradle.properties, projects/gradle/microprofile-lra/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-openapi/gradle.properties, projects/gradle/microprofile-openapi/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-reactive-messaging/gradle.properties, projects/gradle/microprofile-reactive-messaging/src/main/resources/META-INF/resources/index.html, projects/gradle/using-vertx/gradle.properties, projects/gradle/using-vertx/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-graphql/pom.xml, projects/maven/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-health/pom.xml, projects/maven/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-jwt/pom.xml, projects/maven/microprofile-jwt/src/main/resources/META-INF/resources/index.html, src/main/resources/quarkus.xml
=> fix: Update the Quarkus runtime used by the plugin to version 2.1.1.Final

projects/gradle/config-properties/gradle.properties, projects/gradle/config-properties/src/main/resources/META-INF/resources/index.html, projects/gradle/kotlin-resteasy/gradle.properties, projects/gradle/kotlin-resteasy/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-context-propagation/gradle.properties, projects/gradle/microprofile-context-propagation/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-graphql/gradle.properties, projects/gradle/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-health/gradle.properties, projects/gradle/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-jwt/gradle.properties, projects/gradle/microprofile-jwt/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-lra/gradle.properties, projects/gradle/microprofile-lra/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-openapi/gradle.properties, projects/gradle/microprofile-openapi/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-reactive-messaging/gradle.properties, projects/gradle/microprofile-reactive-messaging/src/main/resources/META-INF/resources/index.html, projects/gradle/using-vertx/gradle.properties, projects/gradle/using-vertx/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-graphql/pom.xml, projects/maven/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-health/pom.xml, projects/maven/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-jwt/pom.xml, projects/maven/microprofile-jwt/src/main/resources/META-INF/resources/index.html, src/main/resources/quarkus.xml
=> fix: Update the Quarkus runtime used by the plugin to version 2.1.2.Final

projects/gradle/config-properties/gradle.properties, projects/gradle/config-properties/src/main/resources/META-INF/resources/index.html, projects/gradle/kotlin-resteasy/gradle.properties, projects/gradle/kotlin-resteasy/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-context-propagation/gradle.properties, projects/gradle/microprofile-context-propagation/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-graphql/gradle.properties, projects/gradle/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-health/gradle.properties, projects/gradle/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-jwt/gradle.properties, projects/gradle/microprofile-jwt/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-lra/gradle.properties, projects/gradle/microprofile-lra/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-openapi/gradle.properties, projects/gradle/microprofile-openapi/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-reactive-messaging/gradle.properties, projects/gradle/microprofile-reactive-messaging/src/main/resources/META-INF/resources/index.html, projects/gradle/using-vertx/gradle.properties, projects/gradle/using-vertx/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-graphql/pom.xml, projects/maven/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-health/pom.xml, projects/maven/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-jwt/pom.xml, projects/maven/microprofile-jwt/src/main/resources/META-INF/resources/index.html, src/main/resources/quarkus.xml, src/test/java/com/redhat/devtools/intellij/quarkus/gradle/GradleMicroProfileGraphQLTest.java, src/test/java/com/redhat/devtools/intellij/quarkus/maven/MavenMicroProfileGraphQLTest.java
=> fix: Update the Quarkus runtime used by the plugin to version 2.2.0.CR1

projects/gradle/config-properties/gradle.properties, projects/gradle/config-properties/src/main/resources/META-INF/resources/index.html, projects/gradle/kotlin-resteasy/gradle.properties, projects/gradle/kotlin-resteasy/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-context-propagation/gradle.properties, projects/gradle/microprofile-context-propagation/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-graphql/gradle.properties, projects/gradle/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-health/gradle.properties, projects/gradle/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-jwt/gradle.properties, projects/gradle/microprofile-jwt/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-lra/gradle.properties, projects/gradle/microprofile-lra/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-openapi/gradle.properties, projects/gradle/microprofile-openapi/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-reactive-messaging/gradle.properties, projects/gradle/microprofile-reactive-messaging/src/main/resources/META-INF/resources/index.html, projects/gradle/using-vertx/gradle.properties, projects/gradle/using-vertx/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-graphql/pom.xml, projects/maven/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-health/pom.xml, projects/maven/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-jwt/pom.xml, projects/maven/microprofile-jwt/src/main/resources/META-INF/resources/index.html, src/main/resources/quarkus.xml
=> fix: Update the Quarkus runtime used by the plugin to version 2.2.1.Final

Jenkinsfile
=> chore: Jenkinsfile is broken

projects/gradle/config-properties/gradle.properties, projects/gradle/config-properties/src/main/resources/META-INF/resources/index.html, projects/gradle/kotlin-resteasy/gradle.properties, projects/gradle/kotlin-resteasy/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-context-propagation/gradle.properties, projects/gradle/microprofile-context-propagation/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-graphql/gradle.properties, projects/gradle/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-health/gradle.properties, projects/gradle/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-jwt/gradle.properties, projects/gradle/microprofile-jwt/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-lra/gradle.properties, projects/gradle/microprofile-lra/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-openapi/gradle.properties, projects/gradle/microprofile-openapi/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-reactive-messaging/gradle.properties, projects/gradle/microprofile-reactive-messaging/src/main/resources/META-INF/resources/index.html, projects/gradle/using-vertx/gradle.properties, projects/gradle/using-vertx/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-graphql/pom.xml, projects/maven/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-health/pom.xml, projects/maven/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-jwt/pom.xml, projects/maven/microprofile-jwt/src/main/resources/META-INF/resources/index.html, src/main/resources/quarkus.xml
=> fix: Update the Quarkus runtime used by the plugin to version 2.2.2.Final

gradle.properties, src/main/resources/META-INF/plugin.xml
=> chore: Prepare for 1.7.0

.github/workflows/release.yml
=> chore: Switch release workflow to Java 11

.github/workflows/changelog.yml
This should generate the changelog based on the input tag
=> chore: add workflow to manually generate changelog

projects/gradle/config-properties/gradle.properties, projects/gradle/config-properties/src/main/resources/META-INF/resources/index.html, projects/gradle/kotlin-resteasy/gradle.properties, projects/gradle/kotlin-resteasy/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-context-propagation/gradle.properties, projects/gradle/microprofile-context-propagation/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-graphql/gradle.properties, projects/gradle/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-health/gradle.properties, projects/gradle/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-jwt/gradle.properties, projects/gradle/microprofile-jwt/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-lra/gradle.properties, projects/gradle/microprofile-lra/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-openapi/gradle.properties, projects/gradle/microprofile-openapi/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-reactive-messaging/gradle.properties, projects/gradle/microprofile-reactive-messaging/src/main/resources/META-INF/resources/index.html, projects/gradle/using-vertx/gradle.properties, projects/gradle/using-vertx/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-graphql/pom.xml, projects/maven/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-health/pom.xml, projects/maven/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-jwt/pom.xml, projects/maven/microprofile-jwt/src/main/resources/META-INF/resources/index.html, src/main/resources/quarkus.xml
=> fix: Update the Quarkus runtime used by the plugin to version 2.2.3.Final

src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/utils/AnnotationUtils.java, src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/internal/faulttolerance/java/MicroProfileFaultToleranceDiagnosticsParticipant.java, src/main/resources/META-INF/plugin.xml, src/test/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/faulttolerance/GradleMicroProfileFaultToleranceJavaDiagnosticsTest.java, src/test/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/faulttolerance/MavenMicroProfileFaultToleranceJavaDiagnosticsTest.java
=> feat: Add Microprofile Fault Tolerance diagnostic provider

projects/gradle/microprofile-metrics/src/main/java/org/acme/IncorrectScope.java, projects/maven/microprofile-metrics/src/main/java/org/acme/IncorrectScope.java, src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/internal/metrics/MicroProfileMetricsConstants.java, src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/internal/metrics/java/MicroProfileMetricsDiagnosticsParticipant.java, src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/internal/metrics/java/MicroProfileMetricsErrorCode.java, src/main/resources/META-INF/plugin.xml, src/test/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/metrics/GradleJavaDiagnosticsMicroProfileMetricsTest.java, src/test/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/metrics/MavenJavaDiagnosticsMicroProfileMetricsTest.java
=> feat: Add MicroProfile Metrics diagnostic provider

build.gradle, src/main/java/com/redhat/devtools/intellij/quarkus/lsp/QuarkusServer.java
=> fix: IDE freezes under heavy load

build.gradle
=> chore: update Telemetry to 0.0.2.18

projects/gradle/config-properties/gradle.properties, projects/gradle/config-properties/src/main/resources/META-INF/resources/index.html, projects/gradle/kotlin-resteasy/gradle.properties, projects/gradle/kotlin-resteasy/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-context-propagation/gradle.properties, projects/gradle/microprofile-context-propagation/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-graphql/gradle.properties, projects/gradle/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-health/gradle.properties, projects/gradle/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-jwt/gradle.properties, projects/gradle/microprofile-jwt/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-lra/gradle.properties, projects/gradle/microprofile-lra/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-openapi/gradle.properties, projects/gradle/microprofile-openapi/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-reactive-messaging/gradle.properties, projects/gradle/microprofile-reactive-messaging/src/main/resources/META-INF/resources/index.html, projects/gradle/using-vertx/gradle.properties, projects/gradle/using-vertx/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-graphql/pom.xml, projects/maven/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-health/pom.xml, projects/maven/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-jwt/pom.xml, projects/maven/microprofile-jwt/src/main/resources/META-INF/resources/index.html, src/main/resources/quarkus.xml
=> fix: Update the Quarkus runtime used by the plugin to version 2.4.1.Final

projects/gradle/config-properties/gradle.properties, projects/gradle/config-properties/src/main/resources/META-INF/resources/index.html, projects/gradle/kotlin-resteasy/gradle.properties, projects/gradle/kotlin-resteasy/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-context-propagation/gradle.properties, projects/gradle/microprofile-context-propagation/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-graphql/gradle.properties, projects/gradle/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-health/gradle.properties, projects/gradle/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-jwt/gradle.properties, projects/gradle/microprofile-jwt/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-lra/gradle.properties, projects/gradle/microprofile-lra/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-openapi/gradle.properties, projects/gradle/microprofile-openapi/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-reactive-messaging/gradle.properties, projects/gradle/microprofile-reactive-messaging/src/main/resources/META-INF/resources/index.html, projects/gradle/using-vertx/gradle.properties, projects/gradle/using-vertx/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-graphql/pom.xml, projects/maven/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-health/pom.xml, projects/maven/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-jwt/pom.xml, projects/maven/microprofile-jwt/src/main/resources/META-INF/resources/index.html, src/main/resources/quarkus.xml
=> fix: Update the Quarkus runtime used by the plugin to version 2.5.0.Final

projects/gradle/config-properties/gradle.properties, projects/gradle/config-properties/src/main/resources/META-INF/resources/index.html, projects/gradle/kotlin-resteasy/gradle.properties, projects/gradle/kotlin-resteasy/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-context-propagation/gradle.properties, projects/gradle/microprofile-context-propagation/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-graphql/gradle.properties, projects/gradle/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-health/gradle.properties, projects/gradle/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-jwt/gradle.properties, projects/gradle/microprofile-jwt/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-lra/gradle.properties, projects/gradle/microprofile-lra/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-openapi/gradle.properties, projects/gradle/microprofile-openapi/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-reactive-messaging/gradle.properties, projects/gradle/microprofile-reactive-messaging/src/main/resources/META-INF/resources/index.html, projects/gradle/using-vertx/gradle.properties, projects/gradle/using-vertx/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-graphql/pom.xml, projects/maven/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-health/pom.xml, projects/maven/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-jwt/pom.xml, projects/maven/microprofile-jwt/src/main/resources/META-INF/resources/index.html, src/main/resources/quarkus.xml
=> fix: Update the Quarkus runtime used by the plugin to version 2.5.1.Final

gradle.properties, src/main/resources/META-INF/plugin.xml
=> chore(skip-release): Prepare for 1.9.0

build.gradle
=> fix: Update remote-robot to use proper Log4j

projects/gradle/config-properties/gradle.properties, projects/gradle/config-properties/src/main/resources/META-INF/resources/index.html, projects/gradle/kotlin-resteasy/gradle.properties, projects/gradle/kotlin-resteasy/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-context-propagation/gradle.properties, projects/gradle/microprofile-context-propagation/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-graphql/gradle.properties, projects/gradle/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-health/gradle.properties, projects/gradle/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-jwt/gradle.properties, projects/gradle/microprofile-jwt/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-lra/gradle.properties, projects/gradle/microprofile-lra/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-openapi/gradle.properties, projects/gradle/microprofile-openapi/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-reactive-messaging/gradle.properties, projects/gradle/microprofile-reactive-messaging/src/main/resources/META-INF/resources/index.html, projects/gradle/using-vertx/gradle.properties, projects/gradle/using-vertx/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-graphql/pom.xml, projects/maven/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-health/pom.xml, projects/maven/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-jwt/pom.xml, projects/maven/microprofile-jwt/src/main/resources/META-INF/resources/index.html, src/main/resources/quarkus.xml
=> fix: Update the Quarkus runtime used by the plugin to version 2.6.0.Final

projects/gradle/config-properties/gradle.properties, projects/gradle/config-properties/src/main/resources/META-INF/resources/index.html, projects/gradle/kotlin-resteasy/gradle.properties, projects/gradle/kotlin-resteasy/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-context-propagation/gradle.properties, projects/gradle/microprofile-context-propagation/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-graphql/gradle.properties, projects/gradle/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-health/gradle.properties, projects/gradle/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-jwt/gradle.properties, projects/gradle/microprofile-jwt/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-lra/gradle.properties, projects/gradle/microprofile-lra/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-openapi/gradle.properties, projects/gradle/microprofile-openapi/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-reactive-messaging/gradle.properties, projects/gradle/microprofile-reactive-messaging/src/main/resources/META-INF/resources/index.html, projects/gradle/using-vertx/gradle.properties, projects/gradle/using-vertx/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-graphql/pom.xml, projects/maven/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-health/pom.xml, projects/maven/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-jwt/pom.xml, projects/maven/microprofile-jwt/src/main/resources/META-INF/resources/index.html, src/main/resources/quarkus.xml
=> fix: Update the Quarkus runtime used by the plugin to version 2.6.1.Final

projects/gradle/config-properties/gradle.properties, projects/gradle/config-properties/src/main/resources/META-INF/resources/index.html, projects/gradle/kotlin-resteasy/gradle.properties, projects/gradle/kotlin-resteasy/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-context-propagation/gradle.properties, projects/gradle/microprofile-context-propagation/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-graphql/gradle.properties, projects/gradle/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-health/gradle.properties, projects/gradle/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-jwt/gradle.properties, projects/gradle/microprofile-jwt/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-lra/gradle.properties, projects/gradle/microprofile-lra/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-openapi/gradle.properties, projects/gradle/microprofile-openapi/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-reactive-messaging/gradle.properties, projects/gradle/microprofile-reactive-messaging/src/main/resources/META-INF/resources/index.html, projects/gradle/using-vertx/gradle.properties, projects/gradle/using-vertx/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-graphql/pom.xml, projects/maven/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-health/pom.xml, projects/maven/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-jwt/pom.xml, projects/maven/microprofile-jwt/src/main/resources/META-INF/resources/index.html, src/main/resources/quarkus.xml
=> fix: Update the Quarkus runtime used by the plugin to version 2.7.0.Final

src/it/java/org/jboss/tools/intellij/quarkus/utils/GlobalUtils.java, src/it/java/org/jboss/tools/intellij/quarkus/utils/QuarkusUtils.java
=> fix: increase timeout for background jobs

projects/gradle/config-properties/gradle.properties, projects/gradle/config-properties/src/main/resources/META-INF/resources/index.html, projects/gradle/kotlin-resteasy/gradle.properties, projects/gradle/kotlin-resteasy/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-context-propagation/gradle.properties, projects/gradle/microprofile-context-propagation/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-graphql/gradle.properties, projects/gradle/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-health/gradle.properties, projects/gradle/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-jwt/gradle.properties, projects/gradle/microprofile-jwt/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-lra/gradle.properties, projects/gradle/microprofile-lra/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-openapi/gradle.properties, projects/gradle/microprofile-openapi/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-reactive-messaging/gradle.properties, projects/gradle/microprofile-reactive-messaging/src/main/resources/META-INF/resources/index.html, projects/gradle/using-vertx/gradle.properties, projects/gradle/using-vertx/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-graphql/pom.xml, projects/maven/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-health/pom.xml, projects/maven/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-jwt/pom.xml, projects/maven/microprofile-jwt/src/main/resources/META-INF/resources/index.html, src/main/resources/quarkus.xml
=> fix: Update the Quarkus runtime used by the plugin to version 2.7.1.Final

.github/workflows/ci.yml, src/it/java/org/jboss/tools/intellij/quarkus/utils/BuildUtils.java
=> fix: add synchronization of Gradle window for integration tests

src/main/java/com/redhat/devtools/intellij/quarkus/gradle/AbstractGradleToolDelegate.java, src/main/java/com/redhat/devtools/intellij/quarkus/gradle/GradleGroovyToolDelegate.java, src/main/java/com/redhat/devtools/intellij/quarkus/gradle/GradleKotlinToolDelegate.java, src/main/java/com/redhat/devtools/intellij/quarkus/maven/MavenToolDelegate.java, src/main/java/com/redhat/devtools/intellij/quarkus/maven/QuarkusMavenLibraryImporter.java, src/test/java/com/redhat/devtools/intellij/quarkus/completion/GradleQuarkusLibraryTest.java, src/test/java/com/redhat/devtools/intellij/quarkus/completion/MavenQuarkusLibraryTest.java
=> fix: dependencies duplicated in Quarkus library

src/main/java/com/redhat/devtools/intellij/quarkus/TelemetryService.java, src/main/java/com/redhat/devtools/intellij/quarkus/gradle/AbstractGradleToolDelegate.java, src/main/java/com/redhat/devtools/intellij/quarkus/maven/MavenToolDelegate.java, src/main/java/com/redhat/devtools/intellij/quarkus/run/QuarkusRunConfiguration.java, src/main/java/com/redhat/devtools/intellij/quarkus/run/QuarkusRunConfigurationFactory.java, src/main/java/com/redhat/devtools/intellij/quarkus/run/QuarkusRunConfigurationOptions.java, src/main/java/com/redhat/devtools/intellij/quarkus/run/QuarkusRunConfigurationType.java, src/main/java/com/redhat/devtools/intellij/quarkus/run/QuarkusRunSettingsEditor.form, src/main/java/com/redhat/devtools/intellij/quarkus/run/QuarkusRunSettingsEditor.java, src/main/java/com/redhat/devtools/intellij/quarkus/tool/ToolDelegate.java, src/main/resources/META-INF/plugin.xml, src/test/java/com/redhat/devtools/intellij/quarkus/run/MavenRunConfigurationTest.java
=> feat: add Quarkus run configurations

src/main/java/com/redhat/devtools/intellij/quarkus/gradle/AbstractGradleToolDelegate.java, src/main/java/com/redhat/devtools/intellij/quarkus/maven/MavenToolDelegate.java, src/main/java/com/redhat/devtools/intellij/quarkus/run/QuarkusRunConfiguration.java
=> fix: launch remote debugger for Quarkus run configuration in debug mode

src/main/java/com/redhat/devtools/intellij/quarkus/QuarkusConstants.java, src/main/java/com/redhat/devtools/intellij/quarkus/QuarkusModuleUtil.java, src/main/java/com/redhat/devtools/intellij/quarkus/search/QuarkusModuleComponent.java
=> fix: add version to Quarkus library

src/main/java/com/redhat/devtools/intellij/quarkus/QuarkusModuleUtil.java, src/main/java/com/redhat/devtools/intellij/quarkus/gradle/AbstractGradleToolDelegate.java, src/main/java/com/redhat/devtools/intellij/quarkus/gradle/GradleGroovyToolDelegate.java, src/main/java/com/redhat/devtools/intellij/quarkus/gradle/GradleKotlinToolDelegate.java
=> fix: NPE for multi module Gradle projects

src/main/java/com/redhat/devtools/intellij/quarkus/lsp4ij/DocumentContentSynchronizer.java
=> chore: add more document info in document synchronizer

projects/gradle/config-properties/gradle.properties, projects/gradle/config-properties/src/main/resources/META-INF/resources/index.html, projects/gradle/kotlin-resteasy/gradle.properties, projects/gradle/kotlin-resteasy/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-context-propagation/gradle.properties, projects/gradle/microprofile-context-propagation/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-graphql/gradle.properties, projects/gradle/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-health/gradle.properties, projects/gradle/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-jwt/gradle.properties, projects/gradle/microprofile-jwt/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-lra/gradle.properties, projects/gradle/microprofile-lra/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-openapi/gradle.properties, projects/gradle/microprofile-openapi/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-reactive-messaging/gradle.properties, projects/gradle/microprofile-reactive-messaging/src/main/resources/META-INF/resources/index.html, projects/gradle/using-vertx/gradle.properties, projects/gradle/using-vertx/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-graphql/pom.xml, projects/maven/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-health/pom.xml, projects/maven/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-jwt/pom.xml, projects/maven/microprofile-jwt/src/main/resources/META-INF/resources/index.html, src/main/resources/quarkus.xml
=> fix: Update the Quarkus runtime used by the plugin to version 2.7.2.Final

projects/gradle/config-properties/gradle.properties, projects/gradle/config-properties/src/main/resources/META-INF/resources/index.html, projects/gradle/kotlin-resteasy/gradle.properties, projects/gradle/kotlin-resteasy/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-context-propagation/gradle.properties, projects/gradle/microprofile-context-propagation/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-graphql/gradle.properties, projects/gradle/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-health/gradle.properties, projects/gradle/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-jwt/gradle.properties, projects/gradle/microprofile-jwt/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-lra/gradle.properties, projects/gradle/microprofile-lra/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-openapi/gradle.properties, projects/gradle/microprofile-openapi/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-reactive-messaging/gradle.properties, projects/gradle/microprofile-reactive-messaging/src/main/resources/META-INF/resources/index.html, projects/gradle/using-vertx/gradle.properties, projects/gradle/using-vertx/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-graphql/pom.xml, projects/maven/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-health/pom.xml, projects/maven/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-jwt/pom.xml, projects/maven/microprofile-jwt/src/main/resources/META-INF/resources/index.html, src/main/resources/quarkus.xml
=> fix: Update the Quarkus runtime used by the plugin to version 2.7.3.Final

build.gradle, gradle.properties, src/test/java/com/redhat/devtools/intellij/quarkus/QuarkusModuleUtilTest.java
=> fix: update dependencies versions

gradle.properties, projects/gradle/config-properties/gradle.properties, projects/gradle/config-properties/src/main/resources/META-INF/resources/index.html, projects/gradle/kotlin-resteasy/gradle.properties, projects/gradle/kotlin-resteasy/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-context-propagation/gradle.properties, projects/gradle/microprofile-context-propagation/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-graphql/gradle.properties, projects/gradle/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-health/gradle.properties, projects/gradle/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-jwt/gradle.properties, projects/gradle/microprofile-jwt/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-lra/gradle.properties, projects/gradle/microprofile-lra/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-openapi/gradle.properties, projects/gradle/microprofile-openapi/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-reactive-messaging/gradle.properties, projects/gradle/microprofile-reactive-messaging/src/main/resources/META-INF/resources/index.html, projects/gradle/using-vertx/gradle.properties, projects/gradle/using-vertx/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-graphql/pom.xml, projects/maven/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-health/pom.xml, projects/maven/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-jwt/pom.xml, projects/maven/microprofile-jwt/src/main/resources/META-INF/resources/index.html, src/main/resources/quarkus.xml
=> fix: Update the Quarkus runtime used by the plugin to version 2.7.4.Final

gradle.properties, projects/gradle/config-properties/gradle.properties, projects/gradle/config-properties/src/main/resources/META-INF/resources/index.html, projects/gradle/kotlin-resteasy/gradle.properties, projects/gradle/kotlin-resteasy/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-context-propagation/gradle.properties, projects/gradle/microprofile-context-propagation/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-graphql/gradle.properties, projects/gradle/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-health/gradle.properties, projects/gradle/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-jwt/gradle.properties, projects/gradle/microprofile-jwt/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-lra/gradle.properties, projects/gradle/microprofile-lra/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-openapi/gradle.properties, projects/gradle/microprofile-openapi/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-reactive-messaging/gradle.properties, projects/gradle/microprofile-reactive-messaging/src/main/resources/META-INF/resources/index.html, projects/gradle/using-vertx/gradle.properties, projects/gradle/using-vertx/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-graphql/pom.xml, projects/maven/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-health/pom.xml, projects/maven/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-jwt/pom.xml, projects/maven/microprofile-jwt/src/main/resources/META-INF/resources/index.html, src/main/resources/quarkus.xml
=> fix: Update the Quarkus runtime used by the plugin to version 2.8.0.CR1

Jenkinsfile, build.gradle
=> chore(build): fix rsync issues

gradle.properties, projects/gradle/config-properties/gradle.properties, projects/gradle/config-properties/src/main/resources/META-INF/resources/index.html, projects/gradle/kotlin-resteasy/gradle.properties, projects/gradle/kotlin-resteasy/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-context-propagation/gradle.properties, projects/gradle/microprofile-context-propagation/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-graphql/gradle.properties, projects/gradle/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-health/gradle.properties, projects/gradle/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-jwt/gradle.properties, projects/gradle/microprofile-jwt/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-lra/gradle.properties, projects/gradle/microprofile-lra/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-openapi/gradle.properties, projects/gradle/microprofile-openapi/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-reactive-messaging/gradle.properties, projects/gradle/microprofile-reactive-messaging/src/main/resources/META-INF/resources/index.html, projects/gradle/using-vertx/gradle.properties, projects/gradle/using-vertx/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-graphql/pom.xml, projects/maven/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-health/pom.xml, projects/maven/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-jwt/pom.xml, projects/maven/microprofile-jwt/src/main/resources/META-INF/resources/index.html, src/main/resources/quarkus.xml
=> fix: Update the Quarkus runtime used by the plugin to version 2.8.0.Final

.github/workflows/IJ.yml, build.gradle
=> build: Add IntelliJ 2022.1

gradle.properties, projects/gradle/config-properties/gradle.properties, projects/gradle/config-properties/src/main/resources/META-INF/resources/index.html, projects/gradle/kotlin-resteasy/gradle.properties, projects/gradle/kotlin-resteasy/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-context-propagation/gradle.properties, projects/gradle/microprofile-context-propagation/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-graphql/gradle.properties, projects/gradle/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-health/gradle.properties, projects/gradle/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-jwt/gradle.properties, projects/gradle/microprofile-jwt/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-lra/gradle.properties, projects/gradle/microprofile-lra/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-openapi/gradle.properties, projects/gradle/microprofile-openapi/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-reactive-messaging/gradle.properties, projects/gradle/microprofile-reactive-messaging/src/main/resources/META-INF/resources/index.html, projects/gradle/using-vertx/gradle.properties, projects/gradle/using-vertx/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-graphql/pom.xml, projects/maven/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-health/pom.xml, projects/maven/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-jwt/pom.xml, projects/maven/microprofile-jwt/src/main/resources/META-INF/resources/index.html, src/main/resources/quarkus.xml
=> fix: Update the Quarkus runtime used by the plugin to version 2.8.1.Final

gradle.properties, projects/gradle/config-properties/gradle.properties, projects/gradle/config-properties/src/main/resources/META-INF/resources/index.html, projects/gradle/kotlin-resteasy/gradle.properties, projects/gradle/kotlin-resteasy/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-context-propagation/gradle.properties, projects/gradle/microprofile-context-propagation/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-graphql/gradle.properties, projects/gradle/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-health/gradle.properties, projects/gradle/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-jwt/gradle.properties, projects/gradle/microprofile-jwt/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-lra/gradle.properties, projects/gradle/microprofile-lra/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-openapi/gradle.properties, projects/gradle/microprofile-openapi/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-reactive-messaging/gradle.properties, projects/gradle/microprofile-reactive-messaging/src/main/resources/META-INF/resources/index.html, projects/gradle/using-vertx/gradle.properties, projects/gradle/using-vertx/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-graphql/pom.xml, projects/maven/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-health/pom.xml, projects/maven/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-jwt/pom.xml, projects/maven/microprofile-jwt/src/main/resources/META-INF/resources/index.html, src/main/resources/quarkus.xml
=> fix: Update the Quarkus runtime used by the plugin to version 2.8.2.Final

gradle.properties, projects/gradle/config-properties/gradle.properties, projects/gradle/config-properties/src/main/resources/META-INF/resources/index.html, projects/gradle/kotlin-resteasy/gradle.properties, projects/gradle/kotlin-resteasy/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-context-propagation/gradle.properties, projects/gradle/microprofile-context-propagation/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-graphql/gradle.properties, projects/gradle/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-health/gradle.properties, projects/gradle/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-jwt/gradle.properties, projects/gradle/microprofile-jwt/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-lra/gradle.properties, projects/gradle/microprofile-lra/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-openapi/gradle.properties, projects/gradle/microprofile-openapi/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-reactive-messaging/gradle.properties, projects/gradle/microprofile-reactive-messaging/src/main/resources/META-INF/resources/index.html, projects/gradle/using-vertx/gradle.properties, projects/gradle/using-vertx/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-graphql/pom.xml, projects/maven/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-health/pom.xml, projects/maven/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-jwt/pom.xml, projects/maven/microprofile-jwt/src/main/resources/META-INF/resources/index.html, src/main/resources/quarkus.xml
=> fix: Update the Quarkus runtime used by the plugin to version 2.9.0.Final

src/main/java/com/redhat/devtools/intellij/quarkus/lsp4ij/operations/hover/LSPTextHover.java
=> fix: open hover links in IDE

src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/project/AbstractConfigSource.java, src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/project/PsiMicroProfileProject.java, src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/internal/core/providers/MicroProfileConfigSourceProvider.java, src/main/java/com/redhat/devtools/intellij/quarkus/psi/internal/providers/QuarkusConfigSourceProvider.java, src/test/java/com/redhat/devtools/intellij/MavenModuleImportingTestCase.java, src/test/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/MicroProfileAssert.java, src/test/java/com/redhat/microprofile/psi/quarkus/config/QuarkusConfigJavaHoverTest.java
=> fix: use source folders for the ConfigSource framework

build.gradle, src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/PropertiesManagerForJava.java
=> fix: @ConfigProperty diagnostics may be desynchronized

gradle.properties, projects/gradle/config-properties/gradle.properties, projects/gradle/config-properties/src/main/resources/META-INF/resources/index.html, projects/gradle/kotlin-resteasy/gradle.properties, projects/gradle/kotlin-resteasy/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-context-propagation/gradle.properties, projects/gradle/microprofile-context-propagation/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-graphql/gradle.properties, projects/gradle/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-health/gradle.properties, projects/gradle/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-jwt/gradle.properties, projects/gradle/microprofile-jwt/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-lra/gradle.properties, projects/gradle/microprofile-lra/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-openapi/gradle.properties, projects/gradle/microprofile-openapi/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-reactive-messaging/gradle.properties, projects/gradle/microprofile-reactive-messaging/src/main/resources/META-INF/resources/index.html, projects/gradle/using-vertx/gradle.properties, projects/gradle/using-vertx/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-graphql/pom.xml, projects/maven/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-health/pom.xml, projects/maven/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-jwt/pom.xml, projects/maven/microprofile-jwt/src/main/resources/META-INF/resources/index.html, src/main/resources/quarkus.xml
=> fix: Update the Quarkus runtime used by the plugin to version 2.9.1.Final

src/main/java/com/redhat/devtools/intellij/quarkus/lsp4ij/operations/diagnostics/LSPLocalInspectionTool.java
=> fix: error reported for empty PSI elements

gradle.properties, projects/gradle/config-properties/gradle.properties, projects/gradle/config-properties/src/main/resources/META-INF/resources/index.html, projects/gradle/kotlin-resteasy/gradle.properties, projects/gradle/kotlin-resteasy/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-context-propagation/gradle.properties, projects/gradle/microprofile-context-propagation/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-graphql/gradle.properties, projects/gradle/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-health/gradle.properties, projects/gradle/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-jwt/gradle.properties, projects/gradle/microprofile-jwt/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-lra/gradle.properties, projects/gradle/microprofile-lra/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-openapi/gradle.properties, projects/gradle/microprofile-openapi/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-reactive-messaging/gradle.properties, projects/gradle/microprofile-reactive-messaging/src/main/resources/META-INF/resources/index.html, projects/gradle/using-vertx/gradle.properties, projects/gradle/using-vertx/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-graphql/pom.xml, projects/maven/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-health/pom.xml, projects/maven/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-jwt/pom.xml, projects/maven/microprofile-jwt/src/main/resources/META-INF/resources/index.html, src/main/resources/quarkus.xml
=> fix: Update the Quarkus runtime used by the plugin to version 2.9.2.Final

build.gradle, src/main/java/com/redhat/devtools/intellij/quarkus/javadoc/HtmlToPlainText.java, src/main/java/com/redhat/devtools/intellij/quarkus/javadoc/JavaDoc2MarkdownConverter.java
=> fix: Upgrade to jsoup 1.14.2

src/main/java/com/redhat/devtools/intellij/qute/lsp/QuteLanguageClient.java, src/main/java/com/redhat/devtools/intellij/qute/psi/internal/java/AbstractQuteTemplateLinkCollector.java
=> fix: NPE when processing template links

src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/java/validators/JavaASTValidator.java, src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/java/validators/JavaASTValidatorExtensionPointBean.java, src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/internal/core/java/validators/JavaASTValidatorRegistry.java, src/main/resources/META-INF/plugin.xml
=> fix: Race condition in JavaASTValidator framework

src/main/resources/META-INF/lsp.xml
=> fix: Conflit with Quarkus plugin from JetBrains

src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/java/validators/annotations/AnnotationValidator.java
=> fix: Error while visiting node

CONTRIBUTING.md, DCO
=> fix: Add DCO documentation

src/main/java/com/redhat/devtools/intellij/quarkus/lsp4ij/LSPIJUtils.java
=> fix: Read access is allowed from inside read-action

gradle.properties, projects/gradle/config-properties/gradle.properties, projects/gradle/config-properties/src/main/resources/META-INF/resources/index.html, projects/gradle/config-quickstart/gradle.properties, projects/gradle/kotlin-resteasy/gradle.properties, projects/gradle/kotlin-resteasy/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-context-propagation/gradle.properties, projects/gradle/microprofile-context-propagation/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-graphql/gradle.properties, projects/gradle/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-health/gradle.properties, projects/gradle/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-jwt/gradle.properties, projects/gradle/microprofile-jwt/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-lra/gradle.properties, projects/gradle/microprofile-lra/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-openapi/gradle.properties, projects/gradle/microprofile-openapi/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-reactive-messaging/gradle.properties, projects/gradle/microprofile-reactive-messaging/src/main/resources/META-INF/resources/index.html, projects/gradle/using-vertx/gradle.properties, projects/gradle/using-vertx/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-graphql/pom.xml, projects/maven/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-health/pom.xml, projects/maven/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-jwt/pom.xml, projects/maven/microprofile-jwt/src/main/resources/META-INF/resources/index.html, src/main/resources/quarkus.xml
=> fix: Update the Quarkus runtime used by the plugin to version 2.10.1.Final

gradle.properties, projects/gradle/config-properties/gradle.properties, projects/gradle/config-properties/src/main/resources/META-INF/resources/index.html, projects/gradle/config-quickstart/gradle.properties, projects/gradle/kotlin-resteasy/gradle.properties, projects/gradle/kotlin-resteasy/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-context-propagation/gradle.properties, projects/gradle/microprofile-context-propagation/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-graphql/gradle.properties, projects/gradle/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-health/gradle.properties, projects/gradle/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-jwt/gradle.properties, projects/gradle/microprofile-jwt/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-lra/gradle.properties, projects/gradle/microprofile-lra/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-openapi/gradle.properties, projects/gradle/microprofile-openapi/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-reactive-messaging/gradle.properties, projects/gradle/microprofile-reactive-messaging/src/main/resources/META-INF/resources/index.html, projects/gradle/using-vertx/gradle.properties, projects/gradle/using-vertx/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-graphql/pom.xml, projects/maven/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-health/pom.xml, projects/maven/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-jwt/pom.xml, projects/maven/microprofile-jwt/src/main/resources/META-INF/resources/index.html, src/main/resources/quarkus.xml
=> fix: Update the Quarkus runtime used by the plugin to version 2.10.2.Final

src/it/java/org/jboss/tools/intellij/quarkus/tests/BasicTest.java, src/main/java/com/redhat/devtools/intellij/quarkus/module/QuarkusExtensionsStep.java
=> feat: Add extensions filter in Quarkus wizard

src/main/java/com/redhat/devtools/intellij/quarkus/lsp4ij/operations/codelens/LSPInlayProvider.java
=> feat: Group CodeLens elements on a single line

build.gradle
=> chore: update Telemetry to 0.0.3.33

src/main/java/com/redhat/devtools/intellij/quarkus/QuarkusConstants.java, src/main/java/com/redhat/devtools/intellij/quarkus/run/QuarkusDevAction.java, src/main/java/com/redhat/devtools/intellij/quarkus/run/QuarkusDevActionGroup.java, src/main/java/com/redhat/devtools/intellij/quarkus/run/QuarkusOpenAppInBrowserAction.java, src/main/java/com/redhat/devtools/intellij/quarkus/run/QuarkusOpenDevUIAction.java, src/main/java/com/redhat/devtools/intellij/quarkus/run/QuarkusRunConfiguration.java, src/main/java/com/redhat/devtools/intellij/quarkus/run/QuarkusRunConsolePostProcessor.java, src/main/java/com/redhat/devtools/intellij/quarkus/run/QuarkusRunContext.java, src/main/resources/META-INF/plugin.xml, src/test/java/com/redhat/devtools/intellij/quarkus/run/QuarkusRunContextTest.java
=> feat: Add button to browse the Dev UI

gradle.properties, projects/gradle/config-properties/gradle.properties, projects/gradle/config-properties/src/main/resources/META-INF/resources/index.html, projects/gradle/config-quickstart/gradle.properties, projects/gradle/kotlin-resteasy/gradle.properties, projects/gradle/kotlin-resteasy/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-context-propagation/gradle.properties, projects/gradle/microprofile-context-propagation/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-graphql/gradle.properties, projects/gradle/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-health/gradle.properties, projects/gradle/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-jwt/gradle.properties, projects/gradle/microprofile-jwt/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-lra/gradle.properties, projects/gradle/microprofile-lra/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-openapi/gradle.properties, projects/gradle/microprofile-openapi/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-reactive-messaging/gradle.properties, projects/gradle/microprofile-reactive-messaging/src/main/resources/META-INF/resources/index.html, projects/gradle/using-vertx/gradle.properties, projects/gradle/using-vertx/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-graphql/pom.xml, projects/maven/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-health/pom.xml, projects/maven/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-jwt/pom.xml, projects/maven/microprofile-jwt/src/main/resources/META-INF/resources/index.html, src/main/resources/quarkus.xml
=> fix: Update the Quarkus runtime used by the plugin to version 2.11.1.Final

src/main/java/com/redhat/devtools/intellij/quarkus/QuarkusConstants.java, src/main/java/com/redhat/devtools/intellij/quarkus/module/QuarkusExtension.java, src/main/java/com/redhat/devtools/intellij/quarkus/module/QuarkusExtensionsModel.java, src/main/java/com/redhat/devtools/intellij/quarkus/module/QuarkusExtensionsStep.java, src/main/java/com/redhat/devtools/intellij/quarkus/module/QuarkusModelRegistry.java, src/main/resources/images/platform-icon.svg, src/main/resources/images/platform-icon_dark.svg
=> fix: Extensions from the platform should have an indicator

gradle.properties, projects/gradle/config-properties/gradle.properties, projects/gradle/config-properties/src/main/resources/META-INF/resources/index.html, projects/gradle/config-quickstart/gradle.properties, projects/gradle/kotlin-resteasy/gradle.properties, projects/gradle/kotlin-resteasy/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-context-propagation/gradle.properties, projects/gradle/microprofile-context-propagation/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-graphql/gradle.properties, projects/gradle/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-health/gradle.properties, projects/gradle/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-jwt/gradle.properties, projects/gradle/microprofile-jwt/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-lra/gradle.properties, projects/gradle/microprofile-lra/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-openapi/gradle.properties, projects/gradle/microprofile-openapi/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-reactive-messaging/gradle.properties, projects/gradle/microprofile-reactive-messaging/src/main/resources/META-INF/resources/index.html, projects/gradle/using-vertx/gradle.properties, projects/gradle/using-vertx/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-graphql/pom.xml, projects/maven/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-health/pom.xml, projects/maven/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-jwt/pom.xml, projects/maven/microprofile-jwt/src/main/resources/META-INF/resources/index.html, src/main/resources/quarkus.xml
=> fix: Update the Quarkus runtime used by the plugin to version 2.11.2.Final

src/main/java/com/redhat/devtools/intellij/quarkus/lsp4ij/DocumentContentSynchronizer.java, src/main/java/com/redhat/devtools/intellij/quarkus/lsp4ij/operations/codelens/LSPInlayProvider.java
=> fix: Content assist may eat existing text

build.gradle
=> test: Update the common UI test library to version 0.2.0

src/main/java/com/redhat/devtools/intellij/quarkus/gradle/AbstractGradleToolDelegate.java
=> fix: Synchronous refresh under read lock causes IDE error

src/main/java/com/redhat/devtools/intellij/quarkus/gradle/AbstractGradleToolDelegate.java
=> fix: Quarkus library not generated for Gradle based projects

build.gradle, src/main/java/com/redhat/devtools/intellij/quarkus/lsp4ij/LSPIJUtils.java, src/main/java/com/redhat/devtools/intellij/quarkus/lsp4ij/LanguageServerWrapper.java
=> chore: bump LSP4J from 0.14.0 to 0.15.0

build.gradle
=> fix: Use Jackson provided by IntelliJ

gradle.properties, projects/gradle/config-properties/gradle.properties, projects/gradle/config-properties/src/main/resources/META-INF/resources/index.html, projects/gradle/config-quickstart/gradle.properties, projects/gradle/kotlin-resteasy/gradle.properties, projects/gradle/kotlin-resteasy/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-context-propagation/gradle.properties, projects/gradle/microprofile-context-propagation/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-graphql/gradle.properties, projects/gradle/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-health/gradle.properties, projects/gradle/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-jwt/gradle.properties, projects/gradle/microprofile-jwt/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-lra/gradle.properties, projects/gradle/microprofile-lra/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-openapi/gradle.properties, projects/gradle/microprofile-openapi/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-reactive-messaging/gradle.properties, projects/gradle/microprofile-reactive-messaging/src/main/resources/META-INF/resources/index.html, projects/gradle/using-vertx/gradle.properties, projects/gradle/using-vertx/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-graphql/pom.xml, projects/maven/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-health/pom.xml, projects/maven/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-jwt/pom.xml, projects/maven/microprofile-jwt/src/main/resources/META-INF/resources/index.html, src/main/resources/quarkus.xml
=> fix: Update the Quarkus runtime used by the plugin to version 2.12.0.CR1

gradle.properties, projects/gradle/config-properties/gradle.properties, projects/gradle/config-properties/src/main/resources/META-INF/resources/index.html, projects/gradle/config-quickstart/gradle.properties, projects/gradle/kotlin-resteasy/gradle.properties, projects/gradle/kotlin-resteasy/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-context-propagation/gradle.properties, projects/gradle/microprofile-context-propagation/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-graphql/gradle.properties, projects/gradle/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-health/gradle.properties, projects/gradle/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-jwt/gradle.properties, projects/gradle/microprofile-jwt/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-lra/gradle.properties, projects/gradle/microprofile-lra/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-openapi/gradle.properties, projects/gradle/microprofile-openapi/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-reactive-messaging/gradle.properties, projects/gradle/microprofile-reactive-messaging/src/main/resources/META-INF/resources/index.html, projects/gradle/using-vertx/gradle.properties, projects/gradle/using-vertx/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-graphql/pom.xml, projects/maven/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-health/pom.xml, projects/maven/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-jwt/pom.xml, projects/maven/microprofile-jwt/src/main/resources/META-INF/resources/index.html, src/main/resources/quarkus.xml
=> fix: Update the Quarkus runtime used by the plugin to version 2.12.0.Final

src/main/java/com/redhat/devtools/intellij/quarkus/run/QuarkusRunContext.java
=> fix: NPE when retrieving the QuarkusRunContext

gradle.properties, projects/gradle/config-properties/gradle.properties, projects/gradle/config-properties/src/main/resources/META-INF/resources/index.html, projects/gradle/config-quickstart/gradle.properties, projects/gradle/kotlin-resteasy/gradle.properties, projects/gradle/kotlin-resteasy/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-context-propagation/gradle.properties, projects/gradle/microprofile-context-propagation/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-graphql/gradle.properties, projects/gradle/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-health/gradle.properties, projects/gradle/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-jwt/gradle.properties, projects/gradle/microprofile-jwt/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-lra/gradle.properties, projects/gradle/microprofile-lra/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-openapi/gradle.properties, projects/gradle/microprofile-openapi/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-reactive-messaging/gradle.properties, projects/gradle/microprofile-reactive-messaging/src/main/resources/META-INF/resources/index.html, projects/gradle/using-vertx/gradle.properties, projects/gradle/using-vertx/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-graphql/pom.xml, projects/maven/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-health/pom.xml, projects/maven/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-jwt/pom.xml, projects/maven/microprofile-jwt/src/main/resources/META-INF/resources/index.html, src/main/resources/quarkus.xml
=> fix: Update the Quarkus runtime used by the plugin to version 2.12.1.Final

src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/command/MicroprofileOpenURIAction.java, src/main/java/com/redhat/devtools/intellij/quarkus/lsp4ij/AbstractLSPInlayProvider.java, src/main/java/com/redhat/devtools/intellij/quarkus/lsp4ij/LanguageServerWrapper.java, src/main/java/com/redhat/devtools/intellij/quarkus/lsp4ij/operations/codelens/LSPCodelensInlayProvider.java, src/main/java/com/redhat/devtools/intellij/quarkus/lsp4ij/operations/inlayhint/LSPInlayHintInlayProvider.java, src/main/java/com/redhat/devtools/intellij/qute/psi/core/command/QuteAction.java, src/main/java/com/redhat/devtools/intellij/qute/psi/core/command/QuteGenerateTemplateAction.java, src/main/java/com/redhat/devtools/intellij/qute/psi/core/command/QuteJavaDefinitionAction.java, src/main/resources/META-INF/lsp.xml
=> feat: Support for textDocument/inlayHint

src/main/java/com/redhat/devtools/intellij/quarkus/lsp4ij/operations/highlight/LSPHighlightUsagesHandler.java, src/main/java/com/redhat/devtools/intellij/quarkus/lsp4ij/operations/highlight/LSPHighlightUsagesHandlerFactory.java, src/main/resources/META-INF/lsp.xml
=> feat: Support for textDocument/documentHighlight

build.gradle, src/main/java/com/redhat/devtools/intellij/quarkus/lsp4ij/AbstractLSPInlayProvider.java, src/main/java/com/redhat/devtools/intellij/quarkus/lsp4ij/operations/codelens/LSPCodelensInlayProvider.java, src/main/java/com/redhat/devtools/intellij/quarkus/lsp4ij/operations/inlayhint/LSPInlayHintInlayProvider.java
=> feat: Support clickable InlayHints

gradle.properties, projects/gradle/config-properties/gradle.properties, projects/gradle/config-properties/src/main/resources/META-INF/resources/index.html, projects/gradle/config-quickstart/gradle.properties, projects/gradle/kotlin-resteasy/gradle.properties, projects/gradle/kotlin-resteasy/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-context-propagation/gradle.properties, projects/gradle/microprofile-context-propagation/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-graphql/gradle.properties, projects/gradle/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-health/gradle.properties, projects/gradle/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-jwt/gradle.properties, projects/gradle/microprofile-jwt/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-lra/gradle.properties, projects/gradle/microprofile-lra/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-openapi/gradle.properties, projects/gradle/microprofile-openapi/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-reactive-messaging/gradle.properties, projects/gradle/microprofile-reactive-messaging/src/main/resources/META-INF/resources/index.html, projects/gradle/using-vertx/gradle.properties, projects/gradle/using-vertx/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-graphql/pom.xml, projects/maven/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-health/pom.xml, projects/maven/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-jwt/pom.xml, projects/maven/microprofile-jwt/src/main/resources/META-INF/resources/index.html, src/main/resources/quarkus.xml
=> fix: Update the Quarkus runtime used by the plugin to version 2.12.2.Final

.github/workflows/update.yml
=> build: Skip non released versions of Quarkus

.github/workflows/update.yml
=> build(skip-release): Skip non released versions of Quarkus

gradle.properties, projects/gradle/config-properties/gradle.properties, projects/gradle/config-properties/src/main/resources/META-INF/resources/index.html, projects/gradle/config-quickstart/gradle.properties, projects/gradle/kotlin-resteasy/gradle.properties, projects/gradle/kotlin-resteasy/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-context-propagation/gradle.properties, projects/gradle/microprofile-context-propagation/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-graphql/gradle.properties, projects/gradle/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-health/gradle.properties, projects/gradle/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-jwt/gradle.properties, projects/gradle/microprofile-jwt/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-lra/gradle.properties, projects/gradle/microprofile-lra/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-openapi/gradle.properties, projects/gradle/microprofile-openapi/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-reactive-messaging/gradle.properties, projects/gradle/microprofile-reactive-messaging/src/main/resources/META-INF/resources/index.html, projects/gradle/using-vertx/gradle.properties, projects/gradle/using-vertx/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-graphql/pom.xml, projects/maven/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-health/pom.xml, projects/maven/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-jwt/pom.xml, projects/maven/microprofile-jwt/src/main/resources/META-INF/resources/index.html, src/main/resources/quarkus.xml
=> fix: Update the Quarkus runtime used by the plugin to version 2.13.0.Final

gradle.properties, projects/gradle/config-properties/gradle.properties, projects/gradle/config-properties/src/main/resources/META-INF/resources/index.html, projects/gradle/config-quickstart/gradle.properties, projects/gradle/kotlin-resteasy/gradle.properties, projects/gradle/kotlin-resteasy/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-context-propagation/gradle.properties, projects/gradle/microprofile-context-propagation/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-graphql/gradle.properties, projects/gradle/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-health/gradle.properties, projects/gradle/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-jwt/gradle.properties, projects/gradle/microprofile-jwt/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-lra/gradle.properties, projects/gradle/microprofile-lra/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-openapi/gradle.properties, projects/gradle/microprofile-openapi/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-reactive-messaging/gradle.properties, projects/gradle/microprofile-reactive-messaging/src/main/resources/META-INF/resources/index.html, projects/gradle/using-vertx/gradle.properties, projects/gradle/using-vertx/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-graphql/pom.xml, projects/maven/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-health/pom.xml, projects/maven/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-jwt/pom.xml, projects/maven/microprofile-jwt/src/main/resources/META-INF/resources/index.html, src/main/resources/quarkus.xml
=> fix: Update the Quarkus runtime used by the plugin to version 2.13.2.Final

gradle.properties, src/main/resources/META-INF/plugin.xml
=> chore(skip-release): Prepare for 1.13.1

gradle.properties, projects/gradle/config-properties/gradle.properties, projects/gradle/config-properties/src/main/resources/META-INF/resources/index.html, projects/gradle/config-quickstart/gradle.properties, projects/gradle/kotlin-resteasy/gradle.properties, projects/gradle/kotlin-resteasy/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-context-propagation/gradle.properties, projects/gradle/microprofile-context-propagation/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-graphql/gradle.properties, projects/gradle/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-health/gradle.properties, projects/gradle/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-jwt/gradle.properties, projects/gradle/microprofile-jwt/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-lra/gradle.properties, projects/gradle/microprofile-lra/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-openapi/gradle.properties, projects/gradle/microprofile-openapi/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-reactive-messaging/gradle.properties, projects/gradle/microprofile-reactive-messaging/src/main/resources/META-INF/resources/index.html, projects/gradle/using-vertx/gradle.properties, projects/gradle/using-vertx/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-graphql/pom.xml, projects/maven/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-health/pom.xml, projects/maven/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-jwt/pom.xml, projects/maven/microprofile-jwt/src/main/resources/META-INF/resources/index.html, src/main/resources/quarkus.xml
=> fix: Update the Quarkus runtime used by the plugin to version 2.13.3.Final

src/main/java/com/redhat/devtools/intellij/qute/lang/QuteASTNode.java, src/main/java/com/redhat/devtools/intellij/qute/lang/QuteElementTypes.java
=> fix: Error while editing a qute template

src/main/java/com/redhat/devtools/intellij/quarkus/lsp4ij/operations/highlight/LSPHighlightUsagesHandler.java, src/main/java/com/redhat/devtools/intellij/quarkus/lsp4ij/operations/highlight/LSPHighlightUsagesHandlerFactory.java
=> fix: Quarkus Tools brakes Intellijs syntax highlighting

gradle.properties, projects/gradle/config-properties/gradle.properties, projects/gradle/config-properties/src/main/resources/META-INF/resources/index.html, projects/gradle/config-quickstart/gradle.properties, projects/gradle/kotlin-resteasy/gradle.properties, projects/gradle/kotlin-resteasy/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-context-propagation/gradle.properties, projects/gradle/microprofile-context-propagation/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-graphql/gradle.properties, projects/gradle/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-health/gradle.properties, projects/gradle/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-jwt/gradle.properties, projects/gradle/microprofile-jwt/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-lra/gradle.properties, projects/gradle/microprofile-lra/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-openapi/gradle.properties, projects/gradle/microprofile-openapi/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-reactive-messaging/gradle.properties, projects/gradle/microprofile-reactive-messaging/src/main/resources/META-INF/resources/index.html, projects/gradle/using-vertx/gradle.properties, projects/gradle/using-vertx/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-health/pom.xml, projects/maven/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-jwt/pom.xml, projects/maven/microprofile-jwt/src/main/resources/META-INF/resources/index.html, src/main/java/com/redhat/devtools/intellij/quarkus/QuarkusConstants.java, src/main/java/com/redhat/microprofile/psi/internal/quarkus/core/properties/QuarkusConfigPropertiesProvider.java, src/main/resources/quarkus.xml
=> fix: Update the Quarkus runtime used by the plugin to version 2.14.0.Final

gradle.properties, projects/gradle/config-properties/gradle.properties, projects/gradle/config-properties/src/main/resources/META-INF/resources/index.html, projects/gradle/config-quickstart/gradle.properties, projects/gradle/kotlin-resteasy/gradle.properties, projects/gradle/kotlin-resteasy/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-context-propagation/gradle.properties, projects/gradle/microprofile-context-propagation/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-graphql/gradle.properties, projects/gradle/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-health/gradle.properties, projects/gradle/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-jwt/gradle.properties, projects/gradle/microprofile-jwt/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-lra/gradle.properties, projects/gradle/microprofile-lra/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-openapi/gradle.properties, projects/gradle/microprofile-openapi/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-reactive-messaging/gradle.properties, projects/gradle/microprofile-reactive-messaging/src/main/resources/META-INF/resources/index.html, projects/gradle/using-vertx/gradle.properties, projects/gradle/using-vertx/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-health/pom.xml, projects/maven/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-jwt/pom.xml, projects/maven/microprofile-jwt/src/main/resources/META-INF/resources/index.html, src/main/java/com/redhat/devtools/intellij/quarkus/QuarkusConstants.java, src/main/resources/quarkus.xml
=> fix: Update the Quarkus runtime used by the plugin to version 2.14.1.Final

gradle.properties, projects/gradle/config-properties/gradle.properties, projects/gradle/config-properties/src/main/resources/META-INF/resources/index.html, projects/gradle/config-quickstart/gradle.properties, projects/gradle/kotlin-resteasy/gradle.properties, projects/gradle/kotlin-resteasy/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-context-propagation/gradle.properties, projects/gradle/microprofile-context-propagation/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-graphql/gradle.properties, projects/gradle/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-health/gradle.properties, projects/gradle/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-jwt/gradle.properties, projects/gradle/microprofile-jwt/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-lra/gradle.properties, projects/gradle/microprofile-lra/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-openapi/gradle.properties, projects/gradle/microprofile-openapi/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-reactive-messaging/gradle.properties, projects/gradle/microprofile-reactive-messaging/src/main/resources/META-INF/resources/index.html, projects/gradle/using-vertx/gradle.properties, projects/gradle/using-vertx/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-health/pom.xml, projects/maven/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-jwt/pom.xml, projects/maven/microprofile-jwt/src/main/resources/META-INF/resources/index.html, src/main/java/com/redhat/devtools/intellij/quarkus/QuarkusConstants.java, src/main/resources/quarkus.xml
=> fix: Update the Quarkus runtime used by the plugin to version 2.14.2.Final

src/main/java/com/redhat/devtools/intellij/quarkus/lsp4ij/LanguageServerWrapper.java
=> fix: NullPointerException in LSPCodeActionAnnotator

build.gradle, gradle.properties, src/main/resources/META-INF/plugin.xml
=> chore(skip-release): Prepare for 1.14.1

gradle.properties, projects/gradle/config-properties/gradle.properties, projects/gradle/config-properties/src/main/resources/META-INF/resources/index.html, projects/gradle/config-quickstart/gradle.properties, projects/gradle/kotlin-resteasy/gradle.properties, projects/gradle/kotlin-resteasy/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-context-propagation/gradle.properties, projects/gradle/microprofile-context-propagation/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-graphql/gradle.properties, projects/gradle/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-health/gradle.properties, projects/gradle/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-jwt/gradle.properties, projects/gradle/microprofile-jwt/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-lra/gradle.properties, projects/gradle/microprofile-lra/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-openapi/gradle.properties, projects/gradle/microprofile-openapi/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-reactive-messaging/gradle.properties, projects/gradle/microprofile-reactive-messaging/src/main/resources/META-INF/resources/index.html, projects/gradle/using-vertx/gradle.properties, projects/gradle/using-vertx/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-health/pom.xml, projects/maven/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-jwt/pom.xml, projects/maven/microprofile-jwt/src/main/resources/META-INF/resources/index.html, src/main/java/com/redhat/devtools/intellij/quarkus/QuarkusConstants.java, src/main/resources/quarkus.xml
=> fix: Update the Quarkus runtime used by the plugin to version 2.14.3.Final

build.gradle
=> fix: Qute code completion is broken

src/main/java/com/redhat/devtools/intellij/qute/psi/QuteSupportForTemplate.java
=> fix: id field on PanacheEntity is not resolved in Qute templates

gradle.properties, src/main/resources/META-INF/plugin.xml
=> chore(skip-release): Prepare for 1.15.0

build.gradle, src/main/java/com/redhat/devtools/intellij/quarkus/lsp/QuarkusLanguageClient.java, src/main/java/com/redhat/devtools/intellij/quarkus/lsp4ij/IndexAwareLanguageClient.java, src/main/java/com/redhat/devtools/intellij/qute/lsp/QuteLanguageClient.java
=> fix: IndexNotReadyException when processing LSP events

gradle.properties, projects/gradle/config-properties/gradle.properties, projects/gradle/config-properties/src/main/resources/META-INF/resources/index.html, projects/gradle/config-quickstart/gradle.properties, projects/gradle/kotlin-resteasy/gradle.properties, projects/gradle/kotlin-resteasy/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-context-propagation/gradle.properties, projects/gradle/microprofile-context-propagation/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-graphql/gradle.properties, projects/gradle/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-health/gradle.properties, projects/gradle/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-jwt/gradle.properties, projects/gradle/microprofile-jwt/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-lra/gradle.properties, projects/gradle/microprofile-lra/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-openapi/gradle.properties, projects/gradle/microprofile-openapi/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-reactive-messaging/gradle.properties, projects/gradle/microprofile-reactive-messaging/src/main/resources/META-INF/resources/index.html, projects/gradle/using-vertx/gradle.properties, projects/gradle/using-vertx/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-health/pom.xml, projects/maven/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-jwt/pom.xml, projects/maven/microprofile-jwt/src/main/resources/META-INF/resources/index.html, src/main/java/com/redhat/devtools/intellij/quarkus/QuarkusConstants.java, src/main/resources/quarkus.xml
=> fix: Update the Quarkus runtime used by the plugin to version 2.15.0.Final

gradle.properties, projects/gradle/config-properties/gradle.properties, projects/gradle/config-properties/src/main/resources/META-INF/resources/index.html, projects/gradle/config-quickstart/gradle.properties, projects/gradle/kotlin-resteasy/gradle.properties, projects/gradle/kotlin-resteasy/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-context-propagation/gradle.properties, projects/gradle/microprofile-context-propagation/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-graphql/gradle.properties, projects/gradle/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-health/gradle.properties, projects/gradle/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-jwt/gradle.properties, projects/gradle/microprofile-jwt/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-lra/gradle.properties, projects/gradle/microprofile-lra/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-openapi/gradle.properties, projects/gradle/microprofile-openapi/src/main/resources/META-INF/resources/index.html, projects/gradle/microprofile-reactive-messaging/gradle.properties, projects/gradle/microprofile-reactive-messaging/src/main/resources/META-INF/resources/index.html, projects/gradle/using-vertx/gradle.properties, projects/gradle/using-vertx/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-graphql/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-health/pom.xml, projects/maven/microprofile-health/src/main/resources/META-INF/resources/index.html, projects/maven/microprofile-jwt/pom.xml, projects/maven/microprofile-jwt/src/main/resources/META-INF/resources/index.html, src/main/java/com/redhat/devtools/intellij/quarkus/QuarkusConstants.java, src/main/resources/quarkus.xml
=> fix: Update the Quarkus runtime used by the plugin to version 2.15.1.Final

gradle.properties, src/main/java/com/redhat/devtools/intellij/quarkus/QuarkusConstants.java, src/main/resources/quarkus.xml
=> fix: Update the Quarkus runtime used by the plugin to version 2.15.2.Final

gradle.properties, src/main/java/com/redhat/devtools/intellij/quarkus/QuarkusConstants.java, src/main/resources/quarkus.xml
=> fix: Update the Quarkus runtime used by the plugin to version 2.15.3.Final

gradle.properties
=> build: Remove Kotlin standard library from distribution zip

gradle.properties, src/main/java/com/redhat/devtools/intellij/quarkus/QuarkusConstants.java, src/main/resources/quarkus.xml
=> fix: Update the Quarkus runtime used by the plugin to version 2.16.0.Final

gradle.properties, src/main/java/com/redhat/devtools/intellij/quarkus/QuarkusConstants.java, src/main/resources/quarkus.xml
=> fix: Update the Quarkus runtime used by the plugin to version 2.16.1.Final

gradle.properties, src/main/java/com/redhat/devtools/intellij/quarkus/QuarkusConstants.java, src/main/resources/quarkus.xml
=> fix: Update the Quarkus runtime used by the plugin to version 2.16.2.Final

gradle.properties, src/main/java/com/redhat/devtools/intellij/quarkus/QuarkusConstants.java, src/main/resources/quarkus.xml
=> fix: Update the Quarkus runtime used by the plugin to version 2.16.3.Final

src/main/java/com/redhat/devtools/intellij/quarkus/lsp4ij/LSPIJUtils.java
=> fix: Read access is allowed from inside read-action (or EDT)

gradle.properties, src/main/java/com/redhat/devtools/intellij/quarkus/QuarkusConstants.java, src/main/resources/quarkus.xml
=> fix: Update the Quarkus runtime used by the plugin to version 2.16.4.Final

gradle.properties, src/main/java/com/redhat/devtools/intellij/quarkus/QuarkusConstants.java, src/main/resources/quarkus.xml
=> fix: Update the Quarkus runtime used by the plugin to version 2.16.5.Final

src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/internal/core/ls/PsiUtilsLSImpl.java
depends on #760 which has to be merged first
fixes #757
=> fix: get classpath kind in ReadAction (#757)

gradle.properties, src/main/java/com/redhat/devtools/intellij/quarkus/QuarkusConstants.java, src/main/resources/quarkus.xml
=> fix: Update the Quarkus runtime used by the plugin to version 2.16.6.Final

gradle.properties, src/main/resources/META-INF/plugin.xml
=> chore(skip-release): Prepare for 1.17.1 (#779)

src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/java/codeaction/JavaCodeActionContext.java, src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/java/codeaction/JavaCodeActionResolveContext.java, src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/internal/core/java/codeaction/CodeActionHandler.java
fix: java.lang.IndexOutOfBoundsException when trying to "insert @RestClient"
Fixes #764
=> fix: java.lang.IndexOutOfBoundsException when trying to "insert @RestClient"

src/test/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/health/java/MicroProfileHealthJavaDiagnosticsTest.java, src/test/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/openapi/java/GenerateOpenAPIAnnotationsTest.java, src/test/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/restclient/java/MicroProfileRestClientJavaDiagnosticsTest.java
=> fix: corrected asserted endLine offsets in CodeActions (#800)

src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/PropertiesManagerForJava.java, src/main/java/com/redhat/devtools/intellij/quarkus/lsp/QuarkusLanguageClient.java, src/main/java/com/redhat/devtools/intellij/quarkus/lsp4ij/LSPVirtualFileWrapper.java, src/main/java/com/redhat/devtools/intellij/quarkus/lsp4ij/LanguageServerWrapper.java, src/main/java/com/redhat/devtools/intellij/quarkus/lsp4ij/operations/codeactions/LSPCodeActionIntentionAction.java, src/main/java/com/redhat/devtools/intellij/qute/lsp/QuteServer.java
fix: CodeAction should be resolved only when user click on QuickFix
Fixes #785
Signed-off-by: azerr <azerr@redhat.com>
=> fix: CodeAction should be resolved only when user click on QuickFix

projects/lsp4mp/projects/maven/.gitignore, projects/lsp4mp/projects/maven/open-liberty/.classpath, projects/lsp4mp/projects/maven/open-liberty/.gitignore, projects/lsp4mp/projects/maven/open-liberty/.project, projects/lsp4mp/projects/maven/open-liberty/pom.xml, projects/lsp4mp/projects/maven/open-liberty/src/main/java/com/demo/rest/MyResource.java, projects/lsp4mp/projects/maven/open-liberty/src/main/java/com/demo/rest/MyService.java, projects/lsp4mp/projects/maven/open-liberty/src/main/java/com/demo/rest/RestApplication.java, projects/lsp4mp/projects/maven/open-liberty/src/main/java/com/demo/rest/Service.java, projects/lsp4mp/projects/maven/open-liberty/src/main/java/com/demo/rest/injectAnnotation.java, projects/lsp4mp/projects/maven/open-liberty/src/main/liberty/config/server.xml, src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/MicroProfileConfigConstants.java, src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/java/corrections/proposal/InsertAnnotationProposal.java, src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/internal/restclient/java/InjectAndRestClientAnnotationMissingQuickFix.java, src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/internal/restclient/java/InjectAnnotationMissingQuickFix.java, src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/internal/restclient/java/MicroProfileRestClientDiagnosticsParticipant.java, src/test/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/restclient/java/MicroProfileRestClientJavaDiagnosticsTest.java
Port of https://github.com/eclipse/lsp4mp/commit/b416c804b9c2bc072ffa2010e728436ef899860b to IDEA
Part of #806 and #803
Fixes insertion of duplicate annotations
=> feat: Support jakarta namespace with Inject annotation

src/main/java/com/redhat/devtools/intellij/quarkus/lsp/QuarkusServer.java, src/main/java/com/redhat/devtools/intellij/quarkus/lsp4ij/server/JavaProcessStreamConnectionProvider.java, src/main/java/com/redhat/devtools/intellij/quarkus/lsp4ij/server/OS.java, src/main/java/com/redhat/devtools/intellij/qute/lsp/QuteServer.java
Provide the capability to debug quarkus and qute ls
Fixes #769
=> feat: Provide the capability to debug quarkus and qute ls (#769)

src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/jaxrs/JaxRsContext.java, src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/jaxrs/JaxRsUtils.java, src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/utils/AnnotationUtils.java, src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/internal/jaxrs/JaxRsConstants.java, src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/internal/jaxrs/java/JaxRsCodeLensParticipant.java, src/test/java/com/redhat/microprofile/psi/quarkus/jaxrs/JaxRsApplicationPathCodeLensTest.java
- feat: support codelens for Quarkus 3/Jakarta REST endpoints
- fix: align URL codelens with annotation (fixes #795)
=> feat: support codelens for Quarkus 3/Jakarta REST endpoints

src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/jaxrs/JaxRsUtils.java, src/test/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/jaxrs/java/JaxRsCodeLensTest.java
=> fix: update tests after #795 fix

gradle.properties, src/main/java/com/redhat/devtools/intellij/quarkus/QuarkusConstants.java, src/main/resources/quarkus.xml
=> fix: Update the Quarkus runtime used by the plugin to version 3.0.1.Final

projects/quarkus/projects/maven/config-mapping/src/main/java/org/acme/optionals/Optionals.java, src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/AbstractPropertiesProvider.java, src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/utils/PsiTypeUtils.java, src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/internal/config/properties/MicroProfileConfigPropertyProvider.java, src/main/java/com/redhat/microprofile/psi/internal/quarkus/core/properties/QuarkusConfigMappingProvider.java, src/main/java/com/redhat/microprofile/psi/internal/quarkus/core/properties/QuarkusConfigRootProvider.java, src/test/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/MicroProfileAssert.java, src/test/java/com/redhat/microprofile/psi/quarkus/configmapping/QuarkusConfigMappingTest.java
=> fix: correctly treat optionals that dont have generics (#801)

gradle.properties, src/main/java/com/redhat/devtools/intellij/quarkus/QuarkusConstants.java, src/main/resources/quarkus.xml
=> fix: Update the Quarkus runtime used by the plugin to version 3.0.2.Final

src/main/resources/META-INF/plugin-gradle.xml, src/main/resources/META-INF/plugin-maven.xml, src/main/resources/META-INF/plugin.xml
=> fix: 1.16 made JetBrain Gradle plugin mandatory

gradle.properties, src/main/resources/META-INF/plugin.xml
=> chore(skip-release): Prepare for 1.18.0 (#841)

build.gradle
=> fix(skip-release): handle ideaVersion 'LATEST-EAP-SNAPSHOT'(#844)

gradle.properties, src/main/java/com/redhat/devtools/intellij/quarkus/QuarkusConstants.java, src/main/resources/quarkus.xml
=> fix: Update the Quarkus runtime used by the plugin to version 3.0.3.Final

src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/internal/core/ls/PsiUtilsLSImpl.java, src/main/java/com/redhat/devtools/intellij/quarkus/lsp4ij/LSPIJUtils.java, src/main/java/com/redhat/devtools/intellij/quarkus/lsp4ij/operations/hover/LSPTextHover.java, src/main/java/com/redhat/devtools/intellij/qute/psi/core/command/QuteJavaDefinitionAction.java, src/main/java/com/redhat/devtools/intellij/qute/psi/core/command/QuteOpenURIAction.java
The problem (and the fix) is similar to #735
Fixes #856
=> fix: remove usage of VfsUtil.findFileByURL

src/main/java/com/redhat/devtools/intellij/quarkus/lsp4ij/LanguageServerWrapper.java, src/main/java/com/redhat/devtools/intellij/quarkus/lsp4ij/LanguageServersRegistry.java, src/main/java/com/redhat/devtools/intellij/quarkus/lsp4ij/console/LSPConsoleToolWindowPanel.java, src/main/java/com/redhat/devtools/intellij/quarkus/lsp4ij/console/explorer/LanguageServerExplorer.java, src/main/java/com/redhat/devtools/intellij/quarkus/lsp4ij/console/explorer/LanguageServerExplorerLifecycleListener.java, src/main/java/com/redhat/devtools/intellij/quarkus/lsp4ij/console/explorer/LanguageServerExplorerTreeDataProvider.java, src/main/java/com/redhat/devtools/intellij/quarkus/lsp4ij/console/explorer/LanguageServerProcessTreeNode.java, src/main/java/com/redhat/devtools/intellij/quarkus/lsp4ij/console/explorer/LanguageServerTreeNode.java, src/main/java/com/redhat/devtools/intellij/quarkus/lsp4ij/console/explorer/TracingMessageConsumer.java, src/main/java/com/redhat/devtools/intellij/quarkus/lsp4ij/console/explorer/actions/RestartServerAction.java, src/main/java/com/redhat/devtools/intellij/quarkus/lsp4ij/console/explorer/actions/StopServerAction.java, src/main/java/com/redhat/devtools/intellij/quarkus/lsp4ij/lifecycle/LanguageServerLifecycleListener.java, src/main/java/com/redhat/devtools/intellij/quarkus/lsp4ij/lifecycle/LanguageServerLifecycleManager.java, src/main/java/com/redhat/devtools/intellij/quarkus/lsp4ij/server/ProcessStreamConnectionProvider.java, src/main/java/com/redhat/devtools/intellij/quarkus/lsp4ij/settings/LanguageServerConfigurable.java, src/main/resources/META-INF/lsp.xml, src/main/resources/messages/LanguageServerBundle.properties
feat: Improve LSP console (#867)
Fixes #867
=> feat: Improve LSP console (#867)

projects/qute/projects/maven/qute-quickstart/src/main/java/org/acme/qute/HelloResource.java, src/main/java/com/redhat/devtools/intellij/qute/psi/internal/template/TemplateDataVisitor.java
Collect data model for Qute doesn't support fluent API (#876)
Fixes #876
=> fix: Collect data model for Qute doesn't support fluent API (#876)

src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/internal/core/ls/PsiUtilsLSImpl.java, src/main/java/com/redhat/devtools/intellij/quarkus/QuarkusProjectService.java, src/main/java/com/redhat/devtools/intellij/quarkus/lsp4ij/LSPIJUtils.java, src/main/java/com/redhat/devtools/intellij/quarkus/lsp4ij/LanguageClientImpl.java, src/main/java/com/redhat/devtools/intellij/qute/lsp/QuteLanguageClient.java, src/main/java/com/redhat/devtools/intellij/qute/psi/core/command/QuteJavaDefinitionAction.java, src/main/java/com/redhat/devtools/intellij/qute/psi/core/command/QuteOpenURIAction.java, src/main/java/com/redhat/devtools/intellij/qute/psi/internal/java/QuteJavaCodeLensCollector.java, src/main/java/com/redhat/devtools/intellij/qute/psi/internal/template/QuarkusIntegrationForQute.java, src/main/java/com/redhat/devtools/intellij/qute/psi/internal/template/datamodel/DataModelProviderRegistry.java, src/main/java/com/redhat/devtools/intellij/qute/psi/utils/PsiQuteProjectUtils.java
fix: Use LSPIJUtils to build all uri (#874)
Fixes #874
=> fix: Use LSPIJUtils to build all uri (#874)

src/main/java/com/redhat/devtools/intellij/lsp4ij/LanguageServerWrapper.java, src/main/java/com/redhat/devtools/intellij/lsp4ij/LanguageServersRegistry.java, src/main/java/com/redhat/devtools/intellij/lsp4ij/ServerExtensionPointBean.java
fix: StreamConnectionProvider instance should not be a singleton (#888)
Fixes #888
=> fix: StreamConnectionProvider instance should not be a singleton (#888)

gradle.properties, src/main/java/com/redhat/devtools/intellij/quarkus/QuarkusConstants.java, src/main/resources/quarkus.xml
=> fix: Update the Quarkus runtime used by the plugin to version 3.0.4.Final

src/main/java/com/redhat/devtools/intellij/lsp4ij/console/LSPConsoleToolWindowPanel.java, src/main/java/com/redhat/devtools/intellij/lsp4ij/console/LSPConsoleView.java, src/main/java/com/redhat/devtools/intellij/lsp4ij/console/LSPTextConsoleBuilderImpl.java, src/main/java/com/redhat/devtools/intellij/lsp4ij/console/actions/AutoFoldingAction.java, src/main/java/com/redhat/devtools/intellij/lsp4ij/console/actions/ClearThisConsoleAction.java, src/main/resources/META-INF/lsp4ij.xml, src/main/resources/messages/LanguageServerBundle.properties
feat: Folding support for LSP console (#885)
Fixes #885
Here a demo with LSP trace folding:
=> feat: Folding support for LSP console (#885)

build.gradle, projects/qute/projects/maven/qute-quickstart/src/main/java/org/acme/qute/ItemResourceWithFragment.java, src/main/java/com/redhat/devtools/intellij/qute/psi/internal/QuteJavaConstants.java, src/main/java/com/redhat/devtools/intellij/qute/psi/internal/java/AbstractQuteTemplateLinkCollector.java, src/main/java/com/redhat/devtools/intellij/qute/psi/internal/java/QuteErrorCode.java, src/main/java/com/redhat/devtools/intellij/qute/psi/internal/java/QuteJavaCodeLensCollector.java, src/main/java/com/redhat/devtools/intellij/qute/psi/internal/java/QuteJavaDiagnosticsCollector.java, src/main/java/com/redhat/devtools/intellij/qute/psi/internal/java/QuteJavaDocumentLinkCollector.java, src/main/java/com/redhat/devtools/intellij/qute/psi/internal/template/TemplateDataCollector.java, src/main/java/com/redhat/devtools/intellij/qute/psi/internal/template/TemplateDataSupport.java, src/main/java/com/redhat/devtools/intellij/qute/psi/internal/template/datamodel/CheckedTemplateSupport.java, src/main/java/com/redhat/devtools/intellij/qute/psi/internal/template/datamodel/TemplateFieldSupport.java, src/main/java/com/redhat/devtools/intellij/qute/psi/utils/PsiQuteProjectUtils.java, src/main/java/com/redhat/devtools/intellij/qute/psi/utils/TemplatePathInfo.java, src/test/java/com/redhat/devtools/intellij/qute/psi/java/JavaCodeLensTest.java, src/test/java/com/redhat/devtools/intellij/qute/psi/java/JavaDiagnosticsTest.java, src/test/java/com/redhat/devtools/intellij/qute/psi/java/JavaDocumentLinkTest.java, src/test/java/com/redhat/devtools/intellij/qute/psi/template/TemplateGetDataModelProjectTest.java
fix: Fragment support between Java / Template file (#896)
Fixes #896
Port of commit https://github.com/redhat-developer/quarkus-ls/commit/820e5a9b71302e9f21ea5bc29e1610b51b4757d7 of Quarkus LS
=> fix: Fragment support between Java / Template file (#896)

projects/qute/projects/maven/qute-quickstart/src/main/java/org/acme/qute/ItemResourceWithFragment.java
=> fix: Fix Qute test

gradle.properties, src/main/java/com/redhat/devtools/intellij/quarkus/QuarkusConstants.java, src/main/resources/quarkus.xml
=> fix: Update the Quarkus runtime used by the plugin to version 3.1.0.Final

.github/workflows/ci.yml, README.md
=> build: upload plugin.zip after CI build

gradle.properties, src/main/resources/META-INF/plugin.xml
chore(skip-release): Prepare for 1.20.0
=> chore(skip-release): Prepare for 1.20.0

.github/workflows/buildZip.yml, .github/workflows/ci.yml, README.md
=> build: build plugin zip in separate workflow

src/main/java/com/redhat/devtools/intellij/lsp4ij/server/JavaProcessCommandBuilder.java
fix: Error starting LSP Qute (#927)
Fixes #927
=> fix: Error starting LSP Qute (#927)

src/main/java/com/redhat/devtools/intellij/qute/psi/QuteSupportForTemplate.java
fix: Read access problem with Qute getJavadoc (#932)
Fixes #932
=> fix: Read access problem with Qute getJavadoc (#932)

src/main/java/com/redhat/devtools/intellij/quarkus/module/QuarkusExtensionsStep.java
Since `ExtensionsTree` doesn't extend `CheckboxTreeBase` directly, you can't customize its `CheckboxTreeBase.CheckPolicy`, so `CheckboxTreeHelper.adjustParentsAndChildren` basically calls `nodeStateChanged(node.getParent())`, which doesn't hold a QuarkusExtension and leads to the NPE in #639
The fix consists in checking if the current node holds a `QuarkusExtension`
Fixes #639
=> fix: prevent NPE when unselecting extension in wizard

projects/qute/projects/maven/qute-quickstart/src/main/java/org/acme/qute/ItemWithAnnotationInParams.java, src/main/java/com/redhat/devtools/intellij/qute/psi/utils/PsiTypeUtils.java, src/test/java/com/redhat/devtools/intellij/qute/psi/template/TemplateGetResolvedJavaTypeTest.java
fix: resolve signature of method parameters must ignore annotations (#935)
Fixes #935
=> fix: signature resolution of method parameters must ignore annotations (#935)

.gitignore, build.gradle, gradle.properties, intellij-community/java/testFramework/src/com/intellij/compiler/artifacts/ArtifactsTestUtil.java, intellij-community/platform/external-system-api/testFramework/src/com/intellij/platform/externalSystem/testFramework/ExternalSystemImportingTestCase.java, intellij-community/platform/external-system-api/testFramework/src/com/intellij/platform/externalSystem/testFramework/ExternalSystemTestCase.java, intellij-community/platform/external-system-impl/testSrc/com/intellij/openapi/externalSystem/test/JavaExternalSystemImportingTestCase.java, intellij-community/platform/lang-impl/testSources/com/intellij/openapi/roots/ui/configuration/SdkTestCase.kt, intellij-community/platform/testFramework/extensions/src/com/intellij/testFramework/assertions/Assertions.java, intellij-community/platform/testFramework/extensions/src/com/intellij/testFramework/assertions/JdomAssert.kt, intellij-community/platform/testFramework/extensions/src/com/intellij/testFramework/assertions/StringAssertEx.kt, intellij-community/platform/testFramework/extensions/src/com/intellij/testFramework/assertions/snapshot.kt, intellij-community/plugins/gradle/testSources/org/jetbrains/plugins/gradle/importing/GradleImportingTestCase.java, intellij-community/plugins/gradle/testSources/org/jetbrains/plugins/gradle/importing/TestGradleBuildScriptBuilder.kt, intellij-community/plugins/gradle/tooling-extension-impl/testSources/org/jetbrains/plugins/gradle/tooling/VersionMatcherRule.java, intellij-community/plugins/gradle/tooling-extension-impl/testSources/org/jetbrains/plugins/gradle/tooling/annotation/TargetVersions.java, intellij-community/plugins/gradle/tooling-extension-impl/testSources/org/jetbrains/plugins/gradle/tooling/builder/AbstractModelBuilderTest.java, intellij-community/plugins/gradle/tooling-extension-impl/testSources/org/jetbrains/plugins/gradle/tooling/util/VersionMatcher.java, intellij-community/plugins/maven/testFramework/src/com/intellij/maven/testFramework/MavenImportingTestCase.java, intellij-community/plugins/maven/testFramework/src/com/intellij/maven/testFramework/MavenTestCase.java, intellij-community/plugins/maven/testFramework/src/com/intellij/maven/testFramework/NullMavenConsole.java, pulltest.sh, src/test/java/com/redhat/devtools/intellij/GradleTestCase.java, src/test/java/com/redhat/devtools/intellij/MavenModuleImportingTestCase.java, src/test/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/PropertiesManagerTest.java, src/test/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/config/properties/MicroProfileConfigPropertyTest.java, src/test/java/com/redhat/devtools/intellij/quarkus/module/QuarkusModelRegistryTest.java, src/test/java/com/redhat/devtools/intellij/qute/psi/template/TemplateGetJavaTypeTest.java, src/test/java/com/redhat/devtools/intellij/qute/psi/utils/CDIUtilsTest.java
This will help catch problems that only exists in newer versions of IDEA
=> build: bump dev IDEA version to 2022.1

src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/PropertiesManagerForJava.java, src/main/java/com/redhat/devtools/intellij/qute/psi/QuteSupportForTemplate.java
Fixes #939 
Fixes completion error mentioned in https://github.com/redhat-developer/intellij-quarkus/issues/941#issuecomment-1585215698
=> fix: Wrap calls under Application.runReadAction()

src/main/java/com/redhat/devtools/intellij/qute/psi/QuteSupportForTemplate.java
=> fix: properly wrap QuteSupportForTemplate.getJavadoc in Application.runReadAction()

gradle.properties, src/main/resources/META-INF/plugin.xml
chore(skip-release): Prepare for 1.20.1
=> chore(skip-release): Prepare for 1.20.1

src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/internal/core/java/codeaction/CodeActionHandler.java
=> refactor: remove reflection in CodeActionHandler

src/main/java/com/redhat/devtools/intellij/lsp4ij/IndexAwareLanguageClient.java, src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/ProjectLabelManager.java, src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/PropertiesManager.java, src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/PropertiesManagerForJava.java, src/main/java/com/redhat/devtools/intellij/quarkus/lsp/QuarkusLanguageClient.java, src/main/java/com/redhat/devtools/intellij/qute/psi/QuteSupportForJava.java, src/main/java/com/redhat/devtools/intellij/qute/psi/QuteSupportForTemplate.java, src/test/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/GradlePropertiesManagerForJavaTest.java
=> refactor: execute IndexAwareLanguageClient.runAsBackground in read action by default

src/main/resources/META-INF/plugin.xml
=> feat: reporting link points to GH repo

src/main/java/com/redhat/devtools/intellij/lsp4ij/operations/completion/LSContentAssistProcessor.java
In IDEA 2023.1 (at least), typing properties in application.properties causes plenty of exceptions being logged in the console:
```
2023-06-28 11:27:49,830 [  43062]   WARN - com.redhat.devtools.intellij.lsp4ij.operations.completion.LSContentAssistProcessor - null
com.intellij.openapi.progress.ProcessCanceledException
at com.intellij.openapi.progress.util.AbstractProgressIndicatorBase.throwIfCanceled(AbstractProgressIndicatorBase.java:158)
at com.intellij.openapi.progress.util.AbstractProgressIndicatorBase.checkCanceled(AbstractProgressIndicatorBase.java:148)
at com.intellij.openapi.progress.util.AbstractProgressIndicatorExBase.checkCanceled(AbstractProgressIndicatorExBase.java:103)
at com.intellij.openapi.progress.impl.CoreProgressManager.doCheckCanceled(CoreProgressManager.java:141)
at …
```
=> fix: don't log canceled completion requests' exceptions

src/main/java/com/redhat/devtools/intellij/qute/psi/internal/extensions/renarde/RenardeResolvedJavaTypeFactory.java
Port of https://github.com/redhat-developer/quarkus-ls/pull/793/files#diff-21e074177a55ac669c78f9bccb1c64906574561132a0f9c4984f807341754bb9L50-R169
Fixes #899
=> feat: Add CodeAction to insert expected input for renarde #form

projects/quarkus/projects/maven/renarde-todo/src/main/java/rest/Game.java, src/main/java/com/redhat/microprofile/psi/internal/quarkus/renarde/java/RenardeJaxRsInfoProvider.java, src/test/java/com/redhat/microprofile/psi/quarkus/renarde/RenardeJaxRsTest.java
Port of https://github.com/redhat-developer/quarkus-ls/pull/894
See [892](https://github.com/redhat-developer/quarkus-ls/issues/892) opened by @ia3andy
=> fix: Renarde url computation

src/main/java/com/redhat/devtools/intellij/lsp4ij/ui/IconMapper.java
=> feat: map icons for Reference and Keyword

src/main/resources/META-INF/lsp4ij.xml
feat: Add icon for Language Servers views
=> feat: Add icon for Language Servers views

projects/lsp4mp/projects/maven/microprofile-graphql/src/main/java/io/openliberty/graphql/sample/WeatherService.java, src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/internal/faulttolerance/java/MicroProfileFaultToleranceASTValidator.java, src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/internal/graphql/MicroProfileGraphQLConstants.java, src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/internal/graphql/java/MicroProfileGraphQLASTValidator.java, src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/internal/graphql/java/MicroProfileGraphQLErrorCode.java, src/main/resources/META-INF/plugin.xml, src/test/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/MicroProfileMavenProjectName.java, src/test/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/graphql/java/MicroProfileGraphQLValidationTest.java, src/test/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/graphql/properties/MicroProfileGraphQLTest.java
Port of https://github.com/eclipse/lsp4mp/commit/04cf11f5c141e823179366539a2ecdbcb90b319a
Port of https://github.com/eclipse/lsp4mp/commit/e45de6001e9c58494d565a777723e19563043612
Part of #806
=> feat: Errors for annotating void methods annotated with @Query or @Mutation

src/main/java/com/redhat/devtools/intellij/qute/editor/QuteBraceMatcher.java, src/main/resources/META-INF/plugin.xml
feat: Matching bracket in Qute template
Part of https://github.com/redhat-developer/intellij-quarkus/issues/789
=> feat: Matching bracket in Qute template

src/main/java/com/redhat/devtools/intellij/qute/editor/QuteTypedHandler.java, src/main/resources/META-INF/plugin.xml
=> feat: provide { autoclose in Qute templates

gradle.properties, src/main/resources/META-INF/plugin.xml
=> chore(skip-release): Prepare for 1.22.0

src/main/java/com/redhat/devtools/intellij/lsp4ij/LSPIJUtils.java, src/main/java/com/redhat/devtools/intellij/lsp4ij/operations/completion/LSContentAssistProcessor.java, src/main/java/com/redhat/devtools/intellij/lsp4ij/operations/completion/LSIncompleteCompletionProposal.java, src/main/java/com/redhat/devtools/intellij/lsp4ij/operations/completion/SnippetTemplateFactory.java, src/main/java/com/redhat/devtools/intellij/lsp4ij/operations/completion/SnippetTemplateLoader.java, src/main/java/com/redhat/devtools/intellij/lsp4ij/operations/completion/snippet/AbstractLspSnippetHandler.java, src/main/java/com/redhat/devtools/intellij/lsp4ij/operations/completion/snippet/DefaultLspSnippetHandler.java, src/main/java/com/redhat/devtools/intellij/lsp4ij/operations/completion/snippet/Location.java, src/main/java/com/redhat/devtools/intellij/lsp4ij/operations/completion/snippet/LspSnippetParser.java, src/main/java/com/redhat/devtools/intellij/lsp4ij/operations/completion/snippet/LspSnippetVariableConstants.java, src/main/java/com/redhat/devtools/intellij/lsp4ij/operations/completion/snippet/ParseException.java, src/test/java/com/redhat/devtools/intellij/lsp4ij/operations/completion/snippet/ExtractSnippetLinkedPositionTest.java, src/test/java/com/redhat/devtools/intellij/lsp4ij/operations/completion/snippet/LspSnippetAssert.java, src/test/java/com/redhat/devtools/intellij/lsp4ij/operations/completion/snippet/handler/ExtractSnippetLinkedPositionHandler.java, src/test/java/com/redhat/devtools/intellij/lsp4ij/operations/completion/snippet/handler/LinkedPosition.java, src/test/java/com/redhat/devtools/intellij/lsp4ij/operations/completion/snippet/handler/LinkedPositionResult.java
fix: Wrong location of the caret after apply completion #1010
Fixes (#1010)
=> fix: Wrong location of the caret after apply completion #1010

src/main/java/com/redhat/devtools/intellij/lsp4ij/operations/completion/LSCompletionProposal.java, src/main/java/com/redhat/devtools/intellij/lsp4ij/operations/completion/LSContentAssistProcessor.java, src/main/java/com/redhat/devtools/intellij/lsp4ij/operations/completion/LSIncompleteCompletionProposal.java, src/main/java/com/redhat/devtools/intellij/lsp4ij/operations/completion/SnippetTemplateFactory.java, src/main/java/com/redhat/devtools/intellij/lsp4ij/operations/completion/SnippetTemplateLoader.java, src/main/java/com/redhat/devtools/intellij/lsp4ij/operations/completion/snippet/AbstractLspSnippetHandler.java, src/main/java/com/redhat/devtools/intellij/lsp4ij/operations/completion/snippet/DefaultLspSnippetHandler.java, src/main/java/com/redhat/devtools/intellij/lsp4ij/operations/completion/snippet/LspSnippetIndentOptions.java, src/test/java/com/redhat/devtools/intellij/lsp4ij/operations/completion/snippet/AdvancedTest.java, src/test/java/com/redhat/devtools/intellij/lsp4ij/operations/completion/snippet/ExtractSnippetLinkedPositionTest.java, src/test/java/com/redhat/devtools/intellij/lsp4ij/operations/completion/snippet/LspSnippetAssert.java, src/test/java/com/redhat/devtools/intellij/lsp4ij/operations/completion/snippet/handler/ExtractSnippetLinkedPositionHandler.java
fix: Inserted snippets should be reindented following the IDE indentation setting (#1019)
Fixes #1019
=> fix: Inserted snippets should be reindented following the IDE indentation setting (#1019)

gradle.properties, src/main/resources/META-INF/plugin.xml
chore(skip-release): Prepare for 1.23.0
=> chore(skip-release): Prepare for 1.23.0

src/main/java/com/redhat/microprofile/psi/internal/quarkus/renarde/java/RenardeUtils.java
fix: Bug/RuntimeException during startup of project (#1027)
Fixes #1027
=> fix: Bug/RuntimeException during startup of project (#1027)

src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/classpath/ClasspathResourceChangedListener.java, src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/classpath/ClasspathResourceChangedManager.java, src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/classpath/ClasspathResourceChangedNotifier.java, src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/classpath/RunnableProgress.java, src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/project/PsiMicroProfileProjectManager.java, src/main/java/com/redhat/devtools/intellij/quarkus/QuarkusModuleUtil.java, src/main/java/com/redhat/devtools/intellij/quarkus/QuarkusPostStartupActivity.java, src/main/java/com/redhat/devtools/intellij/quarkus/QuarkusProjectService.java, src/main/java/com/redhat/devtools/intellij/quarkus/gradle/AbstractGradleToolDelegate.java, src/main/java/com/redhat/devtools/intellij/quarkus/lsp/QuarkusLanguageClient.java, src/main/java/com/redhat/devtools/intellij/quarkus/maven/MavenToolDelegate.java, src/main/java/com/redhat/devtools/intellij/quarkus/tool/ToolDelegate.java, src/main/java/com/redhat/devtools/intellij/qute/lsp/QuteLanguageClient.java, src/test/java/com/redhat/devtools/intellij/GradleTestCase.java, src/test/java/com/redhat/devtools/intellij/MavenModuleImportingTestCase.java
fix: quarkus.kubernetes.* properties not shown or validated (#858)
Fixes #858
=> fix: quarkus.kubernetes.* properties not shown or validated (#858)

src/main/java/com/redhat/devtools/intellij/qute/psi/internal/resolver/AbstractTypeResolver.java
fix: Wrong validation in Qute with Java field with annotation (#1052)
Fixes #1052
=> fix: Wrong validation in Qute with Java field with annotation (#1052)

src/main/java/com/redhat/devtools/intellij/lsp4ij/operations/completion/LSPCompletionContributor.java, src/main/java/com/redhat/devtools/intellij/lsp4ij/operations/completion/LSPCompletionProposal.java
perf: Support for LSP CompletionList#ItemDefaults
I have implemented basicly the LSP spec. It gives the capability to minimize the JSON response of CompletionList.
=> perf: Support for LSP CompletionList#ItemDefaults

src/main/java/com/redhat/devtools/intellij/lsp4ij/internal/SupportedFeatures.java
chore: clean LSP supported features
=> chore: clean LSP supported features

src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/internal/jaxrs/java/DefaultJaxRsInfoProvider.java, src/main/java/com/redhat/devtools/intellij/qute/psi/QuteSupportForTemplate.java, src/main/java/com/redhat/microprofile/psi/internal/quarkus/renarde/java/RenardeJaxRsInfoProvider.java
fix: Take care of PsiMethod which can be a constructor (#1057)
Fixes #1057
=> fix: Take care of PsiMethod which can be a constructor (#1057)

.github/workflows/IJ.yml
=> chore: made sure IC-2023.2 is verified (#1059)

src/main/java/com/redhat/devtools/intellij/lsp4ij/ConnectDocumentToLanguageServerSetupParticipant.java, src/main/java/com/redhat/devtools/intellij/lsp4ij/LSPVirtualFileWrapper.java, src/main/java/com/redhat/devtools/intellij/lsp4ij/LanguageServerWrapper.java, src/main/java/com/redhat/devtools/intellij/lsp4ij/LanguageServiceAccessor.java, src/main/java/com/redhat/devtools/intellij/lsp4ij/client/IndexAwareLanguageClient.java, src/main/java/com/redhat/devtools/intellij/lsp4ij/client/LanguageClientImpl.java
fix: Closing one module window doesn't shutdown the running LS instances
Fixes #1069
=> fix: Closing one module window doesn't shutdown the running LS instances

src/main/java/com/redhat/devtools/intellij/quarkus/QuarkusConstants.java, src/main/java/com/redhat/devtools/intellij/quarkus/QuarkusModuleUtil.java
=> fix: optimize isQuarkusModule computation

src/main/java/com/redhat/devtools/intellij/lsp4ij/AbstractLSPInlayProvider.java, src/main/java/com/redhat/devtools/intellij/quarkus/lang/QuarkusImplicitPropertyUsageProvider.java
=> fix: replace usage of deprecated classes marked for removal

src/main/java/com/redhat/devtools/intellij/lsp4ij/console/LSPConsoleToolWindowPanel.java
=> fix: prevent NPE when changing trace value from LSP Console view

src/main/java/com/redhat/devtools/intellij/lsp4ij/LSPVirtualFileWrapper.java, src/main/java/com/redhat/devtools/intellij/lsp4ij/operations/hover/LSPTextHover.java, src/main/java/com/redhat/devtools/intellij/lsp4ij/operations/hover/LSPTextHoverForFile.java
fix: NPE in initiateHoverRequest (this.cancellationSupport is null)
Fixes #1104
=> fix: NPE in initiateHoverRequest (this.cancellationSupport is null)

gradle.properties, src/main/resources/META-INF/plugin.xml
=> chore(skip-release): Prepare for 1.25.0

src/main/java/com/redhat/devtools/intellij/quarkus/module/QuarkusModuleInfoStep.java
=> fix: handle Quarkus streams with null status

src/main/java/com/redhat/devtools/intellij/lsp4ij/internal/CancellationSupport.java, src/main/java/com/redhat/devtools/intellij/lsp4ij/operations/highlight/LSPHighlightUsagesHandlerFactory.java
=> fix: prevent ConcurrentModificationException in CancellationSupport.cancel

.github/workflows/IJ.yml
=> build: add 2023.2.1 to the build matrix

src/main/java/com/redhat/microprofile/psi/internal/quarkus/core/properties/QuarkusConfigMappingProvider.java
fix: java.lang.AssertionError: No constructors are supposed to reach this point
Fixes #1145
=> fix: java.lang.AssertionError: No constructors are supposed to reach this point

gradle.properties, src/main/resources/META-INF/plugin.xml
=> chore(skip-release): Prepare for 1.27.0

src/main/java/com/redhat/devtools/intellij/lsp4ij/LSPIJUtils.java
=> fix: create parent directories in LSPIJUtils.createFile

gradle.properties, src/main/resources/META-INF/plugin.xml
=> chore(skip-release): Prepare for 1.28.0

src/main/java/com/redhat/devtools/intellij/lsp4ij/internal/PromiseToCompletableFuture.java
fix: Deadlock with IDEA EAP 2023-3 EAP
Fixes #1192
=> fix: Deadlock with IDEA EAP 2023-3 EAP

src/main/java/com/redhat/devtools/intellij/lsp4ij/AbstractLSPInlayProvider.java, src/main/java/com/redhat/devtools/intellij/lsp4ij/operations/codelens/LSPCodelensInlayProvider.java, src/main/java/com/redhat/devtools/intellij/lsp4ij/operations/inlayhint/LSPInlayHintInlayProvider.java
fix: CodeLens are not displayed in IDEA EAP 2023-3 EAP
Fixes #1204
=> fix: CodeLens are not displayed in IDEA EAP 2023-3 EAP

src/main/java/com/redhat/devtools/intellij/quarkus/lsp/QuarkusServer.java
fix: use MicroProfile LS debug settings
=> fix: use MicroProfile LS debug settings

.github/workflows/IJ.yml
build: add IC-2023.2.3 to the build matrix
=> build: add IC-2023.2.3 to the build matrix

src/main/java/com/redhat/devtools/intellij/quarkus/QuarkusConstants.java, src/main/java/com/redhat/devtools/intellij/quarkus/psi/internal/ScheduledImplicitUsageProvider.java, src/main/resources/META-INF/lsp4ij-quarkus.xml
=> fix: show @Scheduled methods as implicitly used

README.md
=> docs: add articles section in readme

src/main/java/com/redhat/devtools/intellij/lsp4ij/LanguageServerWrapper.java, src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/classpath/ClasspathResourceChangedNotifier.java
=> fix: prevent TimerTask errors from cancelling their Timer

src/main/java/com/redhat/devtools/intellij/lsp4ij/AbstractLSPInlayProvider.java, src/main/java/com/redhat/devtools/intellij/lsp4ij/operations/codelens/LSPCodelensInlayProvider.java, src/main/java/com/redhat/devtools/intellij/lsp4ij/operations/inlayhint/LSPInlayHintInlayProvider.java
=> fix: duplicate inlay hint

gradle.properties, src/main/resources/META-INF/plugin.xml
chore(skip-release): Prepare for 1.30.0
=> chore(skip-release): Prepare for 1.30.0

build.gradle.kts
=> fix: restore embedded gson to fix project wizard

.github/workflows/nightly.yml, .github/workflows/release.yml
Add a gradle wrapper validation steps for security reasons.
=> chore: add gradle wrapper validation

src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/command/MicroprofileOpenURIAction.java, src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/command/MicroprofileUpdateConfigurationAction.java, src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/java/codeaction/ExtendedCodeAction.java, src/main/java/com/redhat/devtools/intellij/qute/psi/core/command/QuteAction.java, src/main/java/com/redhat/devtools/intellij/qute/psi/core/command/QuteGenerateTemplateAction.java, src/main/java/com/redhat/devtools/intellij/qute/psi/core/command/QuteJavaDefinitionAction.java, src/main/java/com/redhat/devtools/intellij/qute/psi/core/command/QuteOpenURIAction.java, src/main/java/com/redhat/devtools/intellij/qute/psi/core/command/QuteUpdateConfigurationAction.java
feat: Use LSP command action
This PR requires https://github.com/redhat-developer/lsp4ij/pull/37 which provides LSPCommandAction
=> feat: Use LSP command action

build.gradle.kts
This is currently not super useful, until LSP4IJ has been fully approved on the marketplace, making https://plugins.jetbrains.com/api/plugins/23257/updates?channel=nightly&size=1 returning the actual latest value
=> build: fetch latest nightly LSP4IJ version

src/main/resources/META-INF/lsp4ij-quarkus.xml, src/main/resources/META-INF/lsp4ij-qute.xml
feat: remove Qute/Text language for LSP support hover
This PR requires https://github.com/redhat-developer/lsp4ij/pull/45
=> feat: remove Qute/Text language for LSP support hover

.github/workflows/release.yml, gradle.properties
- fix: compile against telemetry 1.1.0, fixes #1301
- build: allow release from a different branch
=> fix: compile against telemetry 1.1.0

src/main/resources/META-INF/plugin.xml
=> build: use 231 as since-build

src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/internal/health/MicroProfileHealthConstants.java, src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/internal/health/java/HealthAnnotationMissingQuickFix.java, src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/internal/health/java/MicroProfileHealthDiagnosticsParticipant.java, src/test/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/health/java/MicroProfileHealthJavaDiagnosticsTest.java
See https://github.com/eclipse/lsp4mp/issues/443
=> feat: add support for @Startup healthcheck diagnostic

src/main/java/com/redhat/devtools/intellij/quarkus/QuarkusPostStartupActivity.java
refactor: use ProjectActivity API
Signed-off-by: azerr azerr@redhat.com
=> refactor: use ProjectActivity API

README.md, build.gradle.kts, gradle.properties, intellij-community/platform/external-system-api/testFramework/src/com/intellij/platform/externalSystem/testFramework/ExternalSystemImportingTestCase.java, intellij-community/platform/external-system-impl/testSrc/com/intellij/openapi/externalSystem/test/JavaCompileTestUtil.kt, intellij-community/platform/external-system-impl/testSrc/com/intellij/openapi/externalSystem/test/JavaExternalSystemImportingTestCase.java, intellij-community/platform/external-system-impl/testSrc/com/intellij/openapi/externalSystem/util/ExternalSystemFileTestUtil.kt, intellij-community/platform/testFramework/extensions/src/com/intellij/testFramework/assertions/PathAssertEx.kt, intellij-community/platform/testFramework/extensions/src/com/intellij/testFramework/assertions/snapshot.kt, intellij-community/plugins/gradle/testSources/org/jetbrains/plugins/gradle/importing/GradleImportingTestCase.java, intellij-community/plugins/gradle/testSources/org/jetbrains/plugins/gradle/importing/TestGradleBuildScriptBuilder.kt, intellij-community/plugins/gradle/tooling-extension-impl/testSources/org/jetbrains/plugins/gradle/tooling/VersionMatcherRule.java, intellij-community/plugins/gradle/tooling-extension-impl/testSources/org/jetbrains/plugins/gradle/tooling/annotation/TargetVersions.java, intellij-community/plugins/gradle/tooling-extension-impl/testSources/org/jetbrains/plugins/gradle/tooling/builder/AbstractModelBuilderTest.java, intellij-community/plugins/gradle/tooling-extension-impl/testSources/org/jetbrains/plugins/gradle/tooling/util/VersionMatcher.java, intellij-community/plugins/maven/testFramework/src/com/intellij/maven/testFramework/MavenImportingTestCase.java, intellij-community/plugins/maven/testFramework/src/com/intellij/maven/testFramework/MavenTestCase.java, intellij-community/plugins/maven/testFramework/src/com/intellij/maven/testFramework/utils/MavenImportingTestCase.kt, pull_intellij_tests.sh
=> build: increase IJ dependency to 2023.2

src/main/resources/META-INF/lsp4ij-quarkus.xml, src/main/resources/META-INF/lsp4ij-qute.xml
fix: remove un-existing LSPDocumentationProvider declaration
=> fix: remove un-existing LSPDocumentationProvider declaration

src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/AbstractAnnotationTypeReferencePropertiesProvider.java, src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/AbstractTypeDeclarationPropertiesProvider.java, src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/internal/core/java/codeaction/JavaCodeActionDefinition.java, src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/internal/core/java/validators/MultiASTVisitor.java, src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/internal/jaxrs/java/DefaultJaxRsInfoProvider.java, src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/internal/jaxrs/java/JaxRsCodeLensParticipant.java, src/main/java/com/redhat/devtools/intellij/quarkus/QuarkusDeploymentSupport.java, src/main/java/com/redhat/devtools/intellij/quarkus/search/QuarkusModuleComponent.java, src/main/java/com/redhat/devtools/intellij/qute/psi/QuteSupportForTemplate.java, src/main/java/com/redhat/devtools/intellij/qute/psi/internal/AbstractQuteExtensionPointRegistry.java, src/main/java/com/redhat/devtools/intellij/qute/psi/internal/extensions/renarde/UriNamespaceResolverSupport.java, src/main/java/com/redhat/devtools/intellij/qute/psi/internal/java/AbstractQuteTemplateLinkCollector.java, src/main/java/com/redhat/devtools/intellij/qute/psi/internal/resolver/AbstractTypeResolver.java, src/main/java/com/redhat/devtools/intellij/qute/psi/internal/template/QuteSupportForTemplateGenerateMissingJavaMemberHandler.java, src/main/java/com/redhat/devtools/intellij/qute/psi/internal/template/TemplateDataLocation.java, src/main/java/com/redhat/devtools/intellij/qute/psi/internal/template/TemplateDataSupport.java, src/main/java/com/redhat/devtools/intellij/qute/psi/internal/template/datamodel/CheckedTemplateSupport.java, src/main/java/com/redhat/devtools/intellij/qute/psi/internal/template/datamodel/DataModelProviderRegistry.java, src/main/java/com/redhat/devtools/intellij/qute/psi/internal/template/datamodel/TemplateDataAnnotationSupport.java, src/main/java/com/redhat/devtools/intellij/qute/psi/internal/template/datamodel/TemplateExtensionAnnotationSupport.java, src/main/java/com/redhat/devtools/intellij/qute/psi/internal/template/datamodel/TemplateFieldSupport.java, src/main/java/com/redhat/devtools/intellij/qute/psi/internal/template/datamodel/TemplateGlobalAnnotationSupport.java, src/main/java/com/redhat/devtools/intellij/qute/psi/internal/template/datamodel/TypeSafeMessageBundlesSupport.java, src/main/java/com/redhat/devtools/intellij/qute/psi/internal/template/resolvedtype/AbstractResolvedJavaTypeFactory.java, src/main/java/com/redhat/devtools/intellij/qute/psi/internal/template/resolvedtype/DefaultResolvedJavaTypeFactory.java, src/main/java/com/redhat/devtools/intellij/qute/psi/template/datamodel/AbstractAnnotationTypeReferenceDataModelProvider.java, src/main/java/com/redhat/devtools/intellij/qute/psi/template/datamodel/AbstractFieldDeclarationTypeReferenceDataModelProvider.java, src/main/java/com/redhat/devtools/intellij/qute/psi/utils/PsiTypeUtils.java
fix: adapt to change in ProcessCanceledException hierarchy in 2024.2
=> fix: adapt to change in ProcessCanceledException hierarchy in 2024.2

src/main/java/com/redhat/devtools/intellij/qute/psi/internal/template/resolvedtype/AbstractResolvedJavaTypeFactory.java
fix: adapt to change in ProcessCanceledException hierarchy in 2024. (2)
=> fix: adapt to change in ProcessCanceledException hierarchy in 2024. (2)

src/main/java/com/redhat/devtools/intellij/quarkus/lsp/QuarkusServer.java, src/main/java/com/redhat/devtools/intellij/qute/lsp/QuteServer.java
fix: adapt the new API of LSP4IJ
=> fix: adapt the new API of LSP4IJ

.github/workflows/itests.yml
=> ci: Updated actions version. Added distribution for setup-java actions.

gradle.properties
chore: Use Qute LS 0.19.0 SNAPSHOT
=> chore: Use Qute LS 0.19.0 SNAPSHOT

projects/qute/projects/maven/qute-record/src/main/java/org/acme/sample/HelloResource.java, src/main/java/com/redhat/devtools/intellij/qute/psi/internal/java/AbstractQuteTemplateLinkCollector.java, src/test/java/com/redhat/devtools/intellij/qute/psi/java/MavenJavaCodeLensTest.java, src/test/java/com/redhat/devtools/intellij/qute/psi/java/MavenJavaDiagnosticsTest.java, src/test/java/com/redhat/devtools/intellij/qute/psi/java/MavenJavaDocumentLinkTest.java
fix: Check if record implement TemplateInstance to provide the support
=> fix: Check if record implements TemplateInstance to provide the support

gradle.properties, src/main/resources/META-INF/plugin.xml
chore(skip-release): Prepare for 2.0.0
=> chore(skip-release): Prepare for 2.0.0

src/main/resources/META-INF/plugin.xml
=> chore(skip-release): Prepare for 2.0.1 release

gradle.properties
chore: Use Qute LS 0.19.2-SNAPSHOT
=> chore: Use Qute LS 0.19.2-SNAPSHOT

src/main/java/com/redhat/devtools/intellij/quarkus/QuarkusPostStartupActivity.java, src/main/java/com/redhat/devtools/intellij/quarkus/json/QuarkusJsonSchemaProjectService.java, src/main/java/com/redhat/devtools/intellij/quarkus/json/QuarkusJsonSchemaProvider.java, src/main/resources/META-INF/plugin-json.xml, src/main/resources/META-INF/plugin.xml, src/test/java/com/redhat/devtools/intellij/quarkus/completion/MavenApplicationYamlCompletionTest.java, src/test/java/com/redhat/devtools/intellij/quarkus/projectWizard/QuarkusModelRegistryTest.java
chore: compatibility with 2024.3
This PR should fix:
=> chore: compatibility with 2024.3

src/main/java/com/redhat/devtools/intellij/quarkus/buildtool/gradle/GradleRunAndDebugProgramRunner.java
chore: don't use internal startRunProfile
This PR the `Internal method usage` problem:
=> chore: don't use internal startRunProfile

src/main/java/com/redhat/devtools/intellij/qute/psi/core/command/QuteGenerateTemplateAction.java, src/main/java/com/redhat/devtools/intellij/qute/psi/core/command/QuteJavaDefinitionAction.java
chore: get Qute LS from command context
=> chore: get Qute LS from command context

gradle.properties
chore: use lsp4mp 0.13.0-SNAPSHOT
=> chore: use lsp4mp 0.13.0-SNAPSHOT

src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/utils/AnnotationUtils.java
=> fix: annotation with enum

src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/utils/AnnotationUtils.java, src/main/java/com/redhat/microprofile/psi/internal/quarkus/core/properties/ConfigPhase.java, src/main/java/com/redhat/microprofile/psi/internal/quarkus/core/properties/QuarkusConfigRootProvider.java, src/main/java/com/redhat/microprofile/psi/internal/quarkus/core/properties/QuarkusCoreProvider.java
fix: support old ConfigPhase.BOOTSRAP
=> fix: support old ConfigPhase.BOOTSRAP

gradle.properties
build: use release of LSP4MP 0.13.0 + Quarkus LS 0.20.0
=> build: use release of LSP4MP 0.13.0 + Quarkus LS 0.20.0

src/main/java/com/redhat/devtools/intellij/quarkus/lsp/QuarkusLanguageClient.java, src/main/java/com/redhat/devtools/intellij/quarkus/lsp/QuarkusServer.java, src/main/java/com/redhat/devtools/intellij/qute/lsp/QuteLanguageClient.java
chore: consume Quarkus LS to benefit with Ollama support
=> chore: consume Quarkus LS to benefit with Ollama support

src/main/resources/META-INF/lsp4ij-qute.xml
=> fix: set Qute language ids.

gradle.properties, src/main/java/com/redhat/devtools/intellij/qute/lang/QuteLanguageSubstitutor.java, src/main/java/com/redhat/devtools/intellij/qute/psi/internal/QuteJavaConstants.java, src/main/java/com/redhat/devtools/intellij/qute/psi/internal/extensions/roq/DataMappingSupport.java, src/main/java/com/redhat/devtools/intellij/qute/psi/internal/extensions/roq/RoqDataModelProvider.java, src/main/java/com/redhat/devtools/intellij/qute/psi/internal/extensions/roq/RoqJavaConstants.java, src/main/java/com/redhat/devtools/intellij/qute/psi/internal/extensions/roq/RoqTemplateRootPathProvider.java, src/main/java/com/redhat/devtools/intellij/qute/psi/internal/extensions/roq/RoqUtils.java, src/main/java/com/redhat/devtools/intellij/qute/psi/internal/extensions/webbundler/WebBundlerJavaConstants.java, src/main/java/com/redhat/devtools/intellij/qute/psi/internal/extensions/webbundler/WebBundlerTemplateRootPathProvider.java, src/main/java/com/redhat/devtools/intellij/qute/psi/internal/template/datamodel/TemplateExtensionAnnotationSupport.java, src/main/java/com/redhat/devtools/intellij/qute/psi/internal/template/rootpath/TemplateRootPathProviderRegistry.java, src/main/java/com/redhat/devtools/intellij/qute/psi/template/rootpath/DefaultTemplateRootPathProvider.java, src/main/java/com/redhat/devtools/intellij/qute/psi/template/rootpath/ITemplateRootPathProvider.java, src/main/java/com/redhat/devtools/intellij/qute/psi/utils/AnnotationUtils.java, src/main/java/com/redhat/devtools/intellij/qute/psi/utils/PsiQuteProjectUtils.java, src/main/resources/META-INF/plugin.xml, src/test/java/com/redhat/devtools/intellij/qute/psi/QuteAssert.java, src/test/java/com/redhat/devtools/intellij/qute/psi/template/TemplateGetDataModelProjectTest.java
=> feat: Initialize roq support

src/main/java/com/redhat/devtools/intellij/qute/psi/internal/template/datamodel/TemplateGlobalAnnotationSupport.java, src/main/resources/META-INF/plugin.xml, src/test/java/com/redhat/devtools/intellij/qute/psi/template/TemplateGetDataModelProjectTest.java
Support for global namespace to have global:X incompletion and avoir having false positive error whenexpression use global namespace.
//cc @ia3andy
=> feat: support for global namespace

src/main/java/com/redhat/devtools/intellij/qute/psi/internal/extensions/webbundler/WebBundlerJavaConstants.java
fix: maven cordinate from Web Bundler.
=> fix: maven cordinate from Web Bundler.

src/main/java/com/redhat/devtools/intellij/quarkus/buildtool/gradle/AbstractGradleToolDelegate.java
The current implementation of task execution in `AbstractGradleToolDelegate` strictly relies on the internals of the External System API. This is not necessary, as there is a correspondingly simple way to execute tasks. 
In addition, some of the used methods will be annotated as `@Internal` and will not be available for use by third-party plugins.
=> fix: use a task execution facade for Gradle task execution

gradle.properties
chore : use Quarkus / Qute LS 0.21.0 release.
=> chore: use Quarkus / Qute LS 0.21.0 release.

.github/workflows/IJ-latest.yml, .github/workflows/IJ.yml, .github/workflows/buildZip.yml, .github/workflows/ci.yml, .github/workflows/nightly.yml, .github/workflows/release.yml
=> build: use Gradle v4

src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/project/MicroProfileConfigPropertyInformation.java
fix: StringIndexOutOfBoundsException
Fixes #1413
=> fix: StringIndexOutOfBoundsException

gradle.properties, src/main/resources/META-INF/plugin.xml
chore(skip-release): Prepare for 2.1.0 release
=> chore(skip-release): Prepare for 2.1.0 release

src/main/java/com/redhat/devtools/intellij/quarkus/json/QuarkusJsonSchemaProjectService.java
fix: compability with 2025.1 eap
=> fix: compability with 2025.1 eap

src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/internal/core/java/ChangeUtil.java, src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/internal/core/java/TextEditConverter.java
=> fix: Removed the Unused method TextEditConverter.convertToTextDocumentEdit(int)

.github/workflows/IJ-latest.yml, .github/workflows/itests.yml, build.gradle.kts, gradle/libs.versions.toml, src/it/java/org/jboss/tools/intellij/quarkus/fixtures/dialogs/project/pages/QuarkusNewProjectFirstPage.java, src/it/java/org/jboss/tools/intellij/quarkus/tests/AbstractQuarkusTest.java, src/it/java/org/jboss/tools/intellij/quarkus/tests/BasicTest.java, src/it/java/org/jboss/tools/intellij/quarkus/utils/XPathDefinitions.java, src/main/java/com/redhat/devtools/intellij/quarkus/QuarkusDeploymentSupport.java, src/main/java/com/redhat/devtools/intellij/quarkus/buildtool/maven/MavenToolDelegate.java, src/main/java/com/redhat/devtools/intellij/quarkus/lang/QuarkusPropertyClassNameCompletionRemover.java, src/main/java/com/redhat/devtools/intellij/quarkus/telemetry/TelemetryManager.java, src/main/resources/META-INF/plugin.xml, src/test/java/com/redhat/devtools/intellij/MavenModuleImportingTestCase.java, src/test/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/MicroProfileForJavaAssert.java, src/test/java/com/redhat/devtools/intellij/quarkus/completion/MavenApplicationPropertiesCompletionTest.java
=> fix: fix unit test and integration test

gradle.properties, gradle/wrapper/gradle-wrapper.properties, gradlew.bat, src/main/java/com/redhat/devtools/intellij/quarkus/QuarkusDeploymentSupport.java, src/main/java/com/redhat/devtools/intellij/quarkus/buildtool/gradle/AbstractGradleToolDelegate.java, src/main/java/com/redhat/devtools/intellij/quarkus/buildtool/maven/MavenToolDelegate.java, src/test/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/GradlePropertiesManagerLocationUsingVertxTest.java, src/test/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/LSP4MPMavenModuleImportingTestCase.java, src/test/java/com/redhat/devtools/intellij/quarkus/completion/MavenApplicationPropertiesCompletionTest.java, src/test/java/com/redhat/microprofile/psi/quarkus/QuarkusMavenModuleImportingTestCase.java
=> fix: fix listQuarkusDependencies build task error popup

src/main/java/com/redhat/devtools/intellij/qute/lsp/QuteLanguageClient.java, src/main/java/com/redhat/devtools/intellij/qute/psi/utils/PsiQuteProjectUtils.java
perf: add Java source file  in 'qute/dataModelChanged' event
=> perf: add Java source file  in 'qute/dataModelChanged' event

src/main/java/com/redhat/devtools/intellij/qute/psi/utils/PsiQuteProjectUtils.java
fix: Read access is allowed from inside read-action only
Fixes #1437
=> fix: Read access is allowed from inside read-action only

gradle.properties
=> build: bump to 2.2.0-SNAPSHOT

src/main/java/com/redhat/devtools/intellij/qute/psi/core/inspections/QuteUndefinedSectionTagInspection.java, src/main/java/com/redhat/devtools/intellij/qute/settings/QuteInspectionsInfo.java, src/main/java/com/redhat/devtools/intellij/qute/settings/UserDefinedQuteSettings.java, src/main/resources/META-INF/lsp4ij-qute.xml, src/main/resources/META-INF/plugin.xml, src/main/resources/inspectionDescriptions/QuteUndefinedSectionTag.htm, src/main/resources/messages/QuteBundle.properties
feat: add undefined section severity settings
//cc @ia3andy
=> feat: add undefined section severity settings

gradle.properties
feat: use Quarkus / Qute LS 0.22.1-SNAPSHOT
=> feat: use Quarkus / Qute LS 0.22.1-SNAPSHOT

src/main/java/com/redhat/devtools/intellij/qute/run/QuteDebugAdapterDescriptorFactory.java
fix: allow setting Qute breakpoint only for Qute file
=> fix: allow setting Qute breakpoint only for Qute file

gradle.properties, src/main/java/com/redhat/devtools/intellij/quarkus/run/QuarkusRunConfigurationManager.java, src/main/resources/META-INF/plugin.xml
=> build: bump to 2.3.0-SNAPSHOT

src/main/java/com/redhat/devtools/intellij/qute/run/QuteConfigurationType.java
feat: Rename to "Remote Qute Debug"
//cc @ia3andy
=> feat: Rename to "Remote Qute Debug"
