- src/main/resources/quarkus.xml
Update Quarkus Runtime to 1.4.2.Final (#71)
Tested on localhost.
Please review @jeffmaury 
**Displayed value:**
**Download works:**
> Update Quarkus Runtime to 1.4.2.Final (#71)

- projects/gradle/config-properties/gradle.properties
- projects/gradle/config-properties/src/main/resources/META-INF/resources/index.html
- projects/gradle/microprofile-context-propagation/gradle.properties
- projects/gradle/microprofile-context-propagation/src/main/resources/META-INF/resources/index.html
- projects/gradle/microprofile-lra/gradle.properties
- projects/gradle/microprofile-lra/src/main/resources/META-INF/resources/index.html
- projects/gradle/microprofile-openapi/gradle.properties
- projects/gradle/microprofile-openapi/src/main/resources/META-INF/resources/index.html
- projects/gradle/using-vertx/gradle.properties
- projects/gradle/using-vertx/src/main/resources/META-INF/resources/index.html
- src/main/resources/quarkus.xml
Fixes #144
According to my manager @psrna we should deliver the newest version of runtime to our customers. I  upgraded the runtime to the newest version - 1.5.1.Final. If we merge this PR, we can make release of this plugin with newest runtime next week. Please review @jeffmaury
> Update the plugin runtime to version 1.5.2.Final

- gradle.properties
- src/main/java/com/redhat/devtools/intellij/quarkus/lsp4ij/operations/completion/CompletionProposalTools.java
- src/main/java/com/redhat/devtools/intellij/quarkus/lsp4ij/operations/completion/LSCompletionProposal.java
- src/main/java/com/redhat/devtools/intellij/quarkus/lsp4ij/operations/completion/LSContentAssistProcessor.java
- src/main/java/com/redhat/devtools/intellij/quarkus/lsp4ij/operations/completion/LSIncompleteCompletionProposal.java
Fixes #152
1. Create a Quarkus project with smallrye-fault-tolerance.
2. Add `@Retry` annotation to one of your JAX-RS method
3. Set the cursor after the y from `@Retry` and ask for code completion, you should see the snippet
4. Create another Java method and import `Stream` ask for code completion on Stream. and those snippet should have disappeared.
> Filter completion proposal

- projects/gradle/config-properties/gradle.properties
- projects/gradle/config-properties/src/main/resources/META-INF/resources/index.html
- projects/gradle/microprofile-context-propagation/gradle.properties
- projects/gradle/microprofile-context-propagation/src/main/resources/META-INF/resources/index.html
- projects/gradle/microprofile-lra/gradle.properties
- projects/gradle/microprofile-lra/src/main/resources/META-INF/resources/index.html
- projects/gradle/microprofile-openapi/gradle.properties
- projects/gradle/microprofile-openapi/src/main/resources/META-INF/resources/index.html
- projects/gradle/using-vertx/gradle.properties
- projects/gradle/using-vertx/src/main/resources/META-INF/resources/index.html
- src/main/resources/quarkus.xml
Fixes #202
Tested on localhost, new version of runtime is available and downloaded without any issue using the Quarkus plugin.
> Update the plugin runtime to version 1.7.0.Final

- projects/gradle/config-properties/gradle.properties
- projects/gradle/config-properties/src/main/resources/META-INF/resources/index.html
- projects/gradle/microprofile-context-propagation/gradle.properties
- projects/gradle/microprofile-context-propagation/src/main/resources/META-INF/resources/index.html
- projects/gradle/microprofile-lra/gradle.properties
- projects/gradle/microprofile-lra/src/main/resources/META-INF/resources/index.html
- projects/gradle/microprofile-openapi/gradle.properties
- projects/gradle/microprofile-openapi/src/main/resources/META-INF/resources/index.html
- projects/gradle/using-vertx/gradle.properties
- projects/gradle/using-vertx/src/main/resources/META-INF/resources/index.html
- src/main/resources/quarkus.xml
Fixes #218
Tested on localhost, new version of runtime is available and downloaded without any issue using the Quarkus plugin.
> Update the plugin runtime to version 1.7.1.Final

- projects/gradle/config-properties/gradle.properties
- projects/gradle/config-properties/src/main/resources/META-INF/resources/index.html
- projects/gradle/microprofile-context-propagation/gradle.properties
- projects/gradle/microprofile-context-propagation/src/main/resources/META-INF/resources/index.html
- projects/gradle/microprofile-lra/gradle.properties
- projects/gradle/microprofile-lra/src/main/resources/META-INF/resources/index.html
- projects/gradle/microprofile-openapi/gradle.properties
- projects/gradle/microprofile-openapi/src/main/resources/META-INF/resources/index.html
- projects/gradle/using-vertx/gradle.properties
- projects/gradle/using-vertx/src/main/resources/META-INF/resources/index.html
- src/main/resources/quarkus.xml
Fixes #226
Tested on localhost, new version of runtime is available and downloaded without any issue using the Quarkus plugin.
> Update the plugin runtime to version 1.8.0.Final

- build.gradle
- src/it/java/org/jboss/tools/intellij/quarkus/BasicTests.java
- src/it/java/org/jboss/tools/intellij/quarkus/fixtures/dialogs/IdeFatalErrorsDialogFixture.java
- src/it/java/org/jboss/tools/intellij/quarkus/fixtures/dialogs/NewProjectDialogFixture.java
- src/it/java/org/jboss/tools/intellij/quarkus/fixtures/dialogs/TipOfTheDayDialogFixture.java
- src/it/java/org/jboss/tools/intellij/quarkus/fixtures/dialogs/WelcomeFrameDialogFixture.java
- src/it/java/org/jboss/tools/intellij/quarkus/fixtures/mainIdeWindow/IdeStatusBarFixture.java
- src/it/java/org/jboss/tools/intellij/quarkus/fixtures/mainIdeWindow/ToolWindowsPaneFixture.java
- src/it/java/org/jboss/tools/intellij/quarkus/fixtures/other/ActionLinkFixture.java
- src/it/java/org/jboss/tools/intellij/quarkus/utils/BuildUtils.java
- src/it/java/org/jboss/tools/intellij/quarkus/utils/GlobalUtils.java
- src/it/java/org/jboss/tools/intellij/quarkus/utils/HelperUtils.java
- src/it/java/org/jboss/tools/intellij/quarkus/utils/NewProjectDialogUtils.java
- src/it/java/org/jboss/tools/intellij/quarkus/utils/QuarkusUtils.java
Fixes: #216
Please review @odockal @jkopriva
> Add basic UI test that creates new Quarkus project and builds it using maven

- src/it/java/org/jboss/tools/intellij/quarkus/BasicTests.java
- src/it/java/org/jboss/tools/intellij/quarkus/utils/GlobalUtils.java
Fix the bug that makes all UI tests fail to start when starting the IDE takes longer
Fixes #269
Please review @jrichter1 @jeffmaury 
@jrichter1 we have discussed this issue before - is this the solution you were talking about? Do you think that the timeout 5 minutes is acceptable for downloading any supported IntelliJ version and start the IDE on our infrastructure?
> Fix the bug that makes all UI tests fail to start when starting the IDE takes longer

- src/it/java/org/jboss/tools/intellij/quarkus/utils/GlobalUtils.java
- Remote-Robot itself does not offer method for taking screenshot (reported: https://github.com/JetBrains/intellij-ui-test-robot/issues/18, will be probably implemented in the future)
- for now I extend GlobalUtils to contain method for taking screenshots
Fixes #345
Please review @jrichter1 @jeffmaury
> Add method to take fullscreen screenshots during running the UI tests

- src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/internal/core/project/YamlConfigSource.java
> fix: Use SafeConstructor when creating new Yaml (CVE-2021-25738)

- build.gradle
- src/it/java/org/jboss/tools/intellij/quarkus/tests/BasicTest.java
> fix: Use test library 0.0.9

- src/main/java/com/redhat/devtools/intellij/quarkus/run/QuarkusRunContext.java
This fixes the following exception, happening when a project is opened:
```java
java.lang.NullPointerException: Cannot invoke "javax.swing.JComponent.getClientProperty(Object)" because the return value of "com.intellij.execution.ui.RunContentDescriptor.getComponent()" is null
at com.redhat.devtools.intellij.quarkus.run.QuarkusRunContext.getContext(QuarkusRunContext.java:34)
at com.redhat.devtools.intellij.quarkus.run.QuarkusDevActionGroup.update(QuarkusDevActionGroup.java:32)
```
> fix: NPE when retrieving the QuarkusRunContext

- .github/workflows/changelog.yml
- .github/workflows/conventionalCheck.yml
- .github/workflows/release.yml
Hi!
Following the [GH Action Security Hardening](https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions) guide we should use the commit SHA instead of the `branch` or `tag` for any third-party untrusted action.
This PR was submitted by a script.
> chore: Pin 3rd-party actions to SHA1

- src/main/java/com/redhat/devtools/intellij/quarkus/lsp4ij/DocumentContentSynchronizer.java
Synchronize correctly the IJ document with the LSP server document.
When you type fastly some content inside the editor content (ex : you open an html file to consume the Qute LS and you type a lot of spaces (let's press space key to generate 20 characters for instance), the IJ document is desynchronized with the LSP server document.
One this desynchronization occurs, the Qute support is unusable (ex : the validation report bad error ranges). 
This PR fixes this problem by avoiding lossing document change event.
Here a demo with the problem in master:
Here the same demo with this PR which should fix this issue:
> fix: Synchronize correctly the IJ document with the LSP server document

- src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/internal/jaxrs/java/JaxRsCodeLensParticipant.java
Codelens URL JAX-RS slows down the Java editor
Fixes #790
> fix: Codelens URL JAX-RS slows down the Java editor

- src/main/java/com/redhat/devtools/intellij/quarkus/lsp/QuarkusServer.java
Don't show quickfix for disable validation for application.properties since IJ quarkus doesn't support it.
This PR remove the quickfix to ignore validation since IJ Quarkus cannot support it
> fix: Don't show quickfix for disable validation for application.properties since IJ quarkus doesn't support it.

- projects/lsp4mp/projects/maven/open-liberty/src/main/java/com/demo/rest/IncorrectScopeJakarta.java
- src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/internal/core/java/codeaction/CodeActionHandler.java
- src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/internal/metrics/MicroProfileMetricsConstants.java
- src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/internal/metrics/java/ApplicationScopedAnnotationMissingQuickFix.java
- src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/internal/metrics/java/MicroProfileMetricsDiagnosticsParticipant.java
- src/test/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/metrics/java/MicroProfileMetricsJavaDiagnosticsTest.java
Port of https://github.com/eclipse/lsp4mp/commit/874375de68fa06bc9b610b46e15578bf4733c25a to IDEA
Part of https://github.com/redhat-developer/intellij-quarkus/issues/806 and https://github.com/redhat-developer/intellij-quarkus/issues/803
Fixes context.getProject() returning null when calling CodeActionHandler.resolveCodeAction
> feat: Support jakarta namespace with microprofile metrics

- src/main/java/com/redhat/devtools/intellij/quarkus/lsp4ij/LSPIJUtils.java
- src/main/java/com/redhat/devtools/intellij/quarkus/lsp4ij/operations/diagnostics/LSPDiagnosticsForServer.java
Consume LSP request codeActions only if language server supports it
Today we use LSP4IJ with MicroProfile and Qute LS which have code actions capability. But if the language server has not the codeAction capability it consumes the codeActions request which throws an UnsuportedOperationException.
This PR check if the language server has the code action capability. 
See https://github.com/redhat-developer/intellij-quarkus/pull/819#discussion_r1179687022
> fix: consume LSP request codeActions only if language server supports it

- src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/internal/core/ls/PsiUtilsLSImpl.java
Calling `VfsUtil.findFileByURL` fails for WSL files as it calls [`VfsUtilCore.convertFromUrl`](https://github.com/JetBrains/intellij-community/blob/0d4a74d99cd22d1f092ff67480537c214497ac9f/platform/core-api/src/com/intellij/openapi/vfs/VfsUtilCore.java#L491-L512), which [strips leading `//` ](https://github.com/JetBrains/intellij-community/blob/0d4a74d99cd22d1f092ff67480537c214497ac9f/platform/core-api/src/com/intellij/openapi/vfs/VfsUtilCore.java#L508-L511) from `file:////wsl$` uris, into `file://wsl$`. 
This bug was reported upstream as https://youtrack.jetbrains.com/issue/IDEA-83879/OpenAPI-com.intellij.openapi.vfs.VfsUtilconvertFromUrl-strips-volume-identifiers-on-Windows. 
The fix is to call `VirtualFileManager.getInstance().findFileByUrl(uri);` instead, as mentioned in the upstream …
> fix: make sure files can be found when running on WSL

- src/main/java/com/redhat/devtools/intellij/qute/psi/utils/AnnotationUtils.java
Simple fix to prevent NPE in qute's AnnotationUtils.isMatchAnnotation, but I'm missing some context, so have no matching unit test.
Fixes #847
> fix: Prevent NPE in qute's AnnotationUtils.isMatchAnnotation

- src/main/java/com/redhat/devtools/intellij/qute/psi/internal/template/QuarkusIntegrationForQute.java
fix: Collect Qute user tags from templates/tags of dependency JARS (#872)
Fixes #872
This PRs provides the capability to collect Qute user tags from JAR Renarde:
> fix: Collect Qute user tags from templates/tags of dependency JARS (#872)

- src/main/resources/META-INF/lsp.xml
fix: Typo 'Quakus' in the Quarkus language server description (#883)
Fixes #883
> fix: Typo 'Quakus' in the Quarkus language server description (#883)

- src/main/java/com/redhat/devtools/intellij/lsp4ij/console/LSPConsoleToolWindowFactory.java
Keep LSP console displayed when IJ is indexing, by making LSPConsoleToolWindowFactory implement DumbAware
See https://plugins.jetbrains.com/docs/intellij/tool-windows.html#contents-tabs
> fix: LSP console shouldn't be hidden when IJ is indexing

- build.gradle
Failed test assertions should now be available directly from the gradle build output, e.g.:
```
./gradlew test --tests '*TemplateGetDataModelProjectTest'
> Configure project :
[gradle-intellij-plugin :] Gradle IntelliJ Plugin is outdated: 1.10.1. Update `org.jetbrains.intellij` to: 1.13.3
> Task :test
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.intellij.util.ref.DebugReflectionUtil (file:/Users/fbricon/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/2020.3/22cef0fc611e4b9642a48bc955b2b7aacb13bd4d/ideaIC-2020.3/lib/platform-impl.jar) to field …
```
> build: show failed assertions in gradle builds

- src/main/java/com/redhat/devtools/intellij/lsp4ij/operations/hover/LSPPsiElementForHover.java
- src/main/java/com/redhat/devtools/intellij/lsp4ij/operations/hover/LSPTextHover.java
fix: Editor is already disposed in LSP hover operation (#914)
Fixes #914
> fix: Editor is already disposed in LSP hover operation (#914)

- README.md
Add instructions to workaround https://github.com/redhat-developer/intellij-quarkus/pull/922#issuecomment-1580893652, caused by https://github.com/actions/upload-artifact/issues/39
> docs: add instructions about double-zipped plugin

- src/main/java/com/redhat/devtools/intellij/lsp4ij/LSPIJUtils.java
Fixes #941
API says `PsiDocumentManager.getDocument(file)` can return `null`, so it should be guarded against.
As to why it returns `null` in some cases, I have no idea.
> fix: ensure document is not null in LSPIJUtils.toLocation

- src/main/java/com/redhat/devtools/intellij/lsp4ij/operations/hover/LSPTextHover.java
Fixes #960 
We ensure both element and originalElement refer to the same file, so it doesn't generate an exception.
No tests since the exception was just logged
> fix: ensure LSPTextHover.generateDoc ignores elements from different files

- .github/workflows/IJ.yml
- src/main/java/com/redhat/devtools/intellij/lsp4ij/LSPIJUtils.java
- src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/classpath/ClasspathResourceChangedListener.java
- src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/classpath/ClasspathResourceChangedManager.java
- src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/classpath/ClasspathResourceChangedNotifier.java
- src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/project/PsiMicroProfileProject.java
- src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/project/PsiMicroProfileProjectManager.java
- src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/internal/core/ls/PsiUtilsLSImpl.java
- src/main/java/com/redhat/devtools/intellij/quarkus/QuarkusPostStartupActivity.java
- src/main/java/com/redhat/devtools/intellij/quarkus/QuarkusProjectService.java
- src/main/java/com/redhat/devtools/intellij/quarkus/lsp/QuarkusLanguageClient.java
- src/main/java/com/redhat/devtools/intellij/qute/lsp/QuteLanguageClient.java
- src/main/resources/META-INF/plugin.xml
- src/test/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/MicroProfileMavenProjectName.java
- src/test/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/PropertiesManagerClassPathKindTest.java
- src/test/java/com/redhat/devtools/intellij/quarkus/module/QuarkusModelRegistryTest.java
- src/test/java/com/redhat/devtools/intellij/quarkus/run/QuarkusRunContextTest.java
- src/test/java/com/redhat/microprofile/psi/quarkus/QuarkusMavenProjectName.java
fix: debounce classpath/source change events (#916)
Fixes #916
Fixes #958
Signed-off-by: azerr <azerr@redhat.com>
> fix: debounce classpath/source change events

- src/main/java/com/redhat/devtools/intellij/quarkus/module/QuarkusCodeEndpointChooserStep.java
- src/main/java/com/redhat/devtools/intellij/quarkus/module/QuarkusExtensionsStep.java
- src/main/java/com/redhat/devtools/intellij/quarkus/module/QuarkusModuleInfoStep.java
> fix: set proper borders / alignment in quarkus wizard

- gradle.properties
- src/main/resources/META-INF/plugin.xml
> chore(skip-release): Prepare for 1.21.0

- src/main/resources/META-INF/plugin.xml
> fix: use wrong Red-Hat name for vendor, to make JetBrains marketplace happy

- src/main/java/com/redhat/devtools/intellij/lsp4ij/operations/completion/LSIncompleteCompletionProposal.java
- src/main/java/com/redhat/devtools/intellij/lsp4ij/ui/IconMapper.java
- src/main/resources/images/expui/fileTypes/text.svg
- src/main/resources/images/expui/fileTypes/text_dark.svg
- src/main/resources/images/nodes/template.svg
- src/test/java/com/redhat/devtools/intellij/lsp4ij/ui/IconMapperTest.java
Provides icons for completion results.
"recent" icons from IJ were copied over to work with older IJ versions still supported.
Example for application.properties completion:
> feat: map LSP4J CompletionItemKinds to Intellij IDEA icons

- src/main/java/com/redhat/devtools/intellij/qute/psi/internal/template/TemplateDataCollector.java
Fixed potential NPEs in TemplateDataCollector.visitParameter
Fixes #987
> fix: prevent NPE when invalid data is injected into Qute template

- src/main/java/com/redhat/devtools/intellij/quarkus/module/QuarkusExtensionsStep.java
- (de)select extension on double-click in extensions treeview
- deselect extension on double-click in selected extensions list
- deselect selection of extension on DELETE or BACKSPACE keypress in selected extensions list
> feat: improve extension (de)selection in Quarkus wizard

- build.gradle
- src/main/java/com/redhat/devtools/intellij/lsp4ij/LanguageServiceAccessor.java
In IJ 2023.1.3, 
- open https://github.com/ia3andy/quarkus-blast/
- open src/main/resources/templates/GameController/game.html
- Ctrl+hover over https://github.com/ia3andy/quarkus-blast/blob/main/src/main/resources/templates/GameController/game.html#L1
console is littered with stacktraces of JobCancellationException:
```
2023-07-07 10:14:38,811 [ 135606]   WARN - com.redhat.devtools.intellij.lsp4ij.LanguageServiceAccessor - kotlinx.coroutines.JobCancellationException: StandaloneCoroutine was cancelled; job=StandaloneCoroutine{Cancelling}@570e68cb
com.intellij.openapi.progress.JobCanceledException: kotlinx.coroutines.JobCancellationException: StandaloneCoroutine was cancelled; job=StandaloneCoroutine{Cancelling}@570e68cb
at com.intellij.openapi.progress.Cancellation.checkCancelled(Cancellat …
```
> fix: avoid polluting logs with ProcessCanceledException stacktraces on Ctrl+hover

- projects/lsp4mp/projects/maven/config-quickstart/src/main/java/org/acme/config/DefaultValueListResource.java
- projects/lsp4mp/projects/maven/config-quickstart/src/main/java/org/acme/config/DefaultValueResource.java
- src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/internal/config/java/MicroProfileConfigASTValidator.java
- src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/internal/config/java/MicroProfileConfigErrorCode.java
- src/test/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/config/java/MicroProfileConfigJavaDiagnosticsTest.java
- src/test/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/config/properties/ConfigItemIntBoolDefaultValueTest.java
- src/test/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/config/properties/MicroProfileConfigPropertyTest.java
Port of https://github.com/eclipse/lsp4mp/commit/a95a3f719ee88a61072b6df0eadf7a06b391bd89
Part of #806
> feat: Validate defaultValue for lists and arrays

- src/main/resources/META-INF/plugin.xml
Port of https://github.com/eclipse/lsp4mp/commit/caf91c68e7f2fe27072f1f947e3c5476f3289d8f
Part of #806
To test, open a non-quarkus project (eg. Lemminx), add an `src/main/resources/application.properties` file and trigger completion on an empty line. config_ordinal should not appear.
> fix: Ensure config_ordinal only appears in MicroProfile projects

- src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/JavaEEImplicitUsageProvider.java
- src/main/java/com/redhat/devtools/intellij/qute/psi/internal/extensions/renarde/RenardeImplicitUsageProvider.java
- src/main/java/com/redhat/microprofile/psi/internal/quarkus/renarde/java/RenardeUtils.java
- src/main/resources/META-INF/lsp4ij-quarkus.xml
- src/main/resources/META-INF/lsp4ij-qute.xml
JAX-RS controller:
Renarde controller:
> feat: mark JAX-RS and Renarde endpoints as implicitly used

- src/main/java/com/redhat/devtools/intellij/lsp4ij/operations/inlayhint/LSPInlayHintInlayProvider.java
Qute Inlay hints are displayed with a double "::"
The non-command part of the inlay hint was added twice. This PR fixes it:
> fix: remove extra colon in inlay hints

- src/main/java/com/redhat/devtools/intellij/lsp4ij/internal/SupportedFeatures.java
- src/main/java/com/redhat/devtools/intellij/lsp4ij/operations/completion/LSContentAssistProcessor.java
- src/main/java/com/redhat/devtools/intellij/lsp4ij/operations/completion/LSIncompleteCompletionProposal.java
- src/main/java/com/redhat/devtools/intellij/lsp4ij/operations/completion/SnippetTemplateFactory.java
- src/main/java/com/redhat/devtools/intellij/lsp4ij/operations/completion/SnippetTemplateLoader.java
- src/main/java/com/redhat/devtools/intellij/lsp4ij/operations/completion/snippet/Location.java
- src/main/java/com/redhat/devtools/intellij/lsp4ij/operations/completion/snippet/LspSnippetHandler.java
- src/main/java/com/redhat/devtools/intellij/lsp4ij/operations/completion/snippet/LspSnippetParser.java
- src/main/java/com/redhat/devtools/intellij/lsp4ij/operations/completion/snippet/ParseException.java
- src/test/java/com/redhat/devtools/intellij/lsp4ij/operations/completion/snippet/AdvancedTest.java
- src/test/java/com/redhat/devtools/intellij/lsp4ij/operations/completion/snippet/ChoiceTest.java
- src/test/java/com/redhat/devtools/intellij/lsp4ij/operations/completion/snippet/LspSnippetAssert.java
- src/test/java/com/redhat/devtools/intellij/lsp4ij/operations/completion/snippet/PlaceholderTest.java
- src/test/java/com/redhat/devtools/intellij/lsp4ij/operations/completion/snippet/TabstopTest.java
- src/test/java/com/redhat/devtools/intellij/lsp4ij/operations/completion/snippet/TextTest.java
- src/test/java/com/redhat/devtools/intellij/lsp4ij/operations/completion/snippet/VariableTest.java
- src/test/java/com/redhat/devtools/intellij/lsp4ij/operations/completion/snippet/handler/ChoiceNode.java
- src/test/java/com/redhat/devtools/intellij/lsp4ij/operations/completion/snippet/handler/LspSnippetHandlerImpl.java
- src/test/java/com/redhat/devtools/intellij/lsp4ij/operations/completion/snippet/handler/LspSnippetNode.java
- src/test/java/com/redhat/devtools/intellij/lsp4ij/operations/completion/snippet/handler/PlaceholderNode.java
- src/test/java/com/redhat/devtools/intellij/lsp4ij/operations/completion/snippet/handler/TabstopNode.java
- src/test/java/com/redhat/devtools/intellij/lsp4ij/operations/completion/snippet/handler/TextNode.java
- src/test/java/com/redhat/devtools/intellij/lsp4ij/operations/completion/snippet/handler/VariableNode.java
feat: Improve completion with snippet support (#786)
Fixes #786
Fixes #975
> feat: Improve completion with snippet support (#786)

- src/main/java/com/redhat/devtools/intellij/lsp4ij/operations/completion/LSContentAssistProcessor.java
feat: provide completion support while indexing process
This PR provides the capability to benefit with completion support while the indexing process. For application.properties it is not interesting because it requires to compute properties from Java files (in this case properties are available only when Java files are indexing) but it is interesting for Qute template section completion.
> feat: provide completion support while indexing process

- src/main/java/com/redhat/devtools/intellij/lsp4ij/operations/completion/LSPCompletionContributor.java
- src/main/java/com/redhat/devtools/intellij/qute/psi/internal/template/JavaTypesSearch.java
fix: Freeze on parameter declaration completion (#1015)
Fixes #1015
It should be fast if you declare the package (ex : `{@java.lang.|`) and little slow if you type directly the class without package (ex : `{@Str|}`. See the following demo:
Perhaps it is slow because we return too many items? But it is now useable.
> fix: Freeze on parameter declaration completion (#1015)

- src/main/resources/META-INF/lsp4ij-quarkus.xml
- src/main/resources/META-INF/lsp4ij.xml
fix: No display name is specified for configurable c.r.d.i.lsp4ij.settings.LanguageServerListConfigurable in xml file (#1030)
Fixes #1030
> fix: No display name is specified for configurable c.r.d.i.lsp4ij.settings.LanguageServerListConfigurable in xml file

- src/main/java/com/redhat/devtools/intellij/lsp4ij/LSPIJUtils.java
- JDK classes use a different URI protocol (`jrt:`)
- Don't use PsiNameIdentifierOwner.getNameIdentifier().getNavigationElement() as it opens the .class file instead of the source, if available
Fixes #1063
> fix: go-to-definition and inlay hint links for JDK classes

- src/main/java/com/redhat/devtools/intellij/lsp4ij/LanguageServerWrapper.java
- src/main/java/com/redhat/devtools/intellij/lsp4ij/console/actions/AutoFoldingAction.java
- src/main/java/com/redhat/devtools/intellij/lsp4ij/console/explorer/LanguageServerExplorer.java
- src/main/java/com/redhat/devtools/intellij/lsp4ij/console/explorer/LanguageServerProcessTreeNode.java
- src/main/java/com/redhat/devtools/intellij/lsp4ij/console/explorer/actions/CopyStartServerCommandAction.java
- src/main/java/com/redhat/devtools/intellij/lsp4ij/console/explorer/actions/PauseServerAction.java
- src/main/java/com/redhat/devtools/intellij/lsp4ij/console/explorer/actions/RestartServerAction.java
- src/main/java/com/redhat/devtools/intellij/lsp4ij/console/explorer/actions/TreeAction.java
- src/main/resources/META-INF/lsp4ij.xml
- src/main/resources/messages/LanguageServerBundle.properties
This PR improve the stop action from the LSP explorer console:
* `Stop `: this action now stop the language server and disable it. To re-enable it you must execute again the Restart action
* `Pause`: only available in dev mode, it stop the language server process. If you type something in the editor, a new language server (new process) will be restarted (same behavior than the old stop action).
> feat: provide a stop process action (dev mode) in the console

- src/main/java/com/redhat/devtools/intellij/lsp4ij/client/LSPCompletableFuture.java
Don't log IndexNotReadyException / ReadAction.CannotReadException error when attempt is not reached
> fix: don't log IndexNotReadyException / ReadAction.CannotReadException error when attempt is not reached

- src/main/java/com/redhat/devtools/intellij/lsp4ij/DocumentContentSynchronizer.java
- src/main/java/com/redhat/devtools/intellij/lsp4ij/LanguageServerWrapper.java
fix: IllegalStateException: Synchronizer should apply to only a single document, which is the one it was instantiated for
Fixes #752
I spend so many times to reproduce the problem without success (I have tried to change git branch to reload the document, I have tried to change encoding to try to change the document instance, etc, I cannot reproduce the problem)
I created a PR where:
* I removed the check of teh document instance
* I get the document from the virtual file when I need to add a document listener (when the language server must be restarted with already opened files) and when I remove the listener from the document to be sure that we work with the document from virtual file and not with a document which could be unused (which usecases does that?)
> fix: IllegalStateException: Synchronizer should apply to only a single document, which is the one it was instantiated for

- README.md
- gradle.properties
- src/main/resources/META-INF/plugin.xml
> chore(skip-release): Prepare for 1.24.0

- src/main/java/com/redhat/devtools/intellij/quarkus/QuarkusModuleUtil.java
- src/main/java/com/redhat/devtools/intellij/quarkus/QuarkusProjectService.java
> fix: Check if project or modules aren't disposed

- src/main/java/com/redhat/devtools/intellij/lsp4ij/console/LSPConsoleToolWindowPanel.java
- src/main/java/com/redhat/devtools/intellij/lsp4ij/settings/UserDefinedLanguageServerSettings.java
Fixes #1062
Since the settings are opened in a modal window, no need to synchronize console view changes -> settings page
> fix: synchronize LSP console trace level with settings page

- src/main/java/com/redhat/devtools/intellij/lsp4ij/LanguageServerItem.java
- src/main/java/com/redhat/devtools/intellij/lsp4ij/LanguageServiceAccessor.java
- src/main/java/com/redhat/devtools/intellij/lsp4ij/client/LSPCompletableFuture.java
- src/main/java/com/redhat/devtools/intellij/lsp4ij/internal/CancellationSupport.java
- src/main/java/com/redhat/devtools/intellij/lsp4ij/operations/codelens/LSPCodelensInlayProvider.java
- src/main/java/com/redhat/devtools/intellij/lsp4ij/operations/completion/LSPCompletionContributor.java
- src/main/java/com/redhat/devtools/intellij/lsp4ij/operations/documentLink/LSPDocumentLinkAnnotator.java
- src/main/java/com/redhat/devtools/intellij/lsp4ij/operations/highlight/LSPHighlightUsagesHandlerFactory.java
- src/main/java/com/redhat/devtools/intellij/lsp4ij/operations/hover/LSPTextHover.java
- src/main/java/com/redhat/devtools/intellij/lsp4ij/operations/inlayhint/LSPInlayHintInlayProvider.java
- src/main/java/com/redhat/devtools/intellij/lsp4ij/operations/navigation/LSPGotoDeclarationHandler.java
perf: LSP cancellation support
Fixes #791
> perf: LSP cancellation support

- src/main/java/com/redhat/devtools/intellij/quarkus/QuarkusConstants.java
- src/main/java/com/redhat/devtools/intellij/quarkus/psi/internal/QuarkusBuildImplicitUsageProvider.java
- src/main/resources/META-INF/lsp4ij-quarkus.xml
fixes #1095 
Before:
After:
@gastaldi  IJ automatically finds usages in .dot file
> feat: mark @BuildStep-annotated methods as implicitly used

- src/main/java/com/redhat/devtools/intellij/quarkus/javadoc/JavadocContentAccess.java
> fix: check type before casting to PsiDocCommentOwner during hover

- src/main/java/com/redhat/devtools/intellij/lsp4ij/client/CoalesceByKey.java
- src/main/java/com/redhat/devtools/intellij/lsp4ij/client/IndexAwareLanguageClient.java
- src/main/java/com/redhat/devtools/intellij/lsp4ij/client/LSPCompletableFuture.java
- src/main/java/com/redhat/devtools/intellij/lsp4ij/operations/diagnostics/LSPDiagnosticHandler.java
- src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/classpath/ClasspathResourceChangedNotifier.java
- src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/internal/jaxrs/java/DefaultJaxRsInfoProvider.java
- src/main/java/com/redhat/devtools/intellij/quarkus/lsp/QuarkusLanguageClient.java
- src/main/java/com/redhat/devtools/intellij/qute/lsp/QuteLanguageClient.java
LSPDiagnosticHandler](fix: Too many non-blocking read actions submitted at once in LSPDiagnosticHandler
Fixes #1089
> fix: Too many non-blocking read actions submitted at once in LSPDiagnosticHandler

- src/main/java/com/redhat/devtools/intellij/lsp4ij/LSPIJUtils.java
fix: PluginException: Range must be inside element being annotated
Fixes #1087
> fix: PluginException: Range must be inside element being annotated

- src/main/java/com/redhat/microprofile/psi/internal/quarkus/core/properties/QuarkusConfigMappingProvider.java
> fix: prevent StackOverflowError in QuarkusConfigMappingProvider.populateConfigObject

- src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/internal/config/properties/MicroProfileConfigPropertyProvider.java
Fixes #1118 
@angelozerr what should happen if neither sourceField nor sourceMethod can be found? Should we stop processing for that javaElement?
> fix: allow records as configuration holder

- src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/inspections/AbstractDelegateInspectionWithExcludedProperties.java
- src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/inspections/MicroProfilePropertiesUnassignedInspection.java
- src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/inspections/MicroProfilePropertiesUnknownInspection.java
- src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/settings/MicroProfileInspectionsInfo.java
- src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/settings/UserDefinedMicroProfileSettings.java
- src/main/resources/META-INF/lsp4ij-quarkus.xml
- src/main/resources/inspectionDescriptions/MicroProfilePropertiesUnassigned.html
- src/main/resources/messages/MicroProfileBundle.properties
Starting with excluded unknown properties
Unassigned properties in Java files
> feat: support for excluding properties from validation

- src/main/java/com/redhat/devtools/intellij/lsp4ij/internal/CancellationUtil.java
- src/main/java/com/redhat/devtools/intellij/lsp4ij/operations/documentation/LSPTextHoverForFile.java
- src/main/java/com/redhat/devtools/intellij/lsp4ij/operations/navigation/LSPGotoDeclarationHandler.java
fix: ResponseErrorException when Ctrl+Hover due to cancellation
Fixes #1136
> fix: ResponseErrorException when Ctrl+Hover due to cancellation

- src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/JavaEEImplicitUsageProvider.java
fixes #1134 
See https://github.com/quarkusio/quarkus-quickstarts/blob/main/reactive-routes-quickstart/src/main/java/org/acme/reactive/routes/MyRouteRegistar.java#L11:
@gastaldi FYI
> feat: Mark observer methods as implicitly used

- src/main/java/com/redhat/devtools/intellij/lsp4ij/AbstractLSPInlayProvider.java
- src/main/java/com/redhat/devtools/intellij/lsp4ij/LSPIJUtils.java
- src/main/java/com/redhat/devtools/intellij/lsp4ij/LanguageServiceAccessor.java
- src/main/java/com/redhat/devtools/intellij/lsp4ij/commands/CommandExecutor.java
- src/main/java/com/redhat/devtools/intellij/lsp4ij/operations/codeactions/LSPLazyCodeActionIntentionAction.java
- src/main/java/com/redhat/devtools/intellij/lsp4ij/operations/completion/LSPCompletionProposal.java
- src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/command/MicroprofileOpenURIAction.java
- src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/command/MicroprofileUpdateConfigurationAction.java
- src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/inspections/MicroProfilePropertiesExpressionsInspection.java
- src/main/java/com/redhat/devtools/intellij/quarkus/lsp/QuarkusServer.java
- src/main/java/com/redhat/devtools/intellij/qute/psi/core/command/QuteAction.java
- src/main/java/com/redhat/devtools/intellij/qute/psi/core/command/QuteGenerateTemplateAction.java
- src/main/java/com/redhat/devtools/intellij/qute/psi/core/command/QuteJavaDefinitionAction.java
- src/main/resources/META-INF/plugin.xml
Fixes #1043 
https://github.com/redhat-developer/intellij-quarkus/assets/148698/dd80418a-e731-4cbb-8a12-793ec75ba621
> feat: add command to update microprofile configuration from LSP4MP

- .idea/icon.svg
Super important PR to customize the intellij-quarkus icon when opening in IDEA:
> build: add quarkus icon for IDEA project

- src/main/java/com/redhat/devtools/intellij/lsp4ij/LSPIJUtils.java
- src/main/java/com/redhat/devtools/intellij/lsp4ij/LSPVirtualFileWrapper.java
- src/main/java/com/redhat/devtools/intellij/lsp4ij/LanguageServerWrapper.java
- src/main/java/com/redhat/devtools/intellij/lsp4ij/LanguageServiceAccessor.java
- src/main/java/com/redhat/devtools/intellij/lsp4ij/client/IndexAwareLanguageClient.java
- src/main/java/com/redhat/devtools/intellij/lsp4ij/internal/SupportedFeatures.java
- src/main/java/com/redhat/devtools/intellij/lsp4ij/operations/diagnostics/LSPDiagnosticHandler.java
- src/main/java/com/redhat/devtools/intellij/lsp4ij/operations/documentLink/LSPDocumentLinkGotoDeclarationHandler.java
- src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/classpath/ClasspathResourceChangedListener.java
- src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/internal/core/ls/PsiUtilsLSImpl.java
- src/main/java/com/redhat/devtools/intellij/qute/lang/format/QuteFileIndentOptionsProvider.java
- src/main/java/com/redhat/microprofile/psi/internal/quarkus/renarde/java/RenardeUtils.java
fix: Bind language servers to Project instead of Module
Fixes #891
> fix: Bind language servers to Project instead of Module

- src/main/java/com/redhat/devtools/intellij/lsp4ij/operations/documentation/LSPDocumentationProvider.java
- src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/java/definition/PropertiesDefinitionParticipant.java
- src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/java/hover/PropertiesHoverParticipant.java
- src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/project/AbstractConfigSource.java
- src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/project/IConfigSource.java
- src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/project/PsiMicroProfileProject.java
- src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/project/PsiMicroProfileProjectManager.java
- src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/internal/config/java/MicroProfileConfigASTValidator.java
- src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/internal/config/java/NoValueAssignedToPropertyQuickFix.java
- src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/internal/restclient/java/MicroProfileRestClientCodeLensParticipant.java
- src/main/java/com/redhat/devtools/intellij/quarkus/QuarkusPostStartupActivity.java
- src/main/java/com/redhat/devtools/intellij/quarkus/run/QuarkusRunContext.java
- src/main/java/com/redhat/microprofile/psi/internal/quarkus/core/properties/QuarkusConfigPropertiesProvider.java
- src/main/java/com/redhat/microprofile/psi/internal/quarkus/jaxrs/java/QuarkusJaxRsCodeLensParticipant.java
fix: Java file diagnostics is not refreshed when properties file is saved
Fixes #860
> fix: Java file diagnostics is not refreshed when properties file is saved

- src/main/java/com/redhat/devtools/intellij/lsp4ij/DocumentContentSynchronizer.java
- src/main/java/com/redhat/devtools/intellij/lsp4ij/LanguageServerWrapper.java
Rename file doesn't send didClose / didOpen LSP notification
Fixes #1097
Fixes #836
> fix: Rename file doesn't send didClose / didOpen LSP notification

- projects/lsp4mp/projects/maven/microprofile-graphql/pom.xml
- projects/lsp4mp/projects/maven/microprofile-graphql/src/main/java/io/openliberty/graphql/sample/Optimistic.java
- projects/lsp4mp/projects/maven/microprofile-graphql/src/main/java/io/openliberty/graphql/sample/WeatherService.java
- src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/internal/graphql/MicroProfileGraphQLConstants.java
- src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/internal/graphql/TypeSystemDirectiveLocation.java
- src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/internal/graphql/java/MicroProfileGraphQLASTValidator.java
- src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/internal/graphql/java/MicroProfileGraphQLErrorCode.java
- src/main/java/com/redhat/devtools/intellij/quarkus/QuarkusModuleUtil.java
- src/test/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/graphql/java/MicroProfileGraphQLValidationTest.java
- Remove the check that forbids returning `void` from GraphQL operations. This is legal in recent Quarkus versions.
- Add some checks for the correct placement of GraphQL directives.
> feat: GraphQL improvements

- projects/qute/projects/maven/qute-quickstart/src/main/java/org/acme/qute/ItemTemplates.java
- projects/qute/projects/maven/qute-quickstart/src/main/java/org/acme/qute/ItemTemplatesIgnoreFragments.java
- src/main/java/com/redhat/devtools/intellij/qute/psi/QuteSupportForTemplate.java
- src/main/java/com/redhat/devtools/intellij/qute/psi/internal/java/AbstractQuteTemplateLinkCollector.java
- src/main/java/com/redhat/devtools/intellij/qute/psi/internal/template/QuteSupportForTemplateGenerateMissingJavaMemberHandler.java
- src/main/java/com/redhat/devtools/intellij/qute/psi/internal/template/TemplateDataLocation.java
- src/main/java/com/redhat/devtools/intellij/qute/psi/internal/template/datamodel/CheckedTemplateSupport.java
- src/main/java/com/redhat/devtools/intellij/qute/psi/internal/template/datamodel/TemplateDataAnnotationSupport.java
- src/main/java/com/redhat/devtools/intellij/qute/psi/internal/template/datamodel/TemplateFieldSupport.java
- src/main/java/com/redhat/devtools/intellij/qute/psi/internal/template/datamodel/TypeSafeMessageBundlesSupport.java
- src/main/java/com/redhat/devtools/intellij/qute/psi/internal/template/resolvedtype/DefaultResolvedJavaTypeFactory.java
- src/main/java/com/redhat/devtools/intellij/qute/psi/template/datamodel/AbstractFieldDeclarationTypeReferenceDataModelProvider.java
- src/main/java/com/redhat/devtools/intellij/qute/psi/utils/PsiQuteProjectUtils.java
- src/test/java/com/redhat/devtools/intellij/qute/psi/java/JavaCodeLensTest.java
- src/test/java/com/redhat/devtools/intellij/qute/psi/java/JavaDiagnosticsTest.java
- src/test/java/com/redhat/devtools/intellij/qute/psi/java/JavaDocumentLinkTest.java
fix: Qute fragments doesn't work with non inner Templates Java file
Fixes #1169
Given this non inner class:
```java
package org.acme;
import io.quarkus.qute.CheckedTemplate;
import io.quarkus.qute.TemplateInstance;
@CheckedTemplate
public class Templates {
public static native TemplateInstance auth$emailVerification(String email);
}
```
With this PR Fragment should be recognized
> fix: Qute fragments doesn't work with non inner Templates Java file

- projects/qute/projects/maven/qute-quickstart/src/main/java/org/acme/qute/ItemResourceWithCustomBasePath.java
- projects/qute/projects/maven/qute-quickstart/src/main/java/org/acme/qute/ItemTemplatesCustomBasePath.java
- src/main/java/com/redhat/devtools/intellij/qute/psi/internal/QuteJavaConstants.java
- src/main/java/com/redhat/devtools/intellij/qute/psi/internal/java/AbstractQuteTemplateLinkCollector.java
- src/main/java/com/redhat/devtools/intellij/qute/psi/internal/java/QuteJavaCodeLensCollector.java
- src/main/java/com/redhat/devtools/intellij/qute/psi/internal/java/QuteJavaDiagnosticsCollector.java
- src/main/java/com/redhat/devtools/intellij/qute/psi/internal/java/QuteJavaDocumentLinkCollector.java
- src/main/java/com/redhat/devtools/intellij/qute/psi/internal/template/datamodel/CheckedTemplateSupport.java
- src/main/java/com/redhat/devtools/intellij/qute/psi/internal/template/datamodel/TemplateFieldSupport.java
- src/main/java/com/redhat/devtools/intellij/qute/psi/utils/PsiQuteProjectUtils.java
- src/test/java/com/redhat/devtools/intellij/qute/psi/java/JavaCodeLensTest.java
- src/test/java/com/redhat/devtools/intellij/qute/psi/java/JavaDiagnosticsTest.java
- src/test/java/com/redhat/devtools/intellij/qute/psi/java/JavaDocumentLinkTest.java
Still need to :
- handle corner cases, i.e empty paths, several "/"s
- write tests
> fix: respect basePath in @CheckedTemplate to find templates

- gradle.properties
- src/main/java/com/redhat/devtools/intellij/qute/lsp/QuteLanguageClient.java
- src/main/java/com/redhat/devtools/intellij/qute/psi/QuteSupportForTemplate.java
- src/main/java/com/redhat/devtools/intellij/qute/psi/utils/PsiQuteProjectUtils.java
fix: Qute support for multi module project doesn't work
Fixes #1164
Here a demo with https://github.com/gbourant/multi-module-template-test //cc @gbourant
> fix: Qute support for multi module project doesn't work

- src/main/java/com/redhat/devtools/intellij/lsp4ij/AbstractDocumentMatcher.java
- src/main/java/com/redhat/devtools/intellij/lsp4ij/ContentTypeToLanguageServerDefinition.java
- src/main/java/com/redhat/devtools/intellij/lsp4ij/DocumentMatcher.java
- src/main/java/com/redhat/devtools/intellij/lsp4ij/LanguageMappingExtensionPointBean.java
- src/main/java/com/redhat/devtools/intellij/lsp4ij/LanguageServersRegistry.java
- src/main/java/com/redhat/devtools/intellij/lsp4ij/LanguageServiceAccessor.java
- src/main/java/com/redhat/devtools/intellij/lsp4ij/client/LSPCompletableFuture.java
- src/main/java/com/redhat/devtools/intellij/lsp4ij/internal/PromiseToCompletableFuture.java
- src/main/java/com/redhat/devtools/intellij/quarkus/QuarkusModuleUtil.java
- src/main/java/com/redhat/devtools/intellij/quarkus/lsp/AbstractQuarkusDocumentMatcher.java
- src/main/java/com/redhat/devtools/intellij/quarkus/lsp/QuarkusDocumentMatcherForJavaFile.java
- src/main/java/com/redhat/devtools/intellij/quarkus/lsp/QuarkusDocumentMatcherForPropertiesFile.java
- src/main/java/com/redhat/devtools/intellij/qute/lang/QuteLanguageSubstitutor.java
- src/main/java/com/redhat/devtools/intellij/qute/lsp/AbstractQuteDocumentMatcher.java
- src/main/java/com/redhat/devtools/intellij/qute/lsp/QuteDocumentMatcherForJavaFile.java
- src/main/java/com/redhat/devtools/intellij/qute/lsp/QuteDocumentMatcherForTemplateFile.java
- src/main/java/com/redhat/devtools/intellij/qute/psi/utils/PsiQuteProjectUtils.java
- src/main/resources/META-INF/lsp4ij-quarkus.xml
- src/main/resources/META-INF/lsp4ij-qute.xml
- src/test/java/com/redhat/devtools/intellij/quarkus/completion/MavenApplicationPropertiesCompletionTest.java
feat: Check if project is a MicroProfile, Qute, etc project to map file with a language server
Fixes #850
Fixes #1121
This PR provides a new API `DocumentMatcher` which is used to match the document with a language server. This matcher is called if the file language is mapped with a language server. Once language is matched, teh document filter is processed to have more robust filter:
* for properties file, we check the  name of properties files which fixes #1121
* for Java file, we check that the file belong to a Quarkus / Qute project. It means that if you have a java project which is not a Qute / Quarkus project, language server should never started
* for HTML files, we check that html files belongs to templates folder and belong to a Qute project.
The `DocumentMatcher` is used for the …
> feat: Check if project is a MicroProfile, Qute, etc project to map file with a language server

- src/main/java/com/redhat/devtools/intellij/lsp4ij/console/LSPConsoleToolWindowPanel.java
fix: NoClassDefFoundError: org/apache/commons/lang/exception/ExceptionUtils in IJ 2023.3 EAP
Fixes #1191
> fix: NoClassDefFoundError: org/apache/commons/lang/exception/ExceptionUtils in IJ 2023.3 EAP

- src/main/java/com/redhat/devtools/intellij/lsp4ij/operations/documentation/LSPTextHoverForFile.java
- src/main/java/com/redhat/devtools/intellij/lsp4ij/operations/highlight/LSPHighlightUsagesHandlerFactory.java
fix: Support null file in LSPHighlightUsagesHandlerFactory
Fixes #1197
> fix: Support null file in LSPHighlightUsagesHandlerFactory

- src/main/resources/static-properties/quarkus-hibernate-orm-metadata.json
This PR adds a missing value to quarkus.hibernate-orm.database.generation.
While addressing this issue, I searched for references and discovered a test: [MavenQuarkusHibernateORMPropertyTest](https://github.com/redhat-developer/intellij-quarkus/blob/main/src/test/java/com/redhat/microprofile/psi/quarkus/MavenQuarkusHibernateORMPropertyTest.java). There is a description value which includes ```Accepted values:``` and is also missing ```validate``` value. Since I couldn't determine where the test pulls its expected values from, I was unable to add the missing value ```validate```
> fix(auto-complete): added missing validate value to hibernate auto-complete

- src/main/java/com/redhat/devtools/intellij/quarkus/lsp/QuarkusServer.java
- src/main/java/com/redhat/devtools/intellij/qute/lsp/QuteServer.java
In EAP, tlemetry is unloaded (I need to investigate that) and when language servers are started the telemetry crashes. This PR catch the the call of telemetry to show the following stack trace and give the capability to start language servers even if telemetry crashes.
```
Error while consuming telemetry service
java.lang.NullPointerException: Cannot invoke "com.redhat.devtools.intellij.telemetry.core.service.TelemetryServiceFactory.create(java.lang.ClassLoader)" because "factory" is null
at com.redhat.devtools.intellij.telemetry.core.service.TelemetryMessageBuilder$ServiceFacade.createService(TelemetryMessageBuilder.java:260)
at com.redhat.devtools.intellij.telemetry.core.service.TelemetryMessageBuilder$ServiceFacade.send(TelemetryMessageBuilder.java:251)
at …
```
> fix: Prevent from telemetry crash when language servers starts

- src/main/java/com/redhat/devtools/intellij/lsp4ij/operations/diagnostics/LSPDiagnosticsForServer.java
- src/main/java/com/redhat/devtools/intellij/quarkus/lsp/QuarkusLanguageClient.java
fix: CodeAction in Java file doesn't work in IDEA EAP 2023-3 EAP
Fixes #1214
> fix: CodeAction in Java file doesn't work in IDEA EAP 2023-3 EAP

- src/main/java/com/redhat/devtools/intellij/qute/psi/internal/java/QuteJavaCodeLensCollector.java
fix: Create template from codelens doesn't work in IDEA EAP 2023-3 EAP
Fixes #1216
> fix: Create template from codelens doesn't work in IDEA EAP 2023-3 EAP

- src/main/java/com/redhat/devtools/intellij/lsp4ij/ConnectDocumentToLanguageServerSetupParticipant.java
- src/main/java/com/redhat/devtools/intellij/lsp4ij/LanguageServiceAccessor.java
This PR tries to connect a file which is opened by setting the read action allowed (with non blocing read action) by keeping checking that index is finished (to start language server).
As document matcher requires read action, we are sure that when a file is opened, the read action is allowed.
> perf: set read action allowed when file is opened

- src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/JavaEEImplicitUsageProvider.java
> fix: Non-public @Observes methods should be implicitly used

- src/main/java/com/redhat/devtools/intellij/lsp4ij/ConnectDocumentToLanguageServerSetupParticipant.java
This PR removes the code which get the Document from the given file because:
* LSP API workw now with VirtualFile instead of Document (we don't need it)
* getting Document from a VirtualFile requires to be in read action mode.
> perf: don't get document when file is opened

- src/main/java/com/redhat/devtools/intellij/qute/lang/highlighter/QuteHighlighterColors.java
Fixes #1181 (hopefully, as I wasn't able to reproduce)
Keys are prefixed with QUTE_TOOLS, to minimize chances of conflicts with IJ Ultimate
> fix: make Qute TextAttributeKeys unique (hopefully)

- src/main/java/com/redhat/devtools/intellij/lsp4ij/ConnectDocumentToLanguageServerSetupParticipant.java
fix: call init when open file must start ls while indexing.
> fix: call init when open file must start ls while indexing.

- src/main/java/com/redhat/devtools/intellij/lsp4ij/console/LSPConsoleToolWindowPanel.java
Fixes rare NPE:
```
java.lang.NullPointerException: Cannot invoke “com.intellij.execution.ui.ConsoleView.print(String, com.intellij.execution.ui.ConsoleViewContentType)” because “this.consoleView” is null
at com.redhat.devtools.intellij.lsp4ij.console.LSPConsoleToolWindowPanel$ConsoleContentPanel.showMessage(LSPConsoleToolWindowPanel.java:249)
[15:05](https://redhat-internal.slack.com/archives/DK4SDAQJH/p1697634348846939)
```
> fix: prevent NPE when calling ConsoleContentPanel.showMessage

- src/main/java/com/redhat/devtools/intellij/lsp4ij/LSPIJUtils.java
- src/main/java/com/redhat/devtools/intellij/lsp4ij/operations/completion/LSPCompletionContributor.java
- src/main/java/com/redhat/devtools/intellij/lsp4ij/operations/documentLink/LSPDocumentLinkAnnotator.java
- src/main/java/com/redhat/devtools/intellij/lsp4ij/operations/highlight/LSPHighlightUsagesHandlerFactory.java
- src/main/java/com/redhat/devtools/intellij/lsp4ij/operations/navigation/LSPGotoDeclarationHandler.java
fix: Argument for @NotNull parameter 'file' of com/intellij/openapi/vfs/VfsUtilCore.virtualToIoFile must not be null
Fixes #1228
> fix: Argument for @NotNull parameter 'file' of com/intellij/openapi/vfs/VfsUtilCore.virtualToIoFile must not be null

- src/main/java/com/redhat/devtools/intellij/lsp4ij/LanguageServerWrapper.java
> fix: don't crash on project name containing %

- src/main/java/com/redhat/devtools/intellij/lsp4ij/ContentTypeToLanguageServerDefinition.java
- src/main/java/com/redhat/devtools/intellij/lsp4ij/LanguageServersRegistry.java
- src/main/java/com/redhat/devtools/intellij/lsp4ij/ServerExtensionPointBean.java
- src/main/java/com/redhat/devtools/intellij/lsp4ij/internal/PromiseToCompletableFuture.java
- don't use smart mode when in light edit
- added new supportsLightEdit property to LS definitions, so some LS can be allowed in Light Edit mode. Disabled by default, so no Quarkus nor Qute LS are spawned in Light Edit mode
Fixes #1244 
To test this fix, you need to install the corresponding build in the IDEA installation used to open a java file on double-click, or via `idea <filename>.java` in a terminal
> fix: disallow language servers in light edit mode

- src/main/java/com/redhat/devtools/intellij/lsp4ij/operations/documentation/LSPDocumentationProvider.java
To reproduce, scroll down to bottom of the String Javadoc, the click on the link.
Before the fix:
After the fix:
This also prevents an exception:
```
java.lang.Throwable: Write-unsafe context! Model changes are allowed from write-safe contexts only. Please ensure you're using invokeLater/invokeAndWait with a correct modality state (not "any"). See TransactionGuard documentation for details.
current modality=ModalityState.NON_MODAL
at com.intellij.openapi.diagnostic.Logger.error(Logger.java:184)
at com.intellij.openapi.application.TransactionGuardImpl.assertWriteActionAllowed(TransactionGuardImpl.java:135)
at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileImpl4Edt(FileEditorManagerImpl.java:975)
at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.lambda$openFil …
```
> fix: ignore non-local files in LSPDocumentationProvider#handleExternalLink

- src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/utils/PsiTypeUtils.java
- src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/internal/core/ls/PsiUtilsLSImpl.java
- src/main/java/com/redhat/devtools/intellij/qute/psi/utils/PsiTypeUtils.java
fix: Jump to inner Java class from property doesn't work.
Fixes #1256
> fix: Jump to inner Java class from property doesn't work.

- src/main/java/com/redhat/devtools/intellij/quarkus/gradle/AbstractGradleToolDelegate.java
- src/main/java/com/redhat/devtools/intellij/quarkus/maven/MavenToolDelegate.java
The 'Before launch' tasks are configured in the QuarkusRunConfiguration. The must be added to the MavenRunConfiguration and GradleRunConfiguration, which are the ones which are actually executed.
Fixes #1259
> fix: Copy 'Run launch' tasks to the Maven run configuration

- src/main/java/com/redhat/devtools/intellij/quarkus/projectWizard/QuarkusExtensionsModel.java
- src/main/java/com/redhat/devtools/intellij/quarkus/projectWizard/QuarkusExtensionsStep.java
- src/main/java/com/redhat/devtools/intellij/quarkus/projectWizard/QuarkusModel.java
- src/main/java/com/redhat/devtools/intellij/quarkus/projectWizard/QuarkusModuleInfoStep.java
If you try to create a new Quarkus project with the wizard, set the name to "foobar", go to the last page, the project name and location are set to "foobar". Now if you go back and change the artifactId to "barfoo", on the last page, the name and location are reset to "code-with-quarkus". Additionally, any other changes made on the module info step page are lost (eg. if you changed the build to gradle, the generated project will use Maven)
This PR fixes this issue by avoiding the reinitialization of UI components in QuarkusModuleInfoStep._init()
> fix: retain input on wizard page back navigation

- src/main/java/com/redhat/devtools/intellij/quarkus/buildtool/maven/MavenToolDelegate.java
- src/main/java/com/redhat/devtools/intellij/quarkus/buildtool/maven/MavenWrapperUtils.java
> feat: configure Maven wrapper usage if available

- src/main/java/com/redhat/devtools/intellij/quarkus/QuarkusConstants.java
- src/main/java/com/redhat/devtools/intellij/quarkus/QuarkusModuleUtil.java
- src/main/java/com/redhat/devtools/intellij/quarkus/run/QuarkusRunConfiguration.java
- src/main/java/com/redhat/devtools/intellij/quarkus/run/dashboard/QuarkusRunDashboardCustomizer.java
- src/main/resources/META-INF/plugin.xml
fix: Connect Quarkus run configuration with Services view support
Fixes #1265
Here a demo:
Please note that link of App and Dev UI are in the same line than Running. I wanted to display thoses 2 links as Running child but it seems it is not possible.
> fix: Connect Quarkus run configuration with Services view support

- src/main/java/com/redhat/devtools/intellij/lsp4ij/LanguageServiceAccessor.java
- src/main/java/com/redhat/devtools/intellij/lsp4ij/ServerMessageHandler.java
- src/main/java/com/redhat/devtools/intellij/lsp4ij/console/explorer/LanguageServerProcessTreeNode.java
- src/main/java/com/redhat/devtools/intellij/lsp4ij/lifecycle/LanguageServerLifecycleManager.java
- src/main/java/com/redhat/devtools/intellij/lsp4ij/operations/diagnostics/LSPDiagnosticHandler.java
- src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/classpath/ClasspathResourceChangedManager.java
- src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/project/AbstractConfigSource.java
- src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/project/PsiMicroProfileProjectManager.java
- src/main/java/com/redhat/devtools/intellij/quarkus/QuarkusDeploymentSupport.java
- src/main/java/com/redhat/devtools/intellij/quarkus/QuarkusProjectService.java
- src/main/java/com/redhat/devtools/intellij/quarkus/buildtool/gradle/AbstractGradleToolDelegate.java
- src/main/java/com/redhat/devtools/intellij/quarkus/facet/QuarkusFrameworkDetector.java
- src/main/java/com/redhat/devtools/intellij/quarkus/lsp/QuarkusServer.java
- src/main/java/com/redhat/devtools/intellij/qute/facet/QuteFrameworkDetector.java
- src/main/java/com/redhat/devtools/intellij/qute/lang/psi/QuteElementType.java
- src/main/java/com/redhat/devtools/intellij/qute/lsp/QuteServer.java
- src/main/resources/META-INF/lsp4ij.xml
> chore: fix some deprecation warnings

- src/main/java/com/redhat/devtools/intellij/quarkus/buildtool/gradle/AbstractGradleToolDelegate.java
- src/main/java/com/redhat/devtools/intellij/quarkus/buildtool/maven/MavenToolDelegate.java
- src/main/java/com/redhat/devtools/intellij/quarkus/run/QuarkusRunConfigurationManager.java
fix: Read action when project is imported
> fix: Read action when project is imported

- src/main/java/com/redhat/devtools/intellij/lsp4ij/ConnectDocumentToLanguageServerSetupParticipant.java
- src/main/java/com/redhat/devtools/intellij/quarkus/QuarkusModuleUtil.java
- src/main/java/com/redhat/devtools/intellij/quarkus/json/QuarkusJsonSchemaProvider.java
- src/main/java/com/redhat/devtools/intellij/qute/lang/QuteLanguageSubstitutor.java
perf: Avoid using ModuleUtilCore#findModuleForFile which can block IJ since 2023.3 Beta2
Fixes #1272
> perf: Avoid using ModuleUtilCore#findModuleForFile which can block IJ since 2023.3 Beta2

- src/main/resources/META-INF/lsp4ij-quarkus.xml
- src/main/resources/META-INF/lsp4ij-qute.xml
feat: remove LSP codeLens/inlahint declaration by using inlay hint factory
This PR requires https://github.com/redhat-developer/lsp4ij/pull/44
> feat: remove LSP codeLens/inlahint declaration by using inlay hint factory

- src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/project/AbstractConfigSource.java
Since 2022.3 apparently, log events with error severity now bubble up as error popups in a user's face.
This PR fixes #1282 until we drop SnakeYAML for good, but most likely other places where a log.error is met will have the same issue
> fix: log YAML parsing errors as warning to avoid popup

- src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/MicroProfileConfigConstants.java
- src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/command/MicroprofileOpenURIAction.java
- src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/command/MicroprofileUpdateConfigurationAction.java
- src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/internal/config/java/MicroProfileConfigASTValidator.java
- src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/internal/config/java/NoValueAssignedToPropertyQuickFix.java
- src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/internal/config/java/PropertyNameData.java
- src/main/java/com/redhat/devtools/intellij/quarkus/lsp/QuarkusLanguageClient.java
- src/main/java/com/redhat/devtools/intellij/qute/psi/core/command/QuteAction.java
- src/main/java/com/redhat/devtools/intellij/qute/psi/core/command/QuteGenerateTemplateAction.java
- src/main/java/com/redhat/devtools/intellij/qute/psi/core/command/QuteJavaDefinitionAction.java
- src/main/java/com/redhat/devtools/intellij/qute/psi/core/command/QuteOpenURIAction.java
- src/main/java/com/redhat/devtools/intellij/qute/psi/core/command/QuteUpdateConfigurationAction.java
fix: use JSONUtils from LSP4IJ
This PR requires https://github.com/redhat-developer/lsp4ij/pull/56 to avoid having this LinkageError error problem when code action is resolved:
```
Internal error: java.lang.LinkageError: loader constraint violation: when resolving method 'com.google.gson.Gson org.eclipse.lsp4j.jsonrpc.json.MessageJsonHandler.getGson()' the class loader com.intellij.ide.plugins.cl.PluginClassLoader @47dad50f of the current class, org/eclipse/lsp4mp/commons/utils/JSONUtility, and the class loader com.intellij.ide.plugins.cl.PluginClassLoader @54c5da1d for the method's defining class, org/eclipse/lsp4j/jsonrpc/json/MessageJsonHandler, have different Class objects for the type com/google/gson/Gson used in the signature (org.eclipse.lsp4mp.commons.utils.JSONUtility is in …
```
> fix: use JSONUtils from LSP4IJ

- build.gradle.kts
- src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/internal/core/ls/PsiUtilsLSImpl.java
- src/main/java/com/redhat/devtools/intellij/quarkus/javadoc/JavaDoc2MarkdownConverter.java
- src/main/java/com/redhat/microprofile/psi/internal/quarkus/kubernetes/properties/QuarkusKubernetesProvider.java
- src/test/java/com/redhat/devtools/intellij/qute/psi/template/TemplateGetJavadocTest.java
- src/test/java/com/redhat/microprofile/psi/quarkus/QuarkusKubernetesTest.java
Replaces obsolete, unmaintained, unsecure remark with flexmark.
Fixes an issue with documentation always being returned as plaintext instead of markdown.
Works best with https://github.com/redhat-developer/lsp4ij/pull/59
> build: replace remark with flexmark

- src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/internal/core/ls/PsiUtilsLSImpl.java
Required after https://github.com/redhat-developer/lsp4ij/pull/78
> chore: migrate LSPIJUtils.toLocation into PsiUtilsLSImpl

- src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/project/PsiMicroProfileProject.java
I've seen this once after reopening IJ after deleting a quarkus config file:
```
java.lang.Throwable: Invalid file: file:///Users/fbricon/Dev/projects/intellij-quarkus/projects/lsp4mp/projects/maven/config-hover/src/main/resources/application-foo.properties (invalid)
at com.intellij.openapi.diagnostic.Logger.error(Logger.java:202)
at com.intellij.psi.impl.file.impl.FileManagerImpl.findFile(FileManagerImpl.java:357)
at com.intellij.psi.impl.PsiManagerImpl.findFile(PsiManagerImpl.java:156)
at com.redhat.devtools.intellij.lsp4mp4ij.psi.core.project.PsiMicroProfileProject.lambda$evictConfigSourcesCache$2(PsiMicroProfileProject.java:198)
at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:891)
at …
```
> fix: prevent IJ from reporting an error when config file is deleted

- src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/PropertiesManagerForJava.java
- src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/java/hover/PropertiesHoverParticipant.java
- src/main/java/com/redhat/microprofile/psi/internal/quarkus/scheduler/SchedulerErrorCodes.java
- src/main/java/com/redhat/microprofile/psi/internal/quarkus/scheduler/SchedulerUtils.java
- src/main/java/com/redhat/microprofile/psi/internal/quarkus/scheduler/java/QuarkusSchedulerASTVisitor.java
- src/main/java/com/redhat/microprofile/psi/internal/quarkus/scheduler/properties/QuarkusScheduledPropertiesProvider.java
- src/test/java/com/redhat/microprofile/psi/quarkus/scheduler/SchedulerUtilsTest.java
Fixes #1325 
Also fixes Hover, Properties validation and completion in application.properties
> fix: properly validate variables with default values in @Scheduled field

- src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/internal/core/java/codeaction/JavaCodeActionDefinition.java
- src/main/java/com/redhat/devtools/intellij/quarkus/run/QuarkusRunConfigurationManager.java
- src/main/java/com/redhat/devtools/intellij/quarkus/run/dashboard/QuarkusRunDashboardDefaultTypesProvider.java
- src/main/java/com/redhat/devtools/intellij/qute/psi/internal/template/TemplateDataVisitor.java
- src/main/resources/META-INF/plugin.xml
fix: Error while adding QuarkusRunConfigurationType in Services view settings
Fixes #1299, #1323
This PR uses the `RunDashboardDefaultTypesProvider` extension point to add automaticlly the `Quarkus Run config type` in the Services view when the option 'Create "Quarkus Dev Mode" run configuration on project import' is activated.
It avoids to add the `Quarkus Run config type`  with the `RunDashboardManager#setTypes` which can causes many problems like
* #1299
* https://github.com/redhat-developer/intellij-quarkus/issues/1323
> fix: Error while adding QuarkusRunConfigurationType in Services view settings

- .github/workflows/itests.yml
- build.gradle.kts
- src/it/java/org/jboss/tools/intellij/quarkus/fixtures/dialogs/project/pages/QuarkusNewProjectSecondPage.java
- src/it/java/org/jboss/tools/intellij/quarkus/fixtures/dialogs/project/pages/QuarkusNewProjectThirdPage.java
- src/it/java/org/jboss/tools/intellij/quarkus/tests/AbstractQuarkusTest.java
- src/it/java/org/jboss/tools/intellij/quarkus/tests/BasicTest.java
- src/it/java/org/jboss/tools/intellij/quarkus/utils/XPathDefinitions.java
Fixes #831 for windows and linux.
> fix: Fixed UI tests on Linux and Windows

- projects/qute/projects/maven/quarkus3/src/main/java/org/acme/Bean3.java
- src/main/java/com/redhat/devtools/intellij/qute/psi/utils/CDIUtils.java
- src/test/java/com/redhat/devtools/intellij/qute/psi/utils/CDIUtilsTest.java
Open https://github.com/ia3andy/one-two-three-quarkus/blob/main/dashboard/src/main/resources/templates/main.html
You will see a false positive error with `inject:csrf`:
`inject:csrf` comes from https://github.com/quarkusio/quarkus/blob/e46f2ec5588858525634e42fa1c6146162ade461/extensions/resteasy-reactive/rest-csrf/runtime/src/main/java/io/quarkus/csrf/reactive/runtime/CsrfTokenParameterProvider.java#L13
This class is flagged because it has constructor arguments https://github.com/quarkusio/quarkus/blob/e46f2ec5588858525634e42fa1c6146162ade461/extensions/resteasy-reactive/rest-csrf/runtime/src/main/java/io/quarkus/csrf/reactive/runtime/CsrfTokenParameterProvider.java#L27
Quarkus manages this arguments injection, so the  `inject:csrf` must be valid.
This PR fix the issue:
*   `inject:csrf` …
> fix: allow inject: with constructor class which have arguments

- projects/lsp4mp/projects/maven/microprofile-reactive-messaging/src/main/java/org/acme/kafka/Quote.java
- projects/lsp4mp/projects/maven/microprofile-reactive-messaging/src/main/java/org/acme/kafka/QuoteResource.java
- src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/internal/reactivemessaging/properties/MicroProfileReactiveMessagingProvider.java
- src/test/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/reactivemessaging/properties/MicroProfileReactiveMessagingTest.java
First pass at fixing the [Unrecognized property mp.messaging.* when Channel annotation is used along with Multi](https://github.com/redhat-developer/vscode-quarkus/issues/750) issue opened in VS Code Quarkus
> fix: relax @channel conditions for completion/validation

- projects/qute/projects/maven/qute-record/src/main/java/org/acme/sample/ItemResource.java
- src/main/java/com/redhat/devtools/intellij/qute/psi/internal/QuteJavaConstants.java
- src/main/java/com/redhat/devtools/intellij/qute/psi/internal/java/AbstractQuteTemplateLinkCollector.java
- src/main/java/com/redhat/devtools/intellij/qute/psi/internal/template/datamodel/CheckedTemplateSupport.java
- src/main/java/com/redhat/devtools/intellij/qute/psi/internal/template/datamodel/TemplateFieldSupport.java
- src/main/java/com/redhat/devtools/intellij/qute/psi/internal/template/datamodel/TemplateRecordsSupport.java
- src/main/java/com/redhat/devtools/intellij/qute/psi/utils/PsiQuteProjectUtils.java
- src/main/java/com/redhat/devtools/intellij/qute/psi/utils/TemplateNameStrategy.java
- src/test/java/com/redhat/devtools/intellij/qute/psi/java/MavenJavaCodeLensTest.java
- src/test/java/com/redhat/devtools/intellij/qute/psi/java/MavenJavaDiagnosticsTest.java
- src/test/java/com/redhat/devtools/intellij/qute/psi/java/MavenJavaDocumentLinkTest.java
- src/test/java/com/redhat/devtools/intellij/qute/psi/template/TemplateGetDataModelProjectTest.java
feat: Qute: Cannot locate hyphenated template name
Fixes https://github.com/redhat-developer/quarkus-ls/issues/975
You can play with the qute-record test project:
//cc @gbourant
> feat: Qute: Cannot locate hyphenated template name

- projects/lsp4mp/projects/maven/config-quickstart/src/main/java/org/acme/config/GreetingResource.java
- src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/PropertiesManagerForJava.java
- src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/java/codelens/IJavaCodeLensParticipant.java
- src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/java/completion/IJavaCompletionParticipant.java
- src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/java/definition/IJavaDefinitionParticipant.java
- src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/java/diagnostics/IJavaDiagnosticsParticipant.java
- src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/java/hover/IJavaHoverParticipant.java
- src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/java/symbols/IJavaWorkspaceSymbolsParticipant.java
- src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/jaxrs/IJaxRsInfoProvider.java
- src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/internal/jaxrs/java/DefaultJaxRsInfoProvider.java
- src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/internal/jaxrs/java/JaxRsInfoProviderRegistry.java
- src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/internal/jaxrs/java/JaxRsWorkspaceSymbolParticipant.java
- src/main/java/com/redhat/devtools/intellij/quarkus/lsp/QuarkusLanguageClient.java
- src/main/java/com/redhat/microprofile/psi/internal/quarkus/renarde/java/RenardeJaxRsInfoProvider.java
- src/main/java/com/redhat/microprofile/psi/internal/quarkus/renarde/java/RenardeUtils.java
- src/main/java/com/redhat/microprofile/psi/internal/quarkus/route/java/ReactiveRouteJaxRsInfoProvider.java
- src/main/resources/META-INF/plugin.xml
- src/test/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/MicroProfileForJavaAssert.java
- src/test/java/com/redhat/microprofile/psi/quarkus/jaxrs/JaxRsWorkspaceSymbolParticipantTest.java
- src/test/java/com/redhat/microprofile/psi/quarkus/renarde/RenardeJaxRsTest.java
feat: Workspace symbols for JAX-RS endpoints
Fixes #1363
This PR provides JAX-RS and Renarde workspace symbol. For Renarde it uses the scope (if you select Project And Libraries scope you can see Renarde controller declared in the JAR Renarde):
//cc @ia3andy
> feat: Workspace symbols for JAX-RS endpoints

- gradle.properties
- src/main/java/com/redhat/devtools/intellij/quarkus/TelemetryService.java
bumps telemetry to 1.2.1 and fixes the deprecation message
> fix: bumped telemetry to 1.2.1

- src/main/java/com/redhat/devtools/intellij/quarkus/projectWizard/QuarkusExtensionsStep.java
Unselect by default the platform checkbox to retrieve for instance langChain4j qurkus extensions:
> fix: set platformOnly to false to collect all extensions in the wizard

- build.gradle.kts
- gradle.properties
chore: use releases of LSP4MP 0.12.0 + Quarkus LS 0.19.0
> chore: use releases of LSP4MP 0.12.0 + Quarkus LS 0.19.0

- src/main/java/com/redhat/devtools/intellij/qute/psi/internal/template/datamodel/CheckedTemplateSupport.java
- src/main/java/com/redhat/devtools/intellij/qute/psi/internal/template/datamodel/TemplateRecordsSupport.java
fix: prevent from duplicate Qute parameter key
Even if I can repoduce a problem like vscode-quarkus, I create this PR to be aligned with JDT code of the PR
https://github.com/redhat-developer/quarkus-ls/pull/988
> fix: prevent from duplicate Qute parameter key

- src/main/java/com/redhat/devtools/intellij/quarkus/buildtool/BuildToolDelegate.java
- src/main/java/com/redhat/devtools/intellij/quarkus/buildtool/gradle/AbstractGradleToolDelegate.java
- src/main/java/com/redhat/devtools/intellij/quarkus/buildtool/gradle/GradleRunAndDebugProgramRunner.java
- src/main/java/com/redhat/devtools/intellij/quarkus/buildtool/maven/MavenToolDelegate.java
- src/main/java/com/redhat/devtools/intellij/quarkus/buildtool/maven/QuarkusMavenDebugProgramRunner.java
- src/main/java/com/redhat/devtools/intellij/quarkus/buildtool/maven/QuarkusMavenRunProgramRunner.java
- src/main/java/com/redhat/devtools/intellij/quarkus/run/AttachDebuggerExecutionListener.java
- src/main/java/com/redhat/devtools/intellij/quarkus/run/AttachDebuggerProcessListener.java
- src/main/java/com/redhat/devtools/intellij/quarkus/run/QuarkusRunConfiguration.java
- src/main/java/com/redhat/devtools/intellij/quarkus/run/QuarkusRunConfigurationManager.java
- src/main/java/com/redhat/devtools/intellij/qute/psi/template/datamodel/AbstractInterfaceImplementationDataModelProvider.java
- src/main/resources/META-INF/plugin.xml
fix: Debug run config invalid with Gradle
Fixes #1311
> fix: Debug run config invalid with Gradle

- src/main/resources/META-INF/lsp4ij-quarkus.xml
fix: set languageId to have highlight with LSP4IJ 0.7.0
LSP4IJ 0.7.0 will support documentSelector and  dynamic capabilities with PR https://github.com/redhat-developer/lsp4ij/pull/566
MicroProfile LS supports `textDocument/documentHighlight` with dynamic capability and set the documentSelector for the `microprofile-properties` languageId:
```json
[Trace - 20:07:06] Received request 'client/registerCapability - (9)'
Params: {
"registrations": [
{
"id": "04793b8a-d455-49f8-8c45-d932f15a1714",
"method": "textDocument/documentHighlight",
"registerOptions": {
"documentSelector": [
{
"language": "microprofile-properties"
}
]
}
}
]
}
```
It means that  `textDocument/documentHighlight` LSP request must be only sent for "microprofile-properties" language and not for java files which works like …
> fix: set languageId to have highlight with LSP4IJ 0.7.0

- src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/internal/openapi/java/MicroProfileGenerateOpenAPIOperation.java
In MicroProfileGenerateOpenAPIOperation we call `PsiClass.getQualifiedName()` which is nullable. It returns null when the class is local or a type parameter. In our test case we used a type parameter so we see the need to check the return type.
Fixes #1397
> fix: Check for null or empty class name in generate OpenAPI annotations

- src/main/java/com/redhat/microprofile/psi/internal/quarkus/core/properties/QuarkusConfigRootProvider.java
fix: remove ConfigPhase.BOOTSRAP which has been removed from Quarkus.
> fix: remove ConfigPhase.BOOTSRAP which has been removed from Quarkus.

- projects/lsp4mp/projects/maven/hibernate-orm-resteasy-yaml/src/main/java/org/acme/hibernate/orm/FruitResource.java
- projects/lsp4mp/projects/maven/hibernate-orm-resteasy/src/main/java/org/acme/hibernate/orm/FruitResource.java
- src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/jaxrs/JaxRsContext.java
- src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/utils/AnnotationUtils.java
- src/main/java/com/redhat/microprofile/psi/internal/quarkus/jaxrs/java/QuarkusJaxRsCodeLensParticipant.java
- src/test/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/jaxrs/java/JaxRsCodeLensTest.java
fix: REST endpoint code vision hint is not resolving a public static final and quarkus.rest.path parameter
Fixes #1393
* fix: for:  REST endpoint code vision hint is not resolving a public static final
* fix for quarkus.rest.path
With `quarkus.rest.path=bar` in `application.properties`:
> fix: REST endpoint code vision hint is not resolving a public static final and quarkus.rest.path parameter

- src/main/java/com/redhat/devtools/intellij/quarkus/QuarkusConstants.java
- src/main/java/com/redhat/microprofile/psi/internal/quarkus/core/properties/ConfigProperties.java
- src/main/java/com/redhat/microprofile/psi/internal/quarkus/core/properties/QuarkusConfigPropertiesProvider.java
> fix: naming strategy

- src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/ProjectLabelManager.java
- src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/PropertiesManager.java
- src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/PropertiesManagerForJava.java
- Replaced deprecated method `DumbService.runReadActionInSmartMode(Computable)`
- Removed unused DumbService and other imports in related files
- Changed copyright year to 2025
Fixes #1420
> fix: Modification to replace the usage of deprecated method DumbService.runReadActionInSmartMode(Computable)

- src/main/java/com/redhat/devtools/intellij/qute/lsp/QuteClientFeatures.java
- src/main/java/com/redhat/devtools/intellij/qute/lsp/QuteDiagnosticFeature.java
- src/main/java/com/redhat/devtools/intellij/qute/lsp/QuteLanguageServerFactory.java
- src/main/java/com/redhat/devtools/intellij/qute/psi/core/inspections/QuteLSPLocalInspectionTool.java
- src/main/resources/META-INF/lsp4ij-qute.xml
feat: define a custom LSP local inspection tool for Qute
This PR provides the capability to display all Qute errors of all Projetc by executing "`Inspect Code...`" from the Problem view:
Here the result with quarkus-roq:
//cc @ia3andy
> feat: define a custom LSP local inspection tool for Qute

- src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/ProjectLabelManager.java
- src/main/java/com/redhat/devtools/intellij/quarkus/lsp/QuarkusLanguageClient.java
- src/main/resources/META-INF/plugin.xml
- src/test/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/GradleProjectLabelTest.java
- src/test/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/ProjectLabelTest.java
While fixing a bug in LSP4IJ with workspace symbols, I have noticed that workspace symbols is queried for all opened project (search of JAX-RS method in Symbol tab (Ctrl+N) is done for all opened project  and not for the current project.
This behavior is bad:
* for feature: you see JAX-RS methods coming from other opened project which is wrong.
* for performance, worlspace symbols is triggered for all opened project.
After debugging IntelliJ Quarkus, I have noticed the problem comes from ProjectLabelManager which uses all opened project instead of using the current project.
This PR fixes those 2 problems (features + performance).
> fix: Get project labels from a given project

- src/main/java/com/redhat/devtools/intellij/quarkus/run/AttachDebuggerProcessListener.java
feat: Use the proper Qute debugger listening port log
> fix: Use the proper Qute debugger listening port log
